# (C) 2017 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other
# software and tools, and its AMPP partner logic functions, and any output
# files any of the foregoing (including device programming or simulation
# files), and any associated documentation or information are expressly subject
# to the terms and conditions of the Intel Program License Subscription
# Agreement, Intel MegaCore Function License Agreement, or other applicable
# license agreement, including, without limitation, that your use is for the
# sole purpose of programming logic devices manufactured by Intel and sold by
# Intel or its authorized distributors.  Please refer to the applicable
# agreement for further details.


# TCL File Generated by Component Editor 17.0
# Mon Oct 23 14:35:43 CDT 2017
# DO NOT MODIFY


# 
# magic_number_rom "Magic Number Rom" v1.0
# JCJB 2017.10.23.14:35:43
# Four location ROM that repeats a 64-bit magic number back to the master
# 

# 
# request TCL package from ACDS 17.0
# 
package require -exact qsys 17.0


# 
# module magic_number_rom
# 
set_module_property DESCRIPTION "Four location ROM that repeats a 64-bit magic number back to the master"
set_module_property NAME magic_number_rom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR JCJB
set_module_property DISPLAY_NAME "Magic Number Rom"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL magic_number_rom
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file magic_number_rom.v VERILOG PATH magic_number_rom.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL magic_number_rom
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file magic_number_rom.v VERILOG PATH magic_number_rom.v


# 
# parameters
# 
add_parameter MAGIC_NUMBER_LOW INTEGER 1400467043 "Lower 32-bits of the 64-bit magic number."
set_parameter_property MAGIC_NUMBER_LOW DISPLAY_NAME "Magic Number Low"
set_parameter_property MAGIC_NUMBER_LOW AFFECTS_GENERATION false
set_parameter_property MAGIC_NUMBER_LOW DERIVED false
set_parameter_property MAGIC_NUMBER_LOW HDL_PARAMETER true
set_parameter_property MAGIC_NUMBER_LOW AFFECTS_ELABORATION false
set_parameter_property MAGIC_NUMBER_LOW DISPLAY_HINT HEXADECIMAL

add_parameter MAGIC_NUMBER_HIGH INTEGER 1467118687 "Lower 32-bits of the 64-bit magic number."
set_parameter_property MAGIC_NUMBER_HIGH DISPLAY_NAME "Magic Number Low"
set_parameter_property MAGIC_NUMBER_HIGH AFFECTS_GENERATION false
set_parameter_property MAGIC_NUMBER_HIGH DERIVED false
set_parameter_property MAGIC_NUMBER_HIGH HDL_PARAMETER true
set_parameter_property MAGIC_NUMBER_HIGH AFFECTS_ELABORATION false
set_parameter_property MAGIC_NUMBER_HIGH DISPLAY_HINT HEXADECIMAL


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave bridgedAddressOffset ""
set_interface_property slave bridgesToMaster ""
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave minimumResponseLatency 1
set_interface_property slave readLatency 0
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave transparentBridge false
set_interface_property slave waitrequestAllowance 0
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave address address Input 2
add_interface_port slave burst burstcount Input 3
add_interface_port slave read read Input 1
add_interface_port slave readdata readdata Output 512
add_interface_port slave waitrequest waitrequest Output 1
add_interface_port slave readdatavalid readdatavalid Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

