.TH "samples/hello_afu/sw Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hello_afu/sw Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBafu_json_info\&.h\fP"
.br
.ti -1c
.RI "file \fBhello_afu\&.c\fP"
.br
.in -1c
