.TH "samples/dummy_afu Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/dummy_afu Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBddr\&.h\fP"
.br
.ti -1c
.RI "file \fBdummy_afu\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdummy_afu\&.h\fP"
.br
.ti -1c
.RI "file \fBlpbk\&.h\fP"
.br
.ti -1c
.RI "file \fBmmio\&.h\fP"
.br
.in -1c
