.TH "samples/hello_fpga Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hello_fpga Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhello_fpga\&.c\fP"
.br
.RI "A code sample illustrates the basic usage of the OPAE C API\&. "
.in -1c
