.TH "include/opae Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcxx\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccess\&.h\fP"
.br
.RI "Functions to acquire, release, and reset OPAE FPGA resources\&. "
.ti -1c
.RI "file \fBbuffer\&.h\fP"
.br
.RI "Functions for allocating and sharing system memory with an FPGA accelerator\&. "
.ti -1c
.RI "file \fBenum\&.h\fP"
.br
.RI "APIs for resource enumeration and managing tokens\&. "
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.RI "Functions for reading and clearing errors in resources\&. "
.ti -1c
.RI "file \fBevent\&.h\fP"
.br
.RI "Functions for registering events and managing the lifecycle for \fCfpga_event_handle\fPs\&. "
.ti -1c
.RI "file \fBfpga\&.h\fP"
.br
.RI "FPGA API\&. "
.ti -1c
.RI "file \fBhash_map\&.h\fP"
.br
.RI "A general-purpose hybrid array/list hash map implementation\&. "
.ti -1c
.RI "file \fBinit\&.h\fP"
.br
.RI "Initialization routine\&. "
.ti -1c
.RI "file \fBlog\&.h\fP"
.br
.ti -1c
.RI "file \fBmanage\&.h\fP"
.br
.RI "Functions for managing FPGA configurations\&. "
.ti -1c
.RI "file \fBmem_alloc\&.h\fP"
.br
.ti -1c
.RI "file \fBmetrics\&.h\fP"
.br
.RI "Functions for Discover/ Enumerates metrics and retrieves values\&. "
.ti -1c
.RI "file \fBmmio\&.h\fP"
.br
.RI "Functions for mapping and accessing MMIO space\&. "
.ti -1c
.RI "file \fBproperties\&.h\fP"
.br
.RI "Functions for examining and manipulating \fCfpga_properties\fP objects\&. "
.ti -1c
.RI "file \fBsysobject\&.h\fP"
.br
.RI "Functions to read/write from system objects\&. On Linux systems with the OPAE kernel driver, this is used to access sysfs nodes created by the driver\&. "
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.RI "Type definitions for FPGA API\&. "
.ti -1c
.RI "file \fBtypes_enum\&.h\fP"
.br
.RI "Definitions of enumerated types for the OPAE C API\&. "
.ti -1c
.RI "file \fBuio\&.h\fP"
.br
.RI "APIs to manage a PCIe device via UIO\&. "
.ti -1c
.RI "file \fBumsg\&.h\fP"
.br
.RI "FPGA UMsg API\&. "
.ti -1c
.RI "file \fBuserclk\&.h\fP"
.br
.RI "Functions for setting and get afu user clock\&. "
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.RI "Utility functions and macros for the FPGA API\&. "
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.ti -1c
.RI "file \fBvfio\&.h\fP"
.br
.RI "APIs to manage a PCIe device via vfio-pci\&. "
.in -1c
