.TH "samples Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcxl_host_exerciser\fP"
.br
.ti -1c
.RI "directory \fBcxl_mem_tg\fP"
.br
.ti -1c
.RI "directory \fBdummy_afu\fP"
.br
.ti -1c
.RI "directory \fBhello_afu\fP"
.br
.ti -1c
.RI "directory \fBhello_events\fP"
.br
.ti -1c
.RI "directory \fBhello_fpga\fP"
.br
.ti -1c
.RI "directory \fBhost_exerciser\fP"
.br
.ti -1c
.RI "directory \fBhssi\fP"
.br
.ti -1c
.RI "directory \fBmem_tg\fP"
.br
.ti -1c
.RI "directory \fBn5010\-ctl\fP"
.br
.ti -1c
.RI "directory \fBn5010\-test\fP"
.br
.ti -1c
.RI "directory \fBobject_api\fP"
.br
.in -1c
