.TH "samples/mem_tg Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/mem_tg Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmem_tg\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmem_tg\&.h\fP"
.br
.ti -1c
.RI "file \fBtg_test\&.h\fP"
.br
.in -1c
