.TH "samples/hello_events Directory Reference" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hello_events Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhello_events\&.c\fP"
.br
.RI "A code sample of using OPAE event API\&. "
.in -1c
