.TH "samples/hello_afu/sw/afu_json_info.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hello_afu/sw/afu_json_info.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAFU_ACCEL_NAME\fP   'hello_afu'"
.br
.ti -1c
.RI "#define \fBAFU_ACCEL_UUID\fP   '850ADCC2\-6CEB\-4B22\-9722\-D43375B61C66'"
.br
.ti -1c
.RI "#define \fBAFU_IMAGE_POWER\fP   0"
.br
.ti -1c
.RI "#define \fBAFU_TOP_IFC\fP   'ccip_std_afu'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AFU_ACCEL_NAME   'hello_afu'"

.PP
Definition at line 8 of file afu_json_info\&.h\&.
.SS "#define AFU_ACCEL_UUID   '850ADCC2\-6CEB\-4B22\-9722\-D43375B61C66'"

.PP
Definition at line 9 of file afu_json_info\&.h\&.
.SS "#define AFU_IMAGE_POWER   0"

.PP
Definition at line 10 of file afu_json_info\&.h\&.
.SS "#define AFU_TOP_IFC   'ccip_std_afu'"

.PP
Definition at line 11 of file afu_json_info\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
