.TH "cxl_mem_tg::mem_tg1_count" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxl_mem_tg::mem_tg1_count
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/cxl_mem_tg/cxl_mem_tg\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = MEM_TG_WR_COUNT }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBcount\fP: 64"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 174 of file cxl_mem_tg\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 175 of file cxl_mem_tg\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t cxl_mem_tg::mem_tg1_count::value"

.PP
Definition at line 176 of file cxl_mem_tg\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
