.TH "samples/cxl_mem_tg/cxl_mem_tg.cpp" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/cxl_mem_tg/cxl_mem_tg.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxl_mem_tg\&.h'\fP
.br
\fC#include <CLI/CLI\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'cxl_tg_test\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 32 of file cxl_mem_tg\&.cpp\&.
.PP
References app, opae::afu_test::afu::main(), and opae::afu_test::afu::register_command()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
