.TH "samples/cxl_host_exerciser/cxl_he_cmd.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/cxl_host_exerciser/cxl_he_cmd.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <numa\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'cxl_he_cmd\&.h'\fP
.br
\fC#include 'cxl_host_exerciser\&.h'\fP
.br
\fC#include 'he_cache_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhost_exerciser::he_cmd\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhost_exerciser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHE_TEST_STARTED\fP   'Test started \&.\&.\&.\&.\&.\&.'"
.br
.ti -1c
.RI "#define \fBHE_PRTEST_SCENARIO\fP   'Pretest scenario started \&.\&.\&.\&.\&.\&.'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HE_TEST_STARTED   'Test started \&.\&.\&.\&.\&.\&.'"

.PP
Definition at line 35 of file cxl_he_cmd\&.h\&.
.SS "#define HE_PRTEST_SCENARIO   'Pretest scenario started \&.\&.\&.\&.\&.\&.'"

.PP
Definition at line 36 of file cxl_he_cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
