.TH "dummy_afu::ddr_test_ctrl" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_afu::ddr_test_ctrl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/dummy_afu/dummy_afu\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = DDR_TEST_CTRL }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBddr_test_ctrl\fP (uint64_t v)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBDDRBank0StartTest\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBDDRBank1StartTest\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBDDRBank2StartTest\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBDDRBank3StartTest\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBReserved4\fP: 60"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file dummy_afu\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 88 of file dummy_afu\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dummy_afu::ddr_test_ctrl::ddr_test_ctrl (uint64_t v)\fC [inline]\fP"

.PP
Definition at line 92 of file dummy_afu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t dummy_afu::ddr_test_ctrl::value"

.PP
Definition at line 93 of file dummy_afu\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
