.TH "dummy_afu::afu_dfh" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_afu::afu_dfh
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/dummy_afu/dummy_afu\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = AFU_DFH }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBafu_dfh\fP (uint64_t v)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBFeatureID\fP: 12"
.br
.ti -1c
.RI "uint64_t \fBFeatureRev\fP: 4"
.br
.ti -1c
.RI "uint64_t \fBNextDfhByteOffset\fP: 24"
.br
.ti -1c
.RI "uint64_t \fBEOL\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBReserved41\fP: 19"
.br
.ti -1c
.RI "uint64_t \fBFeatureType\fP: 4"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file dummy_afu\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 58 of file dummy_afu\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dummy_afu::afu_dfh::afu_dfh (uint64_t v)\fC [inline]\fP"

.PP
Definition at line 62 of file dummy_afu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t dummy_afu::afu_dfh::value"

.PP
Definition at line 63 of file dummy_afu\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
