.TH "dummy_afu::ddr_test_bank0_stat" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummy_afu::ddr_test_bank0_stat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/dummy_afu/dummy_afu\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = DDR_TEST_BANK0_STAT }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBddr_test_bank0_stat\fP (uint64_t v)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBTrafficGenTestPass\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBTrafficGenTestFail\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBTrafficGenTestTimeout\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBTrafficGenFSMState\fP: 4"
.br
.ti -1c
.RI "uint64_t \fBReserved4\fP: 57"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 116 of file dummy_afu\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 117 of file dummy_afu\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dummy_afu::ddr_test_bank0_stat::ddr_test_bank0_stat (uint64_t v)\fC [inline]\fP"

.PP
Definition at line 121 of file dummy_afu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t dummy_afu::ddr_test_bank0_stat::value"

.PP
Definition at line 122 of file dummy_afu\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
