.TH "samples/dummy_afu/dummy_afu.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/dummy_afu/dummy_afu.h
.SH SYNOPSIS
.br
.PP
\fC#include <opae/cxx/core/events\&.h>\fP
.br
\fC#include <opae/cxx/core/shared_buffer\&.h>\fP
.br
\fC#include 'afu_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBdummy_afu::afu_dfh\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::mem_test_ctrl\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_ctrl\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_stat\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_bank0_stat\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_bank1_stat\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_bank2_stat\fP"
.br
.ti -1c
.RI "union \fBdummy_afu::ddr_test_bank3_stat\fP"
.br
.ti -1c
.RI "class \fBdummy_afu::dummy_afu\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::afu_dfh\&.__unnamed65__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::mem_test_ctrl\&.__unnamed68__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_ctrl\&.__unnamed71__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_stat\&.__unnamed74__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_bank0_stat\&.__unnamed77__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_bank1_stat\&.__unnamed80__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_bank2_stat\&.__unnamed83__\fP"
.br
.ti -1c
.RI "struct \fBdummy_afu::ddr_test_bank3_stat\&.__unnamed86__\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdummy_afu\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBdummy_afu::test_afu\fP = \fBopae::afu_test::afu\fP"
.br
.ti -1c
.RI "using \fBdummy_afu::test_command\fP = \fBopae::afu_test::command\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBdummy_afu::AFU_DFH\fP = 0x0000, \fBdummy_afu::AFU_ID_L\fP = 0x0008, \fBdummy_afu::AFU_ID_H\fP = 0x0010, \fBdummy_afu::NEXT_AFU\fP = 0x0018, \fBdummy_afu::AFU_DFH_RSVD\fP = 0x0020, \fBdummy_afu::SCRATCHPAD\fP = 0x0028, \fBdummy_afu::MMIO_TEST_SCRATCHPAD\fP = 0x1000, \fBdummy_afu::MEM_TEST_CTRL\fP = 0x2040, \fBdummy_afu::MEM_TEST_STAT\fP = 0x2048, \fBdummy_afu::MEM_TEST_SRC_ADDR\fP = 0x2050, \fBdummy_afu::MEM_TEST_DST_ADDR\fP = 0x2058, \fBdummy_afu::DDR_TEST_CTRL\fP = 0x3000, \fBdummy_afu::DDR_TEST_STAT\fP = 0x3008, \fBdummy_afu::DDR_TEST_BANK0_STAT\fP = 0x3010, \fBdummy_afu::DDR_TEST_BANK1_STAT\fP = 0x3018, \fBdummy_afu::DDR_TEST_BANK2_STAT\fP = 0x3020, \fBdummy_afu::DDR_TEST_BANK3_STAT\fP = 0x3028 }"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct dummy_afu::afu_dfh\&.__unnamed65__"
.PP 
Definition at line 64 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fIFeatureID: 12\fP 
.br
.PP
uint64_t \fIFeatureRev: 4\fP 
.br
.PP
uint64_t \fINextDfhByteOffset: 24\fP 
.br
.PP
uint64_t \fIEOL: 1\fP 
.br
.PP
uint64_t \fIReserved41: 19\fP 
.br
.PP
uint64_t \fIFeatureType: 4\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::mem_test_ctrl\&.__unnamed68__"
.PP 
Definition at line 81 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fIStartTest: 1\fP 
.br
.PP
uint64_t \fIReserved1: 63\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_ctrl\&.__unnamed71__"
.PP 
Definition at line 94 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fIDDRBank0StartTest: 1\fP 
.br
.PP
uint64_t \fIDDRBank1StartTest: 1\fP 
.br
.PP
uint64_t \fIDDRBank2StartTest: 1\fP 
.br
.PP
uint64_t \fIDDRBank3StartTest: 1\fP 
.br
.PP
uint64_t \fIReserved4: 60\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_stat\&.__unnamed74__"
.PP 
Definition at line 110 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fINumDDRBank: 8\fP 
.br
.PP
uint64_t \fIReserved8: 56\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_bank0_stat\&.__unnamed77__"
.PP 
Definition at line 123 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fITrafficGenTestPass: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestFail: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestTimeout: 1\fP 
.br
.PP
uint64_t \fITrafficGenFSMState: 4\fP 
.br
.PP
uint64_t \fIReserved4: 57\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_bank1_stat\&.__unnamed80__"
.PP 
Definition at line 139 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fITrafficGenTestPass: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestFail: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestTimeout: 1\fP 
.br
.PP
uint64_t \fITrafficGenFSMState: 4\fP 
.br
.PP
uint64_t \fIReserved4: 57\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_bank2_stat\&.__unnamed83__"
.PP 
Definition at line 155 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fITrafficGenTestPass: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestFail: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestTimeout: 1\fP 
.br
.PP
uint64_t \fITrafficGenFSMState: 4\fP 
.br
.PP
uint64_t \fIReserved4: 57\fP 
.br
.PP
.RE
.PP
.SH "struct dummy_afu::ddr_test_bank3_stat\&.__unnamed86__"
.PP 
Definition at line 171 of file dummy_afu\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
uint64_t \fITrafficGenTestPass: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestFail: 1\fP 
.br
.PP
uint64_t \fITrafficGenTestTimeout: 1\fP 
.br
.PP
uint64_t \fITrafficGenFSMState: 4\fP 
.br
.PP
uint64_t \fIReserved4: 57\fP 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
