.TH "include/opae/cxx/core/errors.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae/cxx/core/errors.h
.SH SYNOPSIS
.br
.PP
\fC#include <opae/cxx/core/token\&.h>\fP
.br
\fC#include <opae/types_enum\&.h>\fP
.br
\fC#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBopae::fpga::types::error\fP"
.br
.RI "An error object represents an error register for a resource\&. This is used to read out the raw value in the register\&. No parsing is done by this class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopae\fP"
.br
.ti -1c
.RI " \fBopae::fpga\fP"
.br
.ti -1c
.RI " \fBopae::fpga::types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
