.TH "include/opae/fpga.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae/fpga.h \- FPGA API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <opae/log\&.h>\fP
.br
\fC#include <opae/init\&.h>\fP
.br
\fC#include <opae/types\&.h>\fP
.br
\fC#include <opae/access\&.h>\fP
.br
\fC#include <opae/buffer\&.h>\fP
.br
\fC#include <opae/enum\&.h>\fP
.br
\fC#include <opae/event\&.h>\fP
.br
\fC#include <opae/manage\&.h>\fP
.br
\fC#include <opae/mmio\&.h>\fP
.br
\fC#include <opae/properties\&.h>\fP
.br
\fC#include <opae/umsg\&.h>\fP
.br
\fC#include <opae/utils\&.h>\fP
.br
\fC#include <opae/error\&.h>\fP
.br
\fC#include <opae/version\&.h>\fP
.br
\fC#include <opae/sysobject\&.h>\fP
.br
\fC#include <opae/userclk\&.h>\fP
.br
\fC#include <opae/metrics\&.h>\fP
.br

.SH "Detailed Description"
.PP 
FPGA API\&. 

This conveniently includes all APIs that a part of the OPAE release (base and extensions)\&. 
.PP
Definition in file \fBfpga\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
