.TH "host_exerciser::he_swtest_msg" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
host_exerciser::he_swtest_msg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/host_exerciser/host_exerciser\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = HE_SWTEST_MSG }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBswtest_msg\fP: 64"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 235 of file host_exerciser\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 236 of file host_exerciser\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t host_exerciser::he_swtest_msg::value"

.PP
Definition at line 239 of file host_exerciser\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
