.TH "samples/host_exerciser/host_exerciser_mem.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/host_exerciser/host_exerciser_mem.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afu_test\&.h'\fP
.br
\fC#include 'host_exerciser\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhost_exerciser::host_exerciser_mem\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhost_exerciser\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtest_afu\fP = \fBopae::afu_test::afu\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBMEM_AFU_ID\fP = '8568AB4E\-6bA5\-4616\-BB65\-2A578330A8EB'"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBtest_afu\fP =  \fBopae::afu_test::afu\fP"

.PP
Definition at line 33 of file host_exerciser_mem\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const char* MEM_AFU_ID = '8568AB4E\-6bA5\-4616\-BB65\-2A578330A8EB'"

.PP
Definition at line 30 of file host_exerciser_mem\&.h\&.
.PP
Referenced by host_exerciser::host_exerciser_mem::afu_id()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
