.TH "host_exerciser::host_exerciser_mem" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
host_exerciser::host_exerciser_mem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/host_exerciser/host_exerciser_mem\&.h>\fP
.PP
Inherits \fBhost_exerciser::host_exerciser_cmd\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhost_exerciser_mem\fP ()"
.br
.ti -1c
.RI "virtual \fB~host_exerciser_mem\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const override"
.br
.ti -1c
.RI "virtual const char * \fBdescription\fP () const override"
.br
.ti -1c
.RI "virtual const char * \fBafu_id\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 38 of file host_exerciser_mem\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "host_exerciser::host_exerciser_mem::host_exerciser_mem ()\fC [inline]\fP"

.PP
Definition at line 41 of file host_exerciser_mem\&.h\&.
.SS "virtual host_exerciser::host_exerciser_mem::~host_exerciser_mem ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 44 of file host_exerciser_mem\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* host_exerciser::host_exerciser_mem::name () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBopae::afu_test::command\fP\&.
.PP
Definition at line 45 of file host_exerciser_mem\&.h\&.
.SS "virtual const char* host_exerciser::host_exerciser_mem::description () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBopae::afu_test::command\fP\&.
.PP
Definition at line 50 of file host_exerciser_mem\&.h\&.
.SS "virtual const char* host_exerciser::host_exerciser_mem::afu_id () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBopae::afu_test::command\fP\&.
.PP
Definition at line 55 of file host_exerciser_mem\&.h\&.
.PP
References MEM_AFU_ID\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
