.TH "samples/hssi/hssi_10g_cmd.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hssi/hssi_10g_cmd.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'hssi_cmd\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhssi_10g_cmd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCSR_NUM_PACKETS\fP   0x3c00"
.br
.ti -1c
.RI "#define \fBCSR_RANDOM_LENGTH\fP   0x3c01"
.br
.ti -1c
.RI "#define \fBCSR_RANDOM_PAYLOAD\fP   0x3c02"
.br
.ti -1c
.RI "#define \fBCSR_START\fP   0x3c03"
.br
.ti -1c
.RI "#define \fBCSR_STOP\fP   0x3c04"
.br
.ti -1c
.RI "#define \fBCSR_SRC_ADDR0\fP   0x3c05"
.br
.ti -1c
.RI "#define \fBCSR_SRC_ADDR1\fP   0x3c06"
.br
.ti -1c
.RI "#define \fBCSR_DEST_ADDR0\fP   0x3c07"
.br
.ti -1c
.RI "#define \fBCSR_DEST_ADDR1\fP   0x3c08"
.br
.ti -1c
.RI "#define \fBCSR_PACKET_TX_COUNT\fP   0x3c09"
.br
.ti -1c
.RI "#define \fBCSR_RND_SEED0\fP   0x3c0a"
.br
.ti -1c
.RI "#define \fBCSR_RND_SEED1\fP   0x3c0b"
.br
.ti -1c
.RI "#define \fBCSR_RND_SEED2\fP   0x3c0c"
.br
.ti -1c
.RI "#define \fBCSR_PACKET_LENGTH\fP   0x3c0d"
.br
.ti -1c
.RI "#define \fBCSR_TX_STA_TSTAMP\fP   0x3cf4"
.br
.ti -1c
.RI "#define \fBCSR_TX_END_TSTAMP\fP   0x3cf5"
.br
.ti -1c
.RI "#define \fBCSR_NUM_PKT\fP   0x3d00"
.br
.ti -1c
.RI "#define \fBCSR_PKT_GOOD\fP   0x3d01"
.br
.ti -1c
.RI "#define \fBCSR_PKT_BAD\fP   0x3d02"
.br
.ti -1c
.RI "#define \fBCSR_AVST_RX_ERR\fP   0x3d07"
.br
.ti -1c
.RI "#define \fBCSR_RX_STA_TSTAMP\fP   0x3d0b"
.br
.ti -1c
.RI "#define \fBCSR_RX_END_TSTAMP\fP   0x3d0c"
.br
.ti -1c
.RI "#define \fBCSR_MAC_LOOP\fP   0x3e00"
.br
.ti -1c
.RI "#define \fBINVALID_PORT\fP   99"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CSR_NUM_PACKETS   0x3c00"

.PP
Definition at line 31 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RANDOM_LENGTH   0x3c01"

.PP
Definition at line 32 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RANDOM_PAYLOAD   0x3c02"

.PP
Definition at line 33 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_START   0x3c03"

.PP
Definition at line 34 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_STOP   0x3c04"

.PP
Definition at line 35 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_SRC_ADDR0   0x3c05"

.PP
Definition at line 36 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_SRC_ADDR1   0x3c06"

.PP
Definition at line 37 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_DEST_ADDR0   0x3c07"

.PP
Definition at line 38 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_DEST_ADDR1   0x3c08"

.PP
Definition at line 39 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_PACKET_TX_COUNT   0x3c09"

.PP
Definition at line 40 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RND_SEED0   0x3c0a"

.PP
Definition at line 41 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RND_SEED1   0x3c0b"

.PP
Definition at line 42 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RND_SEED2   0x3c0c"

.PP
Definition at line 43 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_PACKET_LENGTH   0x3c0d"

.PP
Definition at line 44 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_TX_STA_TSTAMP   0x3cf4"

.PP
Definition at line 45 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_TX_END_TSTAMP   0x3cf5"

.PP
Definition at line 46 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_NUM_PKT   0x3d00"

.PP
Definition at line 48 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_PKT_GOOD   0x3d01"

.PP
Definition at line 49 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_PKT_BAD   0x3d02"

.PP
Definition at line 50 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_AVST_RX_ERR   0x3d07"

.PP
Definition at line 51 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RX_STA_TSTAMP   0x3d0b"

.PP
Definition at line 52 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_RX_END_TSTAMP   0x3d0c"

.PP
Definition at line 53 of file hssi_10g_cmd\&.h\&.
.SS "#define CSR_MAC_LOOP   0x3e00"

.PP
Definition at line 55 of file hssi_10g_cmd\&.h\&.
.SS "#define INVALID_PORT   99"

.PP
Definition at line 57 of file hssi_10g_cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
