.TH "samples/hssi/hssi_cmd.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hssi/hssi_cmd.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <netinet/ether\&.h>\fP
.br
\fC#include 'afu_test\&.h'\fP
.br
\fC#include <opae/uio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhssi_cmd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPKT_FILT_CSR_DEST_ADDR\fP   0x0040"
.br
.ti -1c
.RI "#define \fBINVALID_MAC\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#define \fBINVALID_CLOCK_FREQ\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBUSER_CLKFREQ_S10\fP   156\&.25"
.br
.ti -1c
.RI "#define \fBUSER_CLKFREQ_N6000\fP   402\&.83203125"
.br
.ti -1c
.RI "#define \fBBITSVER_MAJOR_S10\fP   4"
.br
.ti -1c
.RI "#define \fBBITSVER_MAJOR_N6000\fP   5"
.br
.ti -1c
.RI "#define \fBFPGA_BBS_VER_MAJOR\fP(i)   (((i) >> 56) & 0xf)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtest_command\fP = \fBopae::afu_test::command\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PKT_FILT_CSR_DEST_ADDR   0x0040"

.PP
Definition at line 38 of file hssi_cmd\&.h\&.
.SS "#define INVALID_MAC   0xffffffffffffffffULL"

.PP
Definition at line 40 of file hssi_cmd\&.h\&.
.SS "#define INVALID_CLOCK_FREQ   0\&.0"

.PP
Definition at line 42 of file hssi_cmd\&.h\&.
.SS "#define USER_CLKFREQ_S10   156\&.25"

.PP
Definition at line 44 of file hssi_cmd\&.h\&.
.SS "#define USER_CLKFREQ_N6000   402\&.83203125"

.PP
Definition at line 45 of file hssi_cmd\&.h\&.
.SS "#define BITSVER_MAJOR_S10   4"

.PP
Definition at line 46 of file hssi_cmd\&.h\&.
.SS "#define BITSVER_MAJOR_N6000   5"

.PP
Definition at line 47 of file hssi_cmd\&.h\&.
.SS "#define FPGA_BBS_VER_MAJOR(i)   (((i) >> 56) & 0xf)"

.PP
Definition at line 49 of file hssi_cmd\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBtest_command\fP =  \fBopae::afu_test::command\fP"

.PP
Definition at line 35 of file hssi_cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
