.TH "hssi_pkt_filt_100g_cmd" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hssi_pkt_filt_100g_cmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/hssi/hssi_pkt_filt_100g_cmd\&.h>\fP
.PP
Inherits \fBhssi_100g_cmd\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhssi_pkt_filt_100g_cmd\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const override"
.br
.ti -1c
.RI "virtual const char * \fBdescription\fP () const override"
.br
.ti -1c
.RI "virtual void \fBadd_options\fP (CLI::App *\fBapp\fP) override"
.br
.ti -1c
.RI "virtual int \fBrun\fP (\fBtest_afu\fP *afu, CLI::App *\fBapp\fP) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdfl_dev_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 31 of file hssi_pkt_filt_100g_cmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hssi_pkt_filt_100g_cmd::hssi_pkt_filt_100g_cmd ()\fC [inline]\fP"

.PP
Definition at line 34 of file hssi_pkt_filt_100g_cmd\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* hssi_pkt_filt_100g_cmd::name () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBhssi_100g_cmd\fP\&.
.PP
Definition at line 38 of file hssi_pkt_filt_100g_cmd\&.h\&.
.SS "virtual const char* hssi_pkt_filt_100g_cmd::description () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBhssi_100g_cmd\fP\&.
.PP
Definition at line 43 of file hssi_pkt_filt_100g_cmd\&.h\&.
.SS "virtual void hssi_pkt_filt_100g_cmd::add_options (CLI::App * app)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBhssi_100g_cmd\fP\&.
.PP
Definition at line 48 of file hssi_pkt_filt_100g_cmd\&.h\&.
.PP
References hssi_100g_cmd::add_options(), app, and dfl_dev_\&.
.SS "virtual int hssi_pkt_filt_100g_cmd::run (\fBtest_afu\fP * afu, CLI::App * app)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBhssi_100g_cmd\fP\&.
.PP
Definition at line 57 of file hssi_pkt_filt_100g_cmd\&.h\&.
.PP
References app, hssi_100g_cmd::dest_addr_, dfl_dev_, opae::afu_test::afu::error, INVALID_MAC, hssi_cmd::mac_bits_for(), hssi_100g_cmd::run(), hssi_cmd::set_pkt_filt_dest(), and opae::afu_test::afu::success\&.
.SH "Field Documentation"
.PP 
.SS "std::string hssi_pkt_filt_100g_cmd::dfl_dev_\fC [protected]\fP"

.PP
Definition at line 84 of file hssi_pkt_filt_100g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
