.TH "samples/dummy_afu/lpbk.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/dummy_afu/lpbk.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afu_test\&.h'\fP
.br
\fC#include 'dummy_afu\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBdummy_afu::lpbk_test\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdummy_afu\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtest_afu\fP = \fBopae::afu_test::afu\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBtest_afu\fP =  \fBopae::afu_test::afu\fP"

.PP
Definition at line 30 of file lpbk\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
