.TH "n5010_test" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
n5010_test
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBfpga_result\fP(* \fBfunc\fP )(struct \fBn5010\fP *\fBn5010\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file n5010\-ctl\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const char * n5010_test::name"

.PP
Definition at line 72 of file n5010\-ctl\&.c\&.
.PP
Referenced by parse_mode()\&.
.SS "\fBfpga_result\fP(* n5010_test::func)(struct \fBn5010\fP *\fBn5010\fP)"

.PP
Definition at line 73 of file n5010\-ctl\&.c\&.
.PP
Referenced by main()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
