.TH "opae::fpga::types" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opae::fpga::types
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdetail\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBerror\fP"
.br
.RI "An error object represents an error register for a resource\&. This is used to read out the raw value in the register\&. No parsing is done by this class\&. "
.ti -1c
.RI "class \fBevent\fP"
.br
.RI "Wraps fpga event routines in OPAE C\&. "
.ti -1c
.RI "class \fBsrc_location\fP"
.br
.RI "Identify a particular line in a source file\&. "
.ti -1c
.RI "class \fBexcept\fP"
.br
.ti -1c
.RI "class \fBinvalid_param\fP"
.br
.ti -1c
.RI "class \fBbusy\fP"
.br
.ti -1c
.RI "class \fBexception\fP"
.br
.ti -1c
.RI "class \fBnot_found\fP"
.br
.ti -1c
.RI "class \fBno_memory\fP"
.br
.ti -1c
.RI "class \fBnot_supported\fP"
.br
.ti -1c
.RI "class \fBno_driver\fP"
.br
.ti -1c
.RI "class \fBno_daemon\fP"
.br
.ti -1c
.RI "class \fBno_access\fP"
.br
.ti -1c
.RI "class \fBreconf_error\fP"
.br
.ti -1c
.RI "class \fBhandle\fP"
.br
.ti -1c
.RI "class \fBproperties\fP"
.br
.ti -1c
.RI "struct \fBguid_t\fP"
.br
.ti -1c
.RI "struct \fBpvalue\fP"
.br
.RI "Wraps OPAE properties defined in the OPAE C API by associating an \fCfpga_properties\fP reference with the getters and setters defined for a property\&. "
.ti -1c
.RI "class \fBshared_buffer\fP"
.br
.ti -1c
.RI "class \fBsysobject\fP"
.br
.ti -1c
.RI "class \fBtoken\fP"
.br
.ti -1c
.RI "class \fBversion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
