.TH "opae::fpga::types::version" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opae::fpga::types::version
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opae/cxx/core/version\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfpga_version\fP \fBas_struct\fP ()"
.br
.RI "Get the package version information as a struct\&. "
.ti -1c
.RI "static std::string \fBas_string\fP ()"
.br
.RI "Get the package version information as a string\&. "
.ti -1c
.RI "static std::string \fBbuild\fP ()"
.br
.RI "Get the package build information as a string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file version\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBfpga_version\fP opae::fpga::types::version::as_struct ()\fC [static]\fP"

.PP
Get the package version information as a struct\&. 
.PP
\fBReturns\fP
.RS 4
The package version as an \fC\fBfpga_version\fP\fP struct 
.RE
.PP

.SS "static std::string opae::fpga::types::version::as_string ()\fC [static]\fP"

.PP
Get the package version information as a string\&. 
.PP
\fBReturns\fP
.RS 4
The package version as an \fCstd::string\fP object 
.RE
.PP

.SS "static std::string opae::fpga::types::version::build ()\fC [static]\fP"

.PP
Get the package build information as a string\&. 
.PP
\fBReturns\fP
.RS 4
The package build as an \fCstd::string\fP object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
