.TH "opae" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opae
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBafu_test\fP"
.br
.ti -1c
.RI " \fBfpga\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
