.TH "include/opae/cxx/core/pvalue.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae/cxx/core/pvalue.h
.SH SYNOPSIS
.br
.PP
\fC#include <opae/cxx/core/except\&.h>\fP
.br
\fC#include <opae/properties\&.h>\fP
.br
\fC#include <opae/utils\&.h>\fP
.br
\fC#include <uuid/uuid\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <array>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBopae::fpga::types::guid_t\fP"
.br
.ti -1c
.RI "struct \fBopae::fpga::types::pvalue< T >\fP"
.br
.RI "Wraps OPAE properties defined in the OPAE C API by associating an \fCfpga_properties\fP reference with the getters and setters defined for a property\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopae\fP"
.br
.ti -1c
.RI " \fBopae::fpga\fP"
.br
.ti -1c
.RI " \fBopae::fpga::types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
