.TH "include/opae/cxx/core/shared_buffer.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae/cxx/core/shared_buffer.h
.SH SYNOPSIS
.br
.PP
\fC#include <opae/buffer\&.h>\fP
.br
\fC#include <opae/cxx/core/except\&.h>\fP
.br
\fC#include <opae/cxx/core/handle\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBopae::fpga::types::shared_buffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopae\fP"
.br
.ti -1c
.RI " \fBopae::fpga\fP"
.br
.ti -1c
.RI " \fBopae::fpga::types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
