.TH "include/opae/umsg.h" 3 "Wed Nov 22 2023" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/opae/umsg.h \- FPGA UMsg API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <opae/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfpga_result\fP \fBfpgaGetNumUmsg\fP (\fBfpga_handle\fP handle, uint64_t *value)"
.br
.ti -1c
.RI "\fBfpga_result\fP \fBfpgaSetUmsgAttributes\fP (\fBfpga_handle\fP handle, uint64_t value)"
.br
.ti -1c
.RI "\fBfpga_result\fP \fBfpgaTriggerUmsg\fP (\fBfpga_handle\fP handle, uint64_t value)"
.br
.ti -1c
.RI "\fBfpga_result\fP \fBfpgaGetUmsgPtr\fP (\fBfpga_handle\fP handle, uint64_t **umsg_ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
FPGA UMsg API\&. 


.PP
Definition in file \fBumsg\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBfpga_result\fP fpgaGetNumUmsg (\fBfpga_handle\fP handle, uint64_t * value)"
Get number of Umsgs
.PP
Retuns number of umsg supported by AFU\&.
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP Handle to previously opened accelerator resource 
.br
\fIvalue\fP Returns number of UMsgs 
.RE
.PP
\fBReturns\fP
.RS 4
FPGA_OK on success\&. FPGA_INVALID_PARAM if input parameter combination is not valid\&. FPGA_EXCEPTION if input parameter fpga handle is not valid\&. 
.RE
.PP

.SS "\fBfpga_result\fP fpgaSetUmsgAttributes (\fBfpga_handle\fP handle, uint64_t value)"
Sets Umsg hint
.PP
Writes usmg hint bit\&.
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP Handle to previously opened accelerator resource 
.br
\fIvalue\fP Value to use for UMsg hint, Umsg hit is N wide bitvector where N = number of Umsgs\&. 
.RE
.PP
\fBReturns\fP
.RS 4
FPGA_OK on success\&. FPGA_INVALID_PARAM if input parameter combination is not valid\&. FPGA_EXCEPTION if input parameter fpga handle is not valid\&. 
.RE
.PP

.SS "\fBfpga_result\fP fpgaTriggerUmsg (\fBfpga_handle\fP handle, uint64_t value)"
Trigger Umsg
.PP
Writes a 64-bit value to trigger low-latency accelerator notification mechanism (UMsgs)\&.
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP Handle to previously opened accelerator resource 
.br
\fIvalue\fP Value to use for UMsg 
.RE
.PP
\fBReturns\fP
.RS 4
FPGA_OK on success\&. FPGA_INVALID_PARAM if input parameter combination is not valid\&. FPGA_EXCEPTION if input parameter fpga handle is not valid\&. 
.RE
.PP

.SS "\fBfpga_result\fP fpgaGetUmsgPtr (\fBfpga_handle\fP handle, uint64_t ** umsg_ptr)"
Access UMsg memory directly
.PP
This function will return a pointer to the memory allocated for low latency accelerator notifications (UMsgs)\&.
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP Handle to previously opened accelerator resource 
.br
\fIumsg_ptr\fP Pointer to memory where a pointer to the virtual address space will be returned 
.RE
.PP
\fBReturns\fP
.RS 4
FPGA_OK on success\&. FPGA_INVALID_PARAM if input parameter combination is not valid\&. FPGA_EXCEPTION if input parameter fpga handle is not valid\&. FPGA_NO_MEMORY if memory allocation fails or system doesn't configure huge pages\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
