OPAE C API: hssi_pkt_filt_100g_cmd Class Reference
hssi_pkt_filt_100g_cmd Class Reference
#include </root/samples/hssi/hssi_pkt_filt_100g_cmd.h>
Public Member Functions
hssi_pkt_filt_100g_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual void add_options (CLI::App *app) override
virtual int run (test_afu *afu, CLI::App *app) override
Public Member Functions inherited from hssi_100g_cmd
hssi_100g_cmd ()
uint64_t timestamp_in_seconds (uint64_t x) const
uint64_t total_per_second (uint64_t y, uint64_t z) const
uint64_t data_64 (uint32_t lowerbytes, uint32_t higherbytes) const
void read_performance (perf_data *perf, hssi_afu *hafu) const
void calc_performance (perf_data *old_perf, perf_data *new_perf, perf_data *perf, uint64_t size) const
uint8_t stall_enable (hssi_afu *hafu) const
uint8_t stall_disable (hssi_afu *hafu) const
void write_ctrl_config (hssi_afu *hafu, ctrl_config config_data) const
void write_csr_addr (hssi_afu *hafu, uint64_t bin_src_addr, uint64_t bin_dest_addr) const
std::ostream & print_monitor_headers (std::ostream &os, uint32_t max_timer) const
std::ostream & print_monitor_data (std::ostream &os, perf_data *data, int port, uint32_t timer) const
void select_port (int port, ctrl_config config_data, hssi_afu *hafu) const
void capture_perf (perf_data *old_perf_data, hssi_afu *hafu) const
std::ostream & run_monitor (std::ostream &os, perf_data *old_perf_data, int port, hssi_afu *hafu, uint32_t timer)
char get_user_input (char key) const
void quit_monitor (uint8_t size, std::string move, hssi_afu *hafu) const
void reset_monitor (std::vector< int > port_, std::string move, ctrl_config config_data, hssi_afu *hafu) const
void move_cursor (uint8_t size, std::string move) const
virtual const char * afu_id () const override
std::ostream & print_registers (std::ostream &os, hssi_afu *hafu) const
Public Member Functions inherited from hssi_cmd
hssi_cmd ()
double clock_freq_for (test_afu *afu) const
int set_pkt_filt_dest (const std::string &dfl_dev, uint64_t bin_dest_addr) const
uint64_t mac_bits_for (std::string addr) const
void run_process (const std::string &proc)
void show_eth_stats (const std::string &eth)
void enable_eth_loopback (const std::string &eth, bool enable)
template<typename X >
std::string int_to_hex (X x) const
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
std::string dfl_dev_
Protected Attributes inherited from hssi_100g_cmd
std::vector< int > port_
std::string eth_loopback_
uint32_t num_packets_
std::string gap_
std::string pattern_
std::string src_addr_
std::string dest_addr_
std::string eth_ifc_
uint32_t start_size_
uint32_t end_size_
std::string end_select_
std::string continuous_
uint32_t contmonitor_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 31 of file hssi_pkt_filt_100g_cmd.h.
Constructor & Destructor Documentation
hssi_pkt_filt_100g_cmd()
hssi_pkt_filt_100g_cmd::hssi_pkt_filt_100g_cmd () inline
Definition at line 34 of file hssi_pkt_filt_100g_cmd.h.
Member Function Documentation
name()
virtual const char* hssi_pkt_filt_100g_cmd::name () const inline override virtual
Reimplemented from hssi_100g_cmd.
Definition at line 38 of file hssi_pkt_filt_100g_cmd.h.
description()
virtual const char* hssi_pkt_filt_100g_cmd::description () const inline override virtual
Reimplemented from hssi_100g_cmd.
Definition at line 43 of file hssi_pkt_filt_100g_cmd.h.
add_options()
virtual void hssi_pkt_filt_100g_cmd::add_options (CLI::App * app) inline override virtual
Reimplemented from hssi_100g_cmd.
Definition at line 48 of file hssi_pkt_filt_100g_cmd.h.
References hssi_100g_cmd::add_options(), app, and dfl_dev_.
run()
virtual int hssi_pkt_filt_100g_cmd::run (test_afu * afu, CLI::App * app) inline override virtual
Reimplemented from hssi_100g_cmd.
Definition at line 57 of file hssi_pkt_filt_100g_cmd.h.
References app, hssi_100g_cmd::dest_addr_, dfl_dev_, opae::afu_test::afu::error, INVALID_MAC, hssi_cmd::mac_bits_for(), hssi_100g_cmd::run(), hssi_cmd::set_pkt_filt_dest(), and opae::afu_test::afu::success.
Field Documentation
dfl_dev_
std::string hssi_pkt_filt_100g_cmd::dfl_dev_ protected
Definition at line 84 of file hssi_pkt_filt_100g_cmd.h.
Referenced by add_options(), and run().