OPAE C API: mem_tg::tg_test Class Reference
mem_tg::tg_test Class Reference
#include </root/samples/mem_tg/tg_test.h>
Public Member Functions
tg_test ()
virtual ~tg_test ()
virtual const char * name () const override
virtual const char * description () const override
virtual const char * afu_id () const override
double bw_calc (uint64_t xfer_bytes, uint64_t num_ticks)
void tg_perf (mem_tg *tg_exe_)
bool tg_wait_test_completion (mem_tg *tg_exe_)
int config_input_options (mem_tg *tg_exe_)
int run_mem_test (mem_tg *tg_exe_)
int run_thread_single_channel (mem_tg *tg_exe_)
virtual int run (test_afu *afu, CLI::App *app) override
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual void add_options (CLI::App *app)
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
uint64_t tg_offset_
mem_tg * tg_exe_
token::ptr_t token_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 52 of file tg_test.h.
Constructor & Destructor Documentation
tg_test()
mem_tg::tg_test::tg_test () inline
Definition at line 55 of file tg_test.h.
~tg_test()
virtual mem_tg::tg_test::~tg_test () inline virtual
Definition at line 60 of file tg_test.h.
Member Function Documentation
name()
virtual const char* mem_tg::tg_test::name () const inline override virtual
Implements opae::afu_test::command.
Definition at line 62 of file tg_test.h.
description()
virtual const char* mem_tg::tg_test::description () const inline override virtual
Implements opae::afu_test::command.
Definition at line 67 of file tg_test.h.
afu_id()
virtual const char* mem_tg::tg_test::afu_id () const inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 72 of file tg_test.h.
References mem_tg::AFU_ID.
bw_calc()
double mem_tg::tg_test::bw_calc (uint64_t xfer_bytes, uint64_t num_ticks) inline
Definition at line 78 of file tg_test.h.
References mem_tg::mem_tg::mem_speed_, and tg_exe_.
Referenced by tg_perf().
tg_perf()
void mem_tg::tg_test::tg_perf (mem_tg * tg_exe_) inline
Definition at line 83 of file tg_test.h.
References mem_tg::mem_tg::bcnt_, bw_calc(), mem_tg::mem_tg::loop_, mem_tg::mem_tg::mem_ch_, mem_tg::MEM_TG_CLOCKS, mem_tg::mem_tg::rcnt_, opae::afu_test::afu::read64(), mem_tg::mem_tg::status_, tg_exe_, mem_tg::TG_FAIL_EXPECTED_DATA, mem_tg::TG_FAIL_READ_DATA, mem_tg::TG_FIRST_FAIL_ADDR_L, mem_tg::mem_tg::tg_offset_, mem_tg::tg_print_mutex, mem_tg::TG_STATUS_ERROR, mem_tg::TG_STATUS_TIMEOUT, and mem_tg::mem_tg::wcnt_.
Referenced by run_mem_test().
tg_wait_test_completion()
bool mem_tg::tg_test::tg_wait_test_completion (mem_tg * tg_exe_) inline
Definition at line 124 of file tg_test.h.
References mem_tg::mem_tg::bcnt_, mem_tg::mem_tg::loop_, mem_tg::mem_tg::mem_ch_, mem_tg::MEM_TG_STAT, mem_tg::MEM_TG_TEST_TIMEOUT, opae::afu_test::afu::read64(), mem_tg::mem_tg::status_, tg_exe_, mem_tg::TG_STATUS_ACTIVE, mem_tg::TG_STATUS_ERROR, and mem_tg::TG_STATUS_TIMEOUT.
Referenced by run_mem_test().
config_input_options()
int mem_tg::tg_test::config_input_options (mem_tg * tg_exe_) inline
Definition at line 155 of file tg_test.h.
References mem_tg::AFU_DFH, mem_tg::mem_tg::bcnt_, mem_tg::mem_tg::loop_, mem_tg::mem_tg::mem_ch_, mem_tg::MEM_TG_CFG_OFFSET, mem_tg::MEM_TG_CTRL, mem_tg::mem_tg::pattern_, mem_tg::mem_tg::rcnt_, opae::afu_test::afu::read64(), mem_tg::mem_tg::stride_, mem_tg::TG_ADDR_MODE_RD, mem_tg::TG_ADDR_MODE_WR, mem_tg::TG_ADDR_SEQ, mem_tg::TG_BURST_LENGTH, tg_exe_, mem_tg::TG_LOOP_COUNT, mem_tg::mem_tg::tg_offset_, mem_tg::TG_PPPG_SEL, mem_tg::TG_READ_COUNT, mem_tg::TG_SEQ_ADDR_INCR, mem_tg::TG_WRITE_COUNT, mem_tg::mem_tg::wcnt_, and opae::afu_test::afu::write32().
Referenced by run_thread_single_channel().
run_mem_test()
int mem_tg::tg_test::run_mem_test (mem_tg * tg_exe_) inline
Definition at line 181 of file tg_test.h.
References opae::afu_test::afu::logger_, mem_tg::tg_cv, tg_exe_, mem_tg::tg_num_threads, mem_tg::mem_tg::tg_offset_, tg_perf(), mem_tg::TG_START, mem_tg::tg_start_write_mutex, tg_wait_test_completion(), mem_tg::tg_waiting_threads_counter, and opae::afu_test::afu::write32().
Referenced by run_thread_single_channel().
run_thread_single_channel()
int mem_tg::tg_test::run_thread_single_channel (mem_tg * tg_exe_) inline
Definition at line 209 of file tg_test.h.
References config_input_options(), run_mem_test(), and tg_exe_.
Referenced by run().
run()
virtual int mem_tg::tg_test::run (test_afu * afu, CLI::App * app) inline override virtual
Implements opae::afu_test::command.
Definition at line 218 of file tg_test.h.
References app, mem_tg::mem_tg::duplicate(), mem_tg::mem_tg::mem_ch_, mem_tg::mem_tg::mem_speed_, mem_tg::MEM_TG_CTRL, opae::afu_test::afu::read64(), run_thread_single_channel(), tg_exe_, mem_tg::tg_num_threads, mem_tg::tg_waiting_threads_counter, and token_.
Field Documentation
tg_offset_
uint64_t mem_tg::tg_test::tg_offset_ protected
Definition at line 312 of file tg_test.h.
tg_exe_
mem_tg* mem_tg::tg_test::tg_exe_ protected
Definition at line 313 of file tg_test.h.
Referenced by bw_calc(), config_input_options(), run(), run_mem_test(), run_thread_single_channel(), tg_perf(), and tg_wait_test_completion().
token_
token::ptr_t mem_tg::tg_test::token_ protected
Definition at line 314 of file tg_test.h.
Referenced by run().