OPAE C API: hssi_pkt_filt_10g_cmd Class Reference
hssi_pkt_filt_10g_cmd Class Reference
#include </root/samples/hssi/hssi_pkt_filt_10g_cmd.h>
Public Member Functions
hssi_pkt_filt_10g_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual void add_options (CLI::App *app) override
virtual int run (test_afu *afu, CLI::App *app) override
Public Member Functions inherited from hssi_10g_cmd
hssi_10g_cmd ()
virtual const char * afu_id () const override
std::ostream & print_registers (std::ostream &os, hssi_afu *hafu) const
Public Member Functions inherited from hssi_cmd
hssi_cmd ()
double clock_freq_for (test_afu *afu) const
int set_pkt_filt_dest (const std::string &dfl_dev, uint64_t bin_dest_addr) const
uint64_t mac_bits_for (std::string addr) const
void run_process (const std::string &proc)
void show_eth_stats (const std::string &eth)
void enable_eth_loopback (const std::string &eth, bool enable)
template<typename X >
std::string int_to_hex (X x) const
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
std::string dfl_dev_
Protected Attributes inherited from hssi_10g_cmd
uint32_t port_
uint32_t dst_port_
uint32_t src_port_
std::string eth_loopback_
std::string he_loopback_
uint32_t num_packets_
std::string random_length_
std::string random_payload_
uint32_t packet_length_
std::string src_addr_
std::string dest_addr_
std::string eth_ifc_
uint32_t rnd_seed0_
uint32_t rnd_seed1_
uint32_t rnd_seed2_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 31 of file hssi_pkt_filt_10g_cmd.h.
Constructor & Destructor Documentation
hssi_pkt_filt_10g_cmd()
hssi_pkt_filt_10g_cmd::hssi_pkt_filt_10g_cmd () inline
Definition at line 34 of file hssi_pkt_filt_10g_cmd.h.
Member Function Documentation
name()
virtual const char* hssi_pkt_filt_10g_cmd::name () const inline override virtual
Reimplemented from hssi_10g_cmd.
Definition at line 38 of file hssi_pkt_filt_10g_cmd.h.
description()
virtual const char* hssi_pkt_filt_10g_cmd::description () const inline override virtual
Reimplemented from hssi_10g_cmd.
Definition at line 43 of file hssi_pkt_filt_10g_cmd.h.
add_options()
virtual void hssi_pkt_filt_10g_cmd::add_options (CLI::App * app) inline override virtual
Reimplemented from hssi_10g_cmd.
Definition at line 48 of file hssi_pkt_filt_10g_cmd.h.
References hssi_10g_cmd::add_options(), app, and dfl_dev_.
run()
virtual int hssi_pkt_filt_10g_cmd::run (test_afu * afu, CLI::App * app) inline override virtual
Reimplemented from hssi_10g_cmd.
Definition at line 57 of file hssi_pkt_filt_10g_cmd.h.
References app, hssi_10g_cmd::dest_addr_, dfl_dev_, opae::afu_test::afu::error, INVALID_MAC, hssi_cmd::mac_bits_for(), hssi_10g_cmd::run(), hssi_cmd::set_pkt_filt_dest(), and opae::afu_test::afu::success.
Field Documentation
dfl_dev_
std::string hssi_pkt_filt_10g_cmd::dfl_dev_ protected
Definition at line 84 of file hssi_pkt_filt_10g_cmd.h.
Referenced by add_options(), and run().