OPAE C API: dummy_afu::dummy_afu Class Reference
dummy_afu::dummy_afu Class Reference
#include </root/samples/dummy_afu/dummy_afu.h>
Public Member Functions
dummy_afu (const char *afu_id="91c2a3a1-4a23-4e21-a7cd-2b36dbf2ed73")
virtual int run (CLI::App *app, test_command::ptr_t test) override
template<typename T >
T read (uint32_t offset) const
template<typename T >
void write (uint32_t offset, T value) const
template<typename T >
T read (uint32_t offset, uint32_t i) const
template<typename T >
void write (uint32_t offset, uint32_t i, T value) const
shared_buffer::ptr_t allocate (size_t size)
void fill (shared_buffer::ptr_t buffer)
void fill (shared_buffer::ptr_t buffer, uint32_t value)
event::ptr_t register_interrupt ()
void interrupt_wait (event::ptr_t event, int timeout=-1)
void compare (shared_buffer::ptr_t b1, shared_buffer::ptr_t b2, uint32_t count=0)
template<class T >
T read_register ()
template<class T >
volatile T * register_ptr (uint32_t offset)
template<class T >
void write_register (uint32_t offset, T *reg)
Public Member Functions inherited from opae::afu_test::afu
afu (const char *name, const char *afu_id=nullptr, const char *log_level=nullptr)
virtual ~afu ()
CLI::App & cli ()
int find_dev_feature ()
void unmap_mmio ()
bool map_mmio ()
int open_handle (const char *dev)
int main (int argc, char *argv[])
template<class T >
CLI::App * register_command ()
uint64_t read64 (uint32_t offset)
void write64 (uint32_t offset, uint64_t value)
uint32_t read32 (uint32_t offset)
void write32 (uint32_t offset, uint32_t value)
command::ptr_t current_command () const
bool allocate_dsm (size_t len=((4) *1024), uint32_t numa_node=0)
bool free_dsm ()
void reset_dsm ()
bool allocate_cache_read (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read ()
bool allocate_cache_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_write ()
bool allocate_cache_read_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read_write ()
uint8_t * get_dsm () const
uint8_t * get_read () const
uint8_t * get_write () const
uint8_t * get_read_write () const
Private Member Functions
uint32_t get_offset (uint32_t base, uint32_t i) const
Private Attributes
uint32_t count_
std::map< uint32_t, uint32_t > limits_
Additional Inherited Members
Public Types inherited from opae::afu_test::afu
enum exit_codes {
success = 0 , not_run , not_found , no_access ,
exception , error
}
typedef int(* command_fn) (afu *afu, CLI::App *app)
Data Fields inherited from opae::afu_test::afu
std::shared_ptr< spdlog::logger > logger_
Protected Attributes inherited from opae::afu_test::afu
std::string name_
std::string afu_id_
CLI::App app_
std::string pci_addr_
std::string log_level_
uint32_t timeout_msec_
int fd_
uint8_t * mmio_base_
uint64_t mmio_len_
uint8_t * dsm_buffer_
uint64_t dsm_buf_len_
uint8_t * rd_buffer_
uint64_t rd_buf_len_
uint8_t * wr_buffer_
uint64_t wr_buf_len_
uint8_t * rd_wr_buffer_
uint64_t rd_wr_buf_len_
struct dfl_cxl_cache_region_info rinfo_
std::string dev_path_ [2]
command::ptr_t current_command_
std::map< CLI::App *, command::ptr_t > commands_
Detailed Description
Definition at line 183 of file dummy_afu.h.
Constructor & Destructor Documentation
dummy_afu()
dummy_afu::dummy_afu::dummy_afu (const char * afu_id = "91c2a3a1-4a23-4e21-a7cd-2b36dbf2ed73") inline
Definition at line 185 of file dummy_afu.h.
Member Function Documentation
run()
virtual int dummy_afu::dummy_afu::run (CLI::App * app, test_command::ptr_t test) inline override virtual
Reimplemented from opae::afu_test::afu.
Definition at line 192 of file dummy_afu.h.
References app, and opae::afu_test::afu::run().
read() [1/2]
template<typename T > T dummy_afu::dummy_afu::read (uint32_t offset) const inline
Definition at line 220 of file dummy_afu.h.
write() [1/2]
template<typename T > void dummy_afu::dummy_afu::write (uint32_t offset, T value) const inline
Definition at line 225 of file dummy_afu.h.
read() [2/2]
template<typename T > T dummy_afu::dummy_afu::read (uint32_t offset, uint32_t i) const inline
Definition at line 230 of file dummy_afu.h.
write() [2/2]
template<typename T > void dummy_afu::dummy_afu::write (uint32_t offset, uint32_t i, T value) const inline
Definition at line 235 of file dummy_afu.h.
allocate()
shared_buffer::ptr_t dummy_afu::dummy_afu::allocate (size_t size) inline
Definition at line 239 of file dummy_afu.h.
References opae::fpga::types::shared_buffer::allocate().
fill() [1/2]
void dummy_afu::dummy_afu::fill (shared_buffer::ptr_t buffer) inline
Definition at line 244 of file dummy_afu.h.
fill() [2/2]
void dummy_afu::dummy_afu::fill (shared_buffer::ptr_t buffer, uint32_t value) inline
Definition at line 256 of file dummy_afu.h.
register_interrupt()
event::ptr_t dummy_afu::dummy_afu::register_interrupt () inline
Definition at line 261 of file dummy_afu.h.
References FPGA_EVENT_INTERRUPT, and opae::fpga::types::event::register_event().
interrupt_wait()
void dummy_afu::dummy_afu::interrupt_wait (event::ptr_t event, int timeout = -1) inline
Definition at line 267 of file dummy_afu.h.
compare()
void dummy_afu::dummy_afu::compare (shared_buffer::ptr_t b1, shared_buffer::ptr_t b2, uint32_t count = 0) inline
Definition at line 280 of file dummy_afu.h.
read_register()
template<class T > T dummy_afu::dummy_afu::read_register () inline
Definition at line 290 of file dummy_afu.h.
register_ptr()
template<class T > volatile T* dummy_afu::dummy_afu::register_ptr (uint32_t offset) inline
Definition at line 296 of file dummy_afu.h.
write_register()
template<class T > void dummy_afu::dummy_afu::write_register (uint32_t offset, T * reg) inline
Definition at line 302 of file dummy_afu.h.
get_offset()
uint32_t dummy_afu::dummy_afu::get_offset (uint32_t base, uint32_t i) const inline private
Definition at line 311 of file dummy_afu.h.
Field Documentation
count_
uint32_t dummy_afu::dummy_afu::count_ private
Definition at line 308 of file dummy_afu.h.
limits_
std::map<uint32_t, uint32_t> dummy_afu::dummy_afu::limits_ private
Definition at line 309 of file dummy_afu.h.