OPAE C API: host_exerciser::he_cmd Class Reference
host_exerciser::he_cmd Class Reference
#include </root/samples/cxl_host_exerciser/cxl_he_cmd.h>
Public Member Functions
he_cmd ()
virtual ~he_cmd ()
double he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks)
void he_perf_counters (he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
void print_csr ()
void host_exerciser_errors ()
int parse_input_options ()
bool he_wait_test_completion ()
bool he_set_bias_mode ()
void he_start_test (const char *str="Test started ......")
bool verify_numa_node ()
bool he_get_perf (double *perf_data, double *latency, he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
uint64_t get_ticks ()
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual int run (afu *afu, CLI::App *app)=0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
host_exerciser * host_exe_
uint32_t he_clock_mhz_
uint32_t numa_node_
uint32_t he_target_
uint32_t he_bias_
he_ctl he_ctl_
he_info he_info_
he_rd_config he_rd_cfg_
he_wr_config he_wr_cfg_
he_rd_addr_table_ctrl rd_table_ctl_
he_wr_addr_table_ctrl wr_table_ctl_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 40 of file cxl_he_cmd.h.
Constructor & Destructor Documentation
he_cmd()
host_exerciser::he_cmd::he_cmd () inline
Definition at line 42 of file cxl_he_cmd.h.
References he_ctl_, he_info_, he_rd_cfg_, he_wr_cfg_, rd_table_ctl_, host_exerciser::he_ctl::value, host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and wr_table_ctl_.
~he_cmd()
virtual host_exerciser::he_cmd::~he_cmd () inline virtual
Definition at line 53 of file cxl_he_cmd.h.
Member Function Documentation
he_num_xfers_to_bw()
double host_exerciser::he_cmd::he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks) inline
Definition at line 56 of file cxl_he_cmd.h.
References he_clock_mhz_.
Referenced by he_get_perf(), and he_perf_counters().
he_perf_counters()
void host_exerciser::he_cmd::he_perf_counters (he_cxl_latency cxl_latency = HE_CXL_LATENCY_NONE) inline
Definition at line 60 of file cxl_he_cmd.h.
References host_exerciser::he_cache_dsm_status::actual_data, host_exerciser::he_cache_dsm_status::dsm_number, host_exerciser::he_cache_dsm_status::err_vector, host_exerciser::he_cache_dsm_status::expected_data, opae::afu_test::afu::get_dsm(), host_exerciser::HE_CXL_RD_LATENCY, he_num_xfers_to_bw(), host_exe_, opae::afu_test::afu::logger_, host_exerciser::he_cache_dsm_status::num_reads, host_exerciser::he_cache_dsm_status::num_ticks, host_exerciser::he_cache_dsm_status::num_writes, host_exerciser::he_cache_dsm_status::penalty_end, host_exerciser::he_cache_dsm_status::penalty_start, and host_exerciser::he_cache_dsm_status::test_completed.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
print_csr()
void host_exerciser::he_cmd::print_csr () inline
Definition at line 102 of file cxl_he_cmd.h.
References host_exerciser::HE_CTL, host_exerciser::HE_DFH, host_exerciser::HE_DSM_BASE, host_exerciser::HE_ERROR_ACT_DATA0, host_exerciser::HE_ERROR_ACT_DATA1, host_exerciser::HE_ERROR_ACT_DATA2, host_exerciser::HE_ERROR_ACT_DATA3, host_exerciser::HE_ERROR_ACT_DATA4, host_exerciser::HE_ERROR_ACT_DATA5, host_exerciser::HE_ERROR_ACT_DATA6, host_exerciser::HE_ERROR_ACT_DATA7, host_exerciser::HE_ERROR_EXP_DATA, host_exerciser::HE_ERROR_STATUS, host_exerciser::HE_ID_H, host_exerciser::HE_ID_L, host_exerciser::HE_INFO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::HE_RD_ADDR_TABLE_DATA, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::HE_SCRATCHPAD0, host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::HE_WR_ADDR_TABLE_DATA, host_exerciser::HE_WR_BYTE_ENABLE, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exe_, opae::afu_test::afu::logger_, and opae::afu_test::afu::read64().
Referenced by host_exerciser::he_cache_cmd::run().
host_exerciser_errors()
void host_exerciser::he_cmd::host_exerciser_errors () inline
Definition at line 176 of file cxl_he_cmd.h.
References host_exerciser::HE_ERROR_ACT_DATA0, host_exerciser::HE_ERROR_ACT_DATA1, host_exerciser::HE_ERROR_ACT_DATA2, host_exerciser::HE_ERROR_ACT_DATA3, host_exerciser::HE_ERROR_ACT_DATA4, host_exerciser::HE_ERROR_ACT_DATA5, host_exerciser::HE_ERROR_ACT_DATA6, host_exerciser::HE_ERROR_ACT_DATA7, host_exerciser::HE_ERROR_EXP_DATA, host_exerciser::HE_ERROR_STATUS, host_exe_, opae::afu_test::afu::read64(), and host_exerciser::he_err_status::value.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
parse_input_options()
int host_exerciser::he_cmd::parse_input_options () inline
Definition at line 220 of file cxl_he_cmd.h.
References host_exe_.
he_wait_test_completion()
bool host_exerciser::he_cmd::he_wait_test_completion () inline
Definition at line 228 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exerciser::HELPBK_TEST_SLEEP_INVL, host_exerciser::HELPBK_TEST_TIMEOUT, host_exe_, and usleep().
Referenced by host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
he_set_bias_mode()
bool host_exerciser::he_cmd::he_set_bias_mode () inline
Definition at line 243 of file cxl_he_cmd.h.
References host_exerciser::FPGAMEM_DEVICE_BIAS, host_exerciser::FPGAMEM_HOST_BIAS, he_bias_, he_ctl_, he_target_, host_exerciser::HE_TARGET_HOST, and host_exerciser::HOSTMEM_BIAS.
Referenced by host_exerciser::he_cache_cmd::run().
he_start_test()
void host_exerciser::he_cmd::he_start_test (const char * str = "Test started ......") inline
Definition at line 268 of file cxl_he_cmd.h.
References host_exerciser::HE_CTL, he_ctl_, host_exe_, host_exerciser::he_ctl::value, and opae::afu_test::afu::write64().
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
verify_numa_node()
bool host_exerciser::he_cmd::verify_numa_node () inline
Definition at line 278 of file cxl_he_cmd.h.
References he_target_, host_exerciser::HE_TARGET_HOST, and numa_node_.
Referenced by host_exerciser::he_cache_cmd::run(), and host_exerciser::he_cache_lpbk_cmd::run().
he_get_perf()
bool host_exerciser::he_cmd::he_get_perf (double * perf_data, double * latency, he_cxl_latency cxl_latency = HE_CXL_LATENCY_NONE) inline
Definition at line 304 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exerciser::HE_CXL_RD_LATENCY, he_num_xfers_to_bw(), host_exe_, host_exerciser::he_cache_dsm_status::num_reads, host_exerciser::he_cache_dsm_status::num_ticks, and host_exerciser::he_cache_dsm_status::num_writes.
get_ticks()
uint64_t host_exerciser::he_cmd::get_ticks () inline
Definition at line 329 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exe_, and host_exerciser::he_cache_dsm_status::num_ticks.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test().
Field Documentation
host_exe_
host_exerciser* host_exerciser::he_cmd::host_exe_ protected
Definition at line 343 of file cxl_he_cmd.h.
Referenced by get_ticks(), host_exerciser::he_cache_cmd::he_continuousmode(), host_exerciser::he_cache_cmd::he_forcetestcmpl(), he_get_perf(), he_perf_counters(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test(), he_start_test(), he_wait_test_completion(), host_exerciser_errors(), parse_input_options(), print_csr(), host_exerciser::he_cache_cmd::run(), and host_exerciser::he_cache_lpbk_cmd::run().
he_clock_mhz_
uint32_t host_exerciser::he_cmd::he_clock_mhz_ protected
Definition at line 344 of file cxl_he_cmd.h.
Referenced by he_num_xfers_to_bw().
numa_node_
uint32_t host_exerciser::he_cmd::numa_node_ protected
Definition at line 345 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test(), host_exerciser::he_cache_cmd::run(), host_exerciser::he_cache_lpbk_cmd::run(), and verify_numa_node().
he_target_
uint32_t host_exerciser::he_cmd::he_target_ protected
Definition at line 346 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::add_options(), host_exerciser::he_cache_lpbk_cmd::add_options(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), he_set_bias_mode(), and verify_numa_node().
he_bias_
uint32_t host_exerciser::he_cmd::he_bias_ protected
Definition at line 347 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::add_options(), and he_set_bias_mode().
he_ctl_
he_ctl host_exerciser::he_cmd::he_ctl_ protected
Definition at line 349 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_forcetestcmpl(), he_set_bias_mode(), he_start_test(), host_exerciser::he_cache_cmd::run(), and host_exerciser::he_cache_lpbk_cmd::run().
he_info_
he_info host_exerciser::he_cmd::he_info_ protected
Definition at line 350 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
he_rd_cfg_
he_rd_config host_exerciser::he_cmd::he_rd_cfg_ protected
Definition at line 351 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
he_wr_cfg_
he_wr_config host_exerciser::he_cmd::he_wr_cfg_ protected
Definition at line 352 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
rd_table_ctl_
he_rd_addr_table_ctrl host_exerciser::he_cmd::rd_table_ctl_ protected
Definition at line 353 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
wr_table_ctl_
he_wr_addr_table_ctrl host_exerciser::he_cmd::wr_table_ctl_ protected
Definition at line 354 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().