OPAE C API: dummy_afu::ddr_test Class Reference
dummy_afu::ddr_test Class Reference
#include </root/samples/dummy_afu/ddr.h>
Public Member Functions
ddr_test ()
virtual ~ddr_test ()
virtual const char * name () const
virtual const char * description () const
virtual int run (test_afu *afu, CLI::App *app)
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 45 of file ddr.h.
Constructor & Destructor Documentation
ddr_test()
dummy_afu::ddr_test::ddr_test () inline
Definition at line 48 of file ddr.h.
~ddr_test()
virtual dummy_afu::ddr_test::~ddr_test () inline virtual
Definition at line 49 of file ddr.h.
Member Function Documentation
name()
virtual const char* dummy_afu::ddr_test::name () const inline virtual
Implements opae::afu_test::command.
Definition at line 50 of file ddr.h.
Referenced by run().
description()
virtual const char* dummy_afu::ddr_test::description () const inline virtual
Implements opae::afu_test::command.
Definition at line 55 of file ddr.h.
run()
virtual int dummy_afu::ddr_test::run (test_afu * afu, CLI::App * app) inline virtual
Implements opae::afu_test::command.
Definition at line 60 of file ddr.h.
References app, dummy_afu::check_stat(), dummy_afu::DDR_TEST_CTRL, name(), dummy_afu::ddr_test_bank0_stat::offset, dummy_afu::ddr_test_bank1_stat::offset, dummy_afu::ddr_test_bank2_stat::offset, and dummy_afu::ddr_test_bank3_stat::offset.