OPAE C API: opae::fpga::types::properties Class Reference
opae::fpga::types::properties Class Reference
#include <opae/cxx/core/properties.h>
Public Types
typedef std::shared_ptr< properties > ptr_t
Public Member Functions
properties (const properties &p)=delete
properties & operator= (const properties &p)=delete
~properties ()
fpga_properties c_type () const
operator fpga_properties () const
Static Public Member Functions
static properties::ptr_t get ()
static properties::ptr_t get (fpga_guid guid_in)
static properties::ptr_t get (fpga_objtype objtype)
static properties::ptr_t get (std::shared_ptr< token > t)
static properties::ptr_t get (fpga_token t)
static properties::ptr_t get (std::shared_ptr< handle > h)
Data Fields
pvalue< fpga_objtype > type
pvalue< uint32_t > num_errors
pvalue< uint16_t > segment
pvalue< uint8_t > bus
pvalue< uint8_t > device
pvalue< uint8_t > function
pvalue< uint8_t > socket_id
pvalue< uint32_t > num_slots
pvalue< uint64_t > bbs_id
pvalue< fpga_version > bbs_version
pvalue< uint16_t > vendor_id
pvalue< uint16_t > device_id
pvalue< uint16_t > subsystem_vendor_id
pvalue< uint16_t > subsystem_device_id
pvalue< char * > model
pvalue< uint64_t > local_memory_size
pvalue< uint64_t > capabilities
pvalue< uint32_t > num_mmio
pvalue< uint32_t > num_interrupts
pvalue< fpga_accelerator_state > accelerator_state
pvalue< uint64_t > object_id
pvalue< fpga_token > parent
pvalue< fpga_interface > interface
guid_t guid
Static Public Attributes
static const std::vector< properties::ptr_t > none
Private Member Functions
properties (bool alloc_props=true)
Private Attributes
fpga_properties props_
Detailed Description
Wraps an OPAE fpga_properties object.
properties are information describing an accelerator resource that is identified by its token. The properties are used during enumeration to narrow the search for an accelerator resource, and after enumeration to provide the configuration of that resource.
Definition at line 51 of file properties.h.
Member Typedef Documentation
ptr_t
typedef std::shared_ptr<properties> opae::fpga::types::properties::ptr_t
Definition at line 53 of file properties.h.
Constructor & Destructor Documentation
properties() [1/2]
opae::fpga::types::properties::properties (const properties & p) delete
~properties()
opae::fpga::types::properties::~properties ()
properties() [2/2]
opae::fpga::types::properties::properties (bool alloc_props = true) private
Member Function Documentation
operator=()
properties& opae::fpga::types::properties::operator= (const properties & p) delete
c_type()
fpga_properties opae::fpga::types::properties::c_type () const inline
Get the underlying fpga_properties object.
Definition at line 69 of file properties.h.
References props_.
operator fpga_properties()
opae::fpga::types::properties::operator fpga_properties () const inline
Get the underlying fpga_properties object.
Definition at line 73 of file properties.h.
References props_.
get() [1/6]
static properties::ptr_t opae::fpga::types::properties::get () static
Create a new properties object.
Returns
A properties smart pointer.
Referenced by hssi_cmd::clock_freq_for(), hssi_afu::ethernet_interface(), and host_exerciser::host_exerciser_cmd::parse_input_options().
get() [2/6]
static properties::ptr_t opae::fpga::types::properties::get (fpga_guid guid_in) static
Create a new properties object from a guid.
Parameters
guid_in A guid to set in the properties
Returns
A properties smart pointer with its guid initialized to guid_in
get() [3/6]
static properties::ptr_t opae::fpga::types::properties::get (fpga_objtype objtype) static
Create a new properties object from an fpga_objtype.
Parameters
objtype An object type to set in the properties
Returns
A properties smart pointer with its object type set to objtype.
get() [4/6]
static properties::ptr_t opae::fpga::types::properties::get (std::shared_ptr< token > t) static
Retrieve the properties for a given token object.
Parameters
[in] t A token identifying the accelerator resource.
Returns
A properties smart pointer for the given token.
get() [5/6]
static properties::ptr_t opae::fpga::types::properties::get (fpga_token t) static
Retrieve the properties for a given fpga_token.
Parameters
[in] t An fpga_token identifying the accelerator resource.
Returns
A properties smart pointer for the given fpga_token.
get() [6/6]
static properties::ptr_t opae::fpga::types::properties::get (std::shared_ptr< handle > h) static
Retrieve the properties for a given handle object.
Parameters
[in] h A handle identifying the accelerator resource.
Returns
A properties smart pointer for the given handle.
Field Documentation
none
const std::vector<properties::ptr_t> opae::fpga::types::properties::none static
An empty vector of properties. Useful for enumerating based on a "match all" criteria.
Definition at line 59 of file properties.h.
props_
fpga_properties opae::fpga::types::properties::props_ private
Definition at line 112 of file properties.h.
Referenced by c_type(), and operator fpga_properties().
type
pvalue<fpga_objtype> opae::fpga::types::properties::type
Definition at line 115 of file properties.h.
num_errors
pvalue<uint32_t> opae::fpga::types::properties::num_errors
Definition at line 116 of file properties.h.
segment
pvalue<uint16_t> opae::fpga::types::properties::segment
Definition at line 117 of file properties.h.
bus
pvalue<uint8_t> opae::fpga::types::properties::bus
Definition at line 118 of file properties.h.
device
pvalue<uint8_t> opae::fpga::types::properties::device
Definition at line 119 of file properties.h.
function
pvalue<uint8_t> opae::fpga::types::properties::function
Definition at line 120 of file properties.h.
socket_id
pvalue<uint8_t> opae::fpga::types::properties::socket_id
Definition at line 121 of file properties.h.
num_slots
pvalue<uint32_t> opae::fpga::types::properties::num_slots
Definition at line 122 of file properties.h.
bbs_id
pvalue<uint64_t> opae::fpga::types::properties::bbs_id
Definition at line 123 of file properties.h.
bbs_version
pvalue<fpga_version> opae::fpga::types::properties::bbs_version
Definition at line 124 of file properties.h.
vendor_id
pvalue<uint16_t> opae::fpga::types::properties::vendor_id
Definition at line 125 of file properties.h.
device_id
pvalue<uint16_t> opae::fpga::types::properties::device_id
Definition at line 126 of file properties.h.
subsystem_vendor_id
pvalue<uint16_t> opae::fpga::types::properties::subsystem_vendor_id
Definition at line 127 of file properties.h.
subsystem_device_id
pvalue<uint16_t> opae::fpga::types::properties::subsystem_device_id
Definition at line 128 of file properties.h.
model
pvalue<char *> opae::fpga::types::properties::model
Definition at line 129 of file properties.h.
local_memory_size
pvalue<uint64_t> opae::fpga::types::properties::local_memory_size
Definition at line 130 of file properties.h.
capabilities
pvalue<uint64_t> opae::fpga::types::properties::capabilities
Definition at line 131 of file properties.h.
num_mmio
pvalue<uint32_t> opae::fpga::types::properties::num_mmio
Definition at line 132 of file properties.h.
num_interrupts
pvalue<uint32_t> opae::fpga::types::properties::num_interrupts
Definition at line 133 of file properties.h.
accelerator_state
pvalue<fpga_accelerator_state> opae::fpga::types::properties::accelerator_state
Definition at line 134 of file properties.h.
object_id
pvalue<uint64_t> opae::fpga::types::properties::object_id
Definition at line 135 of file properties.h.
parent
pvalue<fpga_token> opae::fpga::types::properties::parent
Definition at line 136 of file properties.h.
interface
pvalue<fpga_interface> opae::fpga::types::properties::interface
Definition at line 137 of file properties.h.
guid
guid_t opae::fpga::types::properties::guid
Definition at line 138 of file properties.h.