OPAE C API: hssi_200g_400g_cmd Class Reference
hssi_200g_400g_cmd Class Reference
#include </root/samples/hssi/hssi_200g_400g_cmd.h>
Public Member Functions
hssi_200g_400g_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual void add_options (CLI::App *app) override
virtual int run (test_afu *afu, CLI::App *app) override
virtual const char * afu_id () const override
std::ostream & print_registers (std::ostream &os, hssi_afu *hafu) const
Public Member Functions inherited from hssi_cmd
hssi_cmd ()
double clock_freq_for (test_afu *afu) const
int set_pkt_filt_dest (const std::string &dfl_dev, uint64_t bin_dest_addr) const
uint64_t mac_bits_for (std::string addr) const
void run_process (const std::string &proc)
void show_eth_stats (const std::string &eth)
void enable_eth_loopback (const std::string &eth, bool enable)
template<typename X >
std::string int_to_hex (X x) const
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
uint32_t num_packets_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 95 of file hssi_200g_400g_cmd.h.
Constructor & Destructor Documentation
hssi_200g_400g_cmd()
hssi_200g_400g_cmd::hssi_200g_400g_cmd () inline
Definition at line 97 of file hssi_200g_400g_cmd.h.
Member Function Documentation
name()
virtual const char* hssi_200g_400g_cmd::name () const inline override virtual
Implements opae::afu_test::command.
Definition at line 99 of file hssi_200g_400g_cmd.h.
description()
virtual const char* hssi_200g_400g_cmd::description () const inline override virtual
Implements opae::afu_test::command.
Definition at line 101 of file hssi_200g_400g_cmd.h.
add_options()
virtual void hssi_200g_400g_cmd::add_options (CLI::App * app) inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 105 of file hssi_200g_400g_cmd.h.
References app, and num_packets_.
run()
virtual int hssi_200g_400g_cmd::run (test_afu * afu, CLI::App * app) inline override virtual
Implements opae::afu_test::command.
Definition at line 111 of file hssi_200g_400g_cmd.h.
References app, CSR_AFU_400G_TG_EN, CSR_HW_PC_CTRL, CSR_HW_TEST_LOOP_CNT, CSR_HW_TEST_ROM_ADDR, CSR_STAT_TIMESTAMP_TG_END_LSB, CSR_STAT_TIMESTAMP_TG_END_MSB, CSR_STAT_TIMESTAMP_TG_START_LSB, CSR_STAT_TIMESTAMP_TG_START_MSB, CSR_STAT_TX_SOP_CNT_LSB, CSR_STAT_TX_SOP_CNT_MSB, opae::afu_test::afu::error, hssi_afu::mbox_read(), hssi_afu::mbox_write(), num_packets_, print_registers(), opae::afu_test::afu::read64(), opae::afu_test::command::running(), opae::afu_test::afu::success, TRAFFIC_CTRL_PORT_SEL, USER_CLKFREQ_N6001, and opae::afu_test::afu::write64().
afu_id()
virtual const char* hssi_200g_400g_cmd::afu_id () const inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 265 of file hssi_200g_400g_cmd.h.
print_registers()
std::ostream& hssi_200g_400g_cmd::print_registers (std::ostream & os, hssi_afu * hafu) const inline
Definition at line 274 of file hssi_200g_400g_cmd.h.
References AFU_SCRATCHPAD, CSR_AFU_400G_TG_EN, CSR_HW_PC_CTRL, CSR_HW_TEST_LOOP_CNT, CSR_HW_TEST_ROM_ADDR, CSR_STAT_RX_EOP_CNT_LSB, CSR_STAT_RX_EOP_CNT_MSB, CSR_STAT_RX_ERR_CNT_LSB, CSR_STAT_RX_ERR_CNT_MSB, CSR_STAT_RX_SOP_CNT_LSB, CSR_STAT_RX_SOP_CNT_MSB, CSR_STAT_TIMESTAMP_TG_END_LSB, CSR_STAT_TIMESTAMP_TG_END_MSB, CSR_STAT_TIMESTAMP_TG_START_LSB, CSR_STAT_TIMESTAMP_TG_START_MSB, CSR_STAT_TX_EOP_CNT_LSB, CSR_STAT_TX_EOP_CNT_MSB, CSR_STAT_TX_ERR_CNT_LSB, CSR_STAT_TX_ERR_CNT_MSB, CSR_STAT_TX_SOP_CNT_LSB, CSR_STAT_TX_SOP_CNT_MSB, ETH_AFU_DFH, ETH_AFU_ID_H, ETH_AFU_ID_L, hssi_cmd::int_to_hex(), hssi_afu::mbox_read(), opae::afu_test::afu::read64(), TRAFFIC_CTRL_CMD, TRAFFIC_CTRL_DATA, and TRAFFIC_CTRL_PORT_SEL.
Referenced by run().
Field Documentation
num_packets_
uint32_t hssi_200g_400g_cmd::num_packets_ protected
Definition at line 373 of file hssi_200g_400g_cmd.h.
Referenced by add_options(), and run().