OPAE C API: host_exerciser::he_cache_cmd Class Reference
host_exerciser::he_cache_cmd Class Reference
#include </root/samples/cxl_host_exerciser/cxl_he_cache_cmd.h>
Public Member Functions
he_cache_cmd ()
virtual ~he_cache_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual const char * afu_id () const override
virtual uint64_t featureid () const override
virtual uint64_t guidl () const override
virtual uint64_t guidh () const override
virtual void add_options (CLI::App *app) override
int he_run_fpga_rd_cache_hit_test ()
int he_run_fpga_wr_cache_hit_test ()
int he_run_fpga_rd_cache_miss_test ()
int he_run_fpga_wr_cache_miss_test ()
int he_run_host_rd_cache_hit_test ()
int he_run_host_wr_cache_hit_test ()
int he_run_host_rd_cache_miss_test ()
int he_run_host_wr_cache_miss_test ()
void he_forcetestcmpl ()
bool he_continuousmode ()
virtual int run (test_afu *afu, CLI::App *app)
Public Member Functions inherited from host_exerciser::he_cmd
he_cmd ()
virtual ~he_cmd ()
double he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks)
void he_perf_counters (he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
void print_csr ()
void host_exerciser_errors ()
int parse_input_options ()
bool he_wait_test_completion ()
bool he_set_bias_mode ()
void he_start_test (const char *str="Test started ......")
bool verify_numa_node ()
bool he_get_perf (double *perf_data, double *latency, he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
uint64_t get_ticks ()
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
bool running () const
void stop ()
Protected Attributes
bool he_continuousmode_
uint32_t he_contmodetime_
uint32_t he_linerep_count_
uint32_t he_stride_
uint32_t he_test_
bool he_test_all_
uint32_t he_dev_instance_
bool he_stride_cmd_
uint32_t he_cls_count_
uint64_t he_latency_iterations_
Protected Attributes inherited from host_exerciser::he_cmd
host_exerciser * host_exe_
uint32_t he_clock_mhz_
uint32_t numa_node_
uint32_t he_target_
uint32_t he_bias_
he_ctl he_ctl_
he_info he_info_
he_rd_config he_rd_cfg_
he_wr_config he_wr_cfg_
he_rd_addr_table_ctrl rd_table_ctl_
he_wr_addr_table_ctrl wr_table_ctl_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 49 of file cxl_he_cache_cmd.h.
Constructor & Destructor Documentation
he_cache_cmd()
host_exerciser::he_cache_cmd::he_cache_cmd () inline
Definition at line 51 of file cxl_he_cache_cmd.h.
~he_cache_cmd()
virtual host_exerciser::he_cache_cmd::~he_cache_cmd () inline virtual
Definition at line 57 of file cxl_he_cache_cmd.h.
Member Function Documentation
name()
virtual const char* host_exerciser::he_cache_cmd::name () const inline override virtual
Implements opae::afu_test::command.
Definition at line 59 of file cxl_he_cache_cmd.h.
description()
virtual const char* host_exerciser::he_cache_cmd::description () const inline override virtual
Implements opae::afu_test::command.
Definition at line 61 of file cxl_he_cache_cmd.h.
afu_id()
virtual const char* host_exerciser::he_cache_cmd::afu_id () const inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 65 of file cxl_he_cache_cmd.h.
References HE_CACHE_AFU_ID.
featureid()
virtual uint64_t host_exerciser::he_cache_cmd::featureid () const inline override virtual
Implements opae::afu_test::command.
Definition at line 67 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_ID.
guidl()
virtual uint64_t host_exerciser::he_cache_cmd::guidl () const inline override virtual
Implements opae::afu_test::command.
Definition at line 69 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_GUIDL.
guidh()
virtual uint64_t host_exerciser::he_cache_cmd::guidh () const inline override virtual
Implements opae::afu_test::command.
Definition at line 71 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_GUIDH.
add_options()
virtual void host_exerciser::he_cache_cmd::add_options (CLI::App * app) inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 73 of file cxl_he_cache_cmd.h.
References app, host_exerciser::he_bias, host_exerciser::he_cmd::he_bias_, he_cls_count_, he_continuousmode_, he_contmodetime_, host_exerciser::he_cxl_device, he_dev_instance_, he_latency_iterations_, he_linerep_count_, he_stride_, host_exerciser::he_cmd::he_target_, host_exerciser::he_targets, he_test_, and host_exerciser::he_test_modes.
he_run_fpga_rd_cache_hit_test()
int host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test () inline
Definition at line 132 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), host_exerciser::he_cmd::get_ticks(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), HE_PRTEST_SCENARIO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_S, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
he_run_fpga_wr_cache_hit_test()
int host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test () inline
Definition at line 302 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read_write(), opae::afu_test::afu::free_dsm(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), HE_PRTEST_SCENARIO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_S, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, host_exerciser::WR_LINE_M, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
he_run_fpga_rd_cache_miss_test()
int host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test () inline
Definition at line 452 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), host_exerciser::he_cmd::get_ticks(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_I, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
he_run_fpga_wr_cache_miss_test()
int host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test () inline
Definition at line 581 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_write(), opae::afu_test::afu::free_dsm(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::WR_LINE_I, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
he_run_host_rd_cache_hit_test()
int host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test () inline
Definition at line 681 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, host_exerciser::BUFFER_SIZE_32KB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), g_stop_thread, opae::afu_test::afu::get_read(), host_exerciser::he_cmd::get_ticks(), host_exerciser::he_cache_thread(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_S, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
he_run_host_wr_cache_hit_test()
int host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test () inline
Definition at line 821 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, host_exerciser::BUFFER_SIZE_32KB, opae::afu_test::afu::free_cache_write(), opae::afu_test::afu::free_dsm(), g_stop_thread, opae::afu_test::afu::get_write(), host_exerciser::he_cache_thread(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::WR_PUSH_I, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
he_run_host_rd_cache_miss_test()
int host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test () inline
Definition at line 924 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), host_exerciser::he_cmd::get_ticks(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_I, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
he_run_host_wr_cache_miss_test()
int host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test () inline
Definition at line 1049 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_write(), opae::afu_test::afu::free_dsm(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::he_rd_addr_table_ctrl::value, host_exerciser::WR_PUSH_I, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
he_forcetestcmpl()
void host_exerciser::he_cache_cmd::he_forcetestcmpl () inline
Definition at line 1143 of file cxl_he_cache_cmd.h.
References host_exerciser::HE_CTL, host_exerciser::he_cmd::he_ctl_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, usleep(), host_exerciser::he_ctl::value, and opae::afu_test::afu::write64().
Referenced by he_continuousmode().
he_continuousmode()
bool host_exerciser::he_cache_cmd::he_continuousmode () inline
Definition at line 1159 of file cxl_he_cache_cmd.h.
References g_he_exit, he_continuousmode_, he_contmodetime_, he_forcetestcmpl(), host_exerciser::he_cmd::host_exe_, and opae::afu_test::afu::logger_.
Referenced by he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), and he_run_host_wr_cache_miss_test().
run()
virtual int host_exerciser::he_cache_cmd::run (test_afu * afu, CLI::App * app) inline virtual
Implements opae::afu_test::command.
Definition at line 1178 of file cxl_he_cache_cmd.h.
References app, host_exerciser::HE_CTL, host_exerciser::he_cmd::he_ctl_, host_exerciser::HE_FPGA_RD_CACHE_HIT, host_exerciser::HE_FPGA_RD_CACHE_MISS, host_exerciser::HE_FPGA_WR_CACHE_HIT, host_exerciser::HE_FPGA_WR_CACHE_MISS, host_exerciser::HE_HOST_RD_CACHE_HIT, host_exerciser::HE_HOST_RD_CACHE_MISS, host_exerciser::HE_HOST_WR_CACHE_HIT, host_exerciser::HE_HOST_WR_CACHE_MISS, he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), he_run_host_wr_cache_miss_test(), host_exerciser::he_cmd::he_set_bias_mode(), he_stride_cmd_, he_test_, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::numa_node_, host_exerciser::he_cmd::print_csr(), host_exerciser::he_ctl::value, host_exerciser::he_cmd::verify_numa_node(), and opae::afu_test::afu::write64().
Field Documentation
he_continuousmode_
bool host_exerciser::he_cache_cmd::he_continuousmode_ protected
Definition at line 1253 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_continuousmode(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), and he_run_host_wr_cache_miss_test().
he_contmodetime_
uint32_t host_exerciser::he_cache_cmd::he_contmodetime_ protected
Definition at line 1254 of file cxl_he_cache_cmd.h.
Referenced by add_options(), and he_continuousmode().
he_linerep_count_
uint32_t host_exerciser::he_cache_cmd::he_linerep_count_ protected
Definition at line 1255 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), and he_run_host_wr_cache_miss_test().
he_stride_
uint32_t host_exerciser::he_cache_cmd::he_stride_ protected
Definition at line 1256 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), and he_run_host_wr_cache_miss_test().
he_test_
uint32_t host_exerciser::he_cache_cmd::he_test_ protected
Definition at line 1257 of file cxl_he_cache_cmd.h.
Referenced by add_options(), and run().
he_test_all_
bool host_exerciser::he_cache_cmd::he_test_all_ protected
Definition at line 1258 of file cxl_he_cache_cmd.h.
he_dev_instance_
uint32_t host_exerciser::he_cache_cmd::he_dev_instance_ protected
Definition at line 1259 of file cxl_he_cache_cmd.h.
Referenced by add_options().
he_stride_cmd_
bool host_exerciser::he_cache_cmd::he_stride_cmd_ protected
Definition at line 1260 of file cxl_he_cache_cmd.h.
Referenced by he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), and run().
he_cls_count_
uint32_t host_exerciser::he_cache_cmd::he_cls_count_ protected
Definition at line 1261 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_rd_cache_miss_test(), he_run_host_wr_cache_hit_test(), and he_run_host_wr_cache_miss_test().
he_latency_iterations_
uint64_t host_exerciser::he_cache_cmd::he_latency_iterations_ protected
Definition at line 1262 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_rd_cache_miss_test().