OPAE C API: hssi_100g_cmd Class Reference
hssi_100g_cmd Class Reference
#include </root/samples/hssi/hssi_100g_cmd.h>
Public Member Functions
hssi_100g_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual void add_options (CLI::App *app) override
uint64_t timestamp_in_seconds (uint64_t x) const
uint64_t total_per_second (uint64_t y, uint64_t z) const
uint64_t data_64 (uint32_t lowerbytes, uint32_t higherbytes) const
void read_performance (perf_data *perf, hssi_afu *hafu) const
void calc_performance (perf_data *old_perf, perf_data *new_perf, perf_data *perf, uint64_t size) const
uint8_t stall_enable (hssi_afu *hafu) const
uint8_t stall_disable (hssi_afu *hafu) const
void write_ctrl_config (hssi_afu *hafu, ctrl_config config_data) const
void write_csr_addr (hssi_afu *hafu, uint64_t bin_src_addr, uint64_t bin_dest_addr) const
std::ostream & print_monitor_headers (std::ostream &os, uint32_t max_timer) const
std::ostream & print_monitor_data (std::ostream &os, perf_data *data, int port, uint32_t timer) const
void select_port (int port, ctrl_config config_data, hssi_afu *hafu) const
void capture_perf (perf_data *old_perf_data, hssi_afu *hafu) const
std::ostream & run_monitor (std::ostream &os, perf_data *old_perf_data, int port, hssi_afu *hafu, uint32_t timer)
char get_user_input (char key) const
void quit_monitor (uint8_t size, std::string move, hssi_afu *hafu) const
void reset_monitor (std::vector< int > port_, std::string move, ctrl_config config_data, hssi_afu *hafu) const
void move_cursor (uint8_t size, std::string move) const
virtual int run (test_afu *afu, CLI::App *app) override
virtual const char * afu_id () const override
std::ostream & print_registers (std::ostream &os, hssi_afu *hafu) const
Public Member Functions inherited from hssi_cmd
hssi_cmd ()
double clock_freq_for (test_afu *afu) const
int set_pkt_filt_dest (const std::string &dfl_dev, uint64_t bin_dest_addr) const
uint64_t mac_bits_for (std::string addr) const
void run_process (const std::string &proc)
void show_eth_stats (const std::string &eth)
void enable_eth_loopback (const std::string &eth, bool enable)
template<typename X >
std::string int_to_hex (X x) const
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
std::vector< int > port_
std::string eth_loopback_
uint32_t num_packets_
std::string gap_
std::string pattern_
std::string src_addr_
std::string dest_addr_
std::string eth_ifc_
uint32_t start_size_
uint32_t end_size_
std::string end_select_
std::string continuous_
uint32_t contmonitor_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 70 of file hssi_100g_cmd.h.
Constructor & Destructor Documentation
hssi_100g_cmd()
hssi_100g_cmd::hssi_100g_cmd () inline
Definition at line 73 of file hssi_100g_cmd.h.
Member Function Documentation
name()
virtual const char* hssi_100g_cmd::name () const inline override virtual
Implements opae::afu_test::command.
Reimplemented in hssi_pkt_filt_100g_cmd.
Definition at line 89 of file hssi_100g_cmd.h.
description()
virtual const char* hssi_100g_cmd::description () const inline override virtual
Implements opae::afu_test::command.
Reimplemented in hssi_pkt_filt_100g_cmd.
Definition at line 94 of file hssi_100g_cmd.h.
add_options()
virtual void hssi_100g_cmd::add_options (CLI::App * app) inline override virtual
Reimplemented from opae::afu_test::command.
Reimplemented in hssi_pkt_filt_100g_cmd.
Definition at line 99 of file hssi_100g_cmd.h.
References app, continuous_, contmonitor_, dest_addr_, end_select_, end_size_, eth_ifc_, eth_loopback_, gap_, num_packets_, pattern_, port_, src_addr_, and start_size_.
Referenced by hssi_pkt_filt_100g_cmd::add_options().
timestamp_in_seconds()
uint64_t hssi_100g_cmd::timestamp_in_seconds (uint64_t x) const inline
Definition at line 154 of file hssi_100g_cmd.h.
References CONV_SEC.
Referenced by total_per_second().
total_per_second()
uint64_t hssi_100g_cmd::total_per_second (uint64_t y, uint64_t z) const inline
Definition at line 159 of file hssi_100g_cmd.h.
References timestamp_in_seconds().
Referenced by calc_performance().
data_64()
uint64_t hssi_100g_cmd::data_64 (uint32_t lowerbytes, uint32_t higherbytes) const inline
Definition at line 196 of file hssi_100g_cmd.h.
References CSR_SHIFT.
Referenced by read_performance().
read_performance()
void hssi_100g_cmd::read_performance (perf_data * perf, hssi_afu * hafu) const inline
Definition at line 201 of file hssi_100g_cmd.h.
References CSR_RX_END_TIMESTAMP_HI, CSR_RX_END_TIMESTAMP_LO, CSR_STATS_RX_CNT_HI, CSR_STATS_RX_CNT_LO, CSR_STATS_RX_GD_CNT_HI, CSR_STATS_RX_GD_CNT_LO, CSR_STATS_TX_CNT_HI, CSR_STATS_TX_CNT_LO, data_64(), hssi_afu::mbox_read(), perf_data::rx_count, perf_data::rx_good_packet_count, perf_data::rx_pkt_sec, and perf_data::tx_count.
Referenced by capture_perf().
calc_performance()
void hssi_100g_cmd::calc_performance (perf_data * old_perf, perf_data * new_perf, perf_data * perf, uint64_t size) const inline
Definition at line 209 of file hssi_100g_cmd.h.
References perf_data::bw, perf_data::rx_count, perf_data::rx_good_packet_count, perf_data::rx_pkt_sec, total_per_second(), and perf_data::tx_count.
Referenced by run_monitor().
stall_enable()
uint8_t hssi_100g_cmd::stall_enable (hssi_afu * hafu) const inline
Definition at line 218 of file hssi_100g_cmd.h.
References CSR_STATS_CTRL, hssi_afu::mbox_read(), and hssi_afu::mbox_write().
Referenced by capture_perf().
stall_disable()
uint8_t hssi_100g_cmd::stall_disable (hssi_afu * hafu) const inline
Definition at line 227 of file hssi_100g_cmd.h.
References CSR_STATS_CTRL, hssi_afu::mbox_read(), and hssi_afu::mbox_write().
Referenced by capture_perf().
write_ctrl_config()
void hssi_100g_cmd::write_ctrl_config (hssi_afu * hafu, ctrl_config config_data) const inline
Definition at line 236 of file hssi_100g_cmd.h.
References CSR_CTRL0, CSR_CTRL1, CSR_PKT_SIZE, ctrl_config::ctrl0_data, ctrl_config::ctrl1_data, hssi_afu::mbox_write(), and ctrl_config::pkt_size_data.
Referenced by select_port().
write_csr_addr()
void hssi_100g_cmd::write_csr_addr (hssi_afu * hafu, uint64_t bin_src_addr, uint64_t bin_dest_addr) const inline
Definition at line 243 of file hssi_100g_cmd.h.
References CSR_DST_ADDR_HI, CSR_DST_ADDR_LO, CSR_SRC_ADDR_HI, CSR_SRC_ADDR_LO, and hssi_afu::mbox_write().
Referenced by select_port().
print_monitor_headers()
std::ostream& hssi_100g_cmd::print_monitor_headers (std::ostream & os, uint32_t max_timer) const inline
Definition at line 252 of file hssi_100g_cmd.h.
Referenced by run().
print_monitor_data()
std::ostream& hssi_100g_cmd::print_monitor_data (std::ostream & os, perf_data * data, int port, uint32_t timer) const inline
Definition at line 274 of file hssi_100g_cmd.h.
References perf_data::bw, perf_data::rx_count, perf_data::rx_good_packet_count, perf_data::rx_pkt_sec, and perf_data::tx_count.
Referenced by run_monitor().
select_port()
void hssi_100g_cmd::select_port (int port, ctrl_config config_data, hssi_afu * hafu) const inline
Definition at line 291 of file hssi_100g_cmd.h.
References dest_addr_, hssi_cmd::mac_bits_for(), src_addr_, TRAFFIC_CTRL_PORT_SEL, opae::afu_test::afu::write64(), write_csr_addr(), and write_ctrl_config().
Referenced by reset_monitor(), and run().
capture_perf()
void hssi_100g_cmd::capture_perf (perf_data * old_perf_data, hssi_afu * hafu) const inline
Definition at line 299 of file hssi_100g_cmd.h.
References read_performance(), stall_disable(), and stall_enable().
Referenced by run(), and run_monitor().
run_monitor()
std::ostream& hssi_100g_cmd::run_monitor (std::ostream & os, perf_data * old_perf_data, int port, hssi_afu * hafu, uint32_t timer) inline
Definition at line 309 of file hssi_100g_cmd.h.
References calc_performance(), capture_perf(), print_monitor_data(), and start_size_.
Referenced by run().
get_user_input()
char hssi_100g_cmd::get_user_input (char key) const inline
Definition at line 325 of file hssi_100g_cmd.h.
Referenced by run().
quit_monitor()
void hssi_100g_cmd::quit_monitor (uint8_t size, std::string move, hssi_afu * hafu) const inline
Definition at line 337 of file hssi_100g_cmd.h.
References CSR_CTRL0, CSR_STATS_CTRL, DATA_CNF_PKT_NUM, hssi_afu::mbox_write(), move_cursor(), and ZERO.
Referenced by run().
reset_monitor()
void hssi_100g_cmd::reset_monitor (std::vector< int > port_, std::string move, ctrl_config config_data, hssi_afu * hafu) const inline
Definition at line 345 of file hssi_100g_cmd.h.
References CSR_STATS_CTRL, hssi_afu::mbox_write(), move_cursor(), ONE, port_, select_port(), and ZERO.
Referenced by run().
move_cursor()
void hssi_100g_cmd::move_cursor (uint8_t size, std::string move) const inline
Definition at line 358 of file hssi_100g_cmd.h.
Referenced by quit_monitor(), reset_monitor(), and run().
run()
virtual int hssi_100g_cmd::run (test_afu * afu, CLI::App * app) inline override virtual
Implements opae::afu_test::command.
Reimplemented in hssi_pkt_filt_100g_cmd.
Definition at line 368 of file hssi_100g_cmd.h.
References app, capture_perf(), continuous_, contmonitor_, CSR_CTRL0, CSR_CTRL1, CSR_DST_ADDR_HI, CSR_DST_ADDR_LO, CSR_PKT_SIZE, CSR_SRC_ADDR_HI, CSR_SRC_ADDR_LO, CSR_TX_COUNT, ctrl_config::ctrl0_data, ctrl_config::ctrl1_data, CURSOR_DOWN, CURSOR_UP, DATA_CNF_CONTINUOUS_MODE, DATA_CNF_FIXED_MODE, dest_addr_, hssi_cmd::enable_eth_loopback(), end_select_, end_size_, opae::afu_test::afu::error, ETH_AFU_DFH, eth_ifc_, eth_loopback_, hssi_afu::ethernet_interface(), gap_, get_user_input(), INVALID_MAC, hssi_cmd::mac_bits_for(), MAX_PORT, hssi_afu::mbox_read(), hssi_afu::mbox_write(), move_cursor(), num_packets_, pattern_, ctrl_config::pkt_size_data, port_, print_monitor_headers(), print_registers(), quit_monitor(), opae::afu_test::afu::read64(), reset_monitor(), run_monitor(), opae::afu_test::command::running(), select_port(), hssi_cmd::show_eth_stats(), src_addr_, start_size_, STOP_BITS, opae::afu_test::afu::success, TRAFFIC_CTRL_PORT_SEL, and opae::afu_test::afu::write64().
Referenced by hssi_pkt_filt_100g_cmd::run().
afu_id()
virtual const char* hssi_100g_cmd::afu_id () const inline override virtual
Reimplemented from opae::afu_test::command.
Definition at line 580 of file hssi_100g_cmd.h.
print_registers()
std::ostream& hssi_100g_cmd::print_registers (std::ostream & os, hssi_afu * hafu) const inline
Definition at line 585 of file hssi_100g_cmd.h.
References AFU_SCRATCHPAD, CSR_BLOCK_ID, CSR_CTRL0, CSR_CTRL1, CSR_DST_ADDR_HI, CSR_DST_ADDR_LO, CSR_MLB_RST, CSR_PKT_SIZE, CSR_RX_COUNT, CSR_SCRATCH, CSR_SRC_ADDR_HI, CSR_SRC_ADDR_LO, CSR_TX_COUNT, ETH_AFU_DFH, ETH_AFU_ID_H, ETH_AFU_ID_L, hssi_cmd::int_to_hex(), hssi_afu::mbox_read(), opae::afu_test::afu::read64(), TRAFFIC_CTRL_CMD, TRAFFIC_CTRL_DATA, and TRAFFIC_CTRL_PORT_SEL.
Referenced by run().
Field Documentation
port_
std::vector<int> hssi_100g_cmd::port_ protected
Definition at line 633 of file hssi_100g_cmd.h.
Referenced by add_options(), reset_monitor(), and run().
eth_loopback_
std::string hssi_100g_cmd::eth_loopback_ protected
Definition at line 634 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
num_packets_
uint32_t hssi_100g_cmd::num_packets_ protected
Definition at line 635 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
gap_
std::string hssi_100g_cmd::gap_ protected
Definition at line 636 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
pattern_
std::string hssi_100g_cmd::pattern_ protected
Definition at line 637 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
src_addr_
std::string hssi_100g_cmd::src_addr_ protected
Definition at line 638 of file hssi_100g_cmd.h.
Referenced by add_options(), run(), and select_port().
dest_addr_
std::string hssi_100g_cmd::dest_addr_ protected
Definition at line 639 of file hssi_100g_cmd.h.
Referenced by add_options(), run(), hssi_pkt_filt_100g_cmd::run(), and select_port().
eth_ifc_
std::string hssi_100g_cmd::eth_ifc_ protected
Definition at line 640 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
start_size_
uint32_t hssi_100g_cmd::start_size_ protected
Definition at line 641 of file hssi_100g_cmd.h.
Referenced by add_options(), run(), and run_monitor().
end_size_
uint32_t hssi_100g_cmd::end_size_ protected
Definition at line 642 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
end_select_
std::string hssi_100g_cmd::end_select_ protected
Definition at line 643 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
continuous_
std::string hssi_100g_cmd::continuous_ protected
Definition at line 644 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().
contmonitor_
uint32_t hssi_100g_cmd::contmonitor_ protected
Definition at line 645 of file hssi_100g_cmd.h.
Referenced by add_options(), and run().