OPAE C API: opae::afu_test::command Class Reference
opae::afu_test::command Class Reference abstract
#include </root/samples/cxl_host_exerciser/he_cache_test.h>
Public Types
typedef std::shared_ptr< command > ptr_t
Public Member Functions
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual int run (afu *afu, CLI::App *app)=0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Private Attributes
std::atomic< bool > running_
Detailed Description
Definition at line 231 of file he_cache_test.h.
Member Typedef Documentation
ptr_t
typedef std::shared_ptr<command> opae::afu_test::command::ptr_t
Definition at line 233 of file he_cache_test.h.
Constructor & Destructor Documentation
command()
opae::afu_test::command::command () inline
Definition at line 234 of file he_cache_test.h.
~command()
virtual opae::afu_test::command::~command () inline virtual
Definition at line 235 of file he_cache_test.h.
Member Function Documentation
name()
virtual const char* opae::afu_test::command::name () const pure virtual
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_lpbk_cmd, host_exerciser::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
description()
virtual const char* opae::afu_test::command::description () const pure virtual
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_lpbk_cmd, host_exerciser::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
run()
virtual int opae::afu_test::command::run (afu * afu, CLI::App * app) pure virtual
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, cxl_mem_tg::cxl_tg_test, host_exerciser::host_exerciser_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, dummy_afu::ddr_test, host_exerciser::he_cache_lpbk_cmd, and host_exerciser::he_cache_cmd.
add_options()
virtual void opae::afu_test::command::add_options (CLI::App * app) inline virtual
Reimplemented in hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::he_cache_lpbk_cmd, host_exerciser::he_cache_cmd, and dummy_afu::mmio_test.
Definition at line 239 of file he_cache_test.h.
References app.
afu_id()
virtual const char* opae::afu_test::command::afu_id () const inline virtual
Reimplemented in mem_tg::tg_test, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_lpbk_cmd, and host_exerciser::he_cache_cmd.
Definition at line 240 of file he_cache_test.h.
featureid()
virtual uint64_t opae::afu_test::command::featureid () const pure virtual
Implemented in host_exerciser::he_cache_lpbk_cmd, and host_exerciser::he_cache_cmd.
guidl()
virtual uint64_t opae::afu_test::command::guidl () const pure virtual
Implemented in host_exerciser::he_cache_lpbk_cmd, and host_exerciser::he_cache_cmd.
guidh()
virtual uint64_t opae::afu_test::command::guidh () const pure virtual
Implemented in host_exerciser::he_cache_lpbk_cmd, and host_exerciser::he_cache_cmd.
running()
bool opae::afu_test::command::running () const inline
Definition at line 246 of file he_cache_test.h.
Referenced by hssi_100g_cmd::run(), hssi_10g_cmd::run(), and hssi_200g_400g_cmd::run().
stop()
void opae::afu_test::command::stop () inline
Definition at line 247 of file he_cache_test.h.
Field Documentation
running_
std::atomic<bool> opae::afu_test::command::running_ private
Definition at line 250 of file he_cache_test.h.