OPAE C API: hssi_cmd Class Reference
hssi_cmd Class Reference
#include </root/samples/hssi/hssi_cmd.h>
Public Member Functions
hssi_cmd ()
double clock_freq_for (test_afu *afu) const
int set_pkt_filt_dest (const std::string &dfl_dev, uint64_t bin_dest_addr) const
uint64_t mac_bits_for (std::string addr) const
void run_process (const std::string &proc)
void show_eth_stats (const std::string &eth)
void enable_eth_loopback (const std::string &eth, bool enable)
template<typename X >
std::string int_to_hex (X x) const
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual int run (afu *afu, CLI::App *app)=0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 51 of file hssi_cmd.h.
Constructor & Destructor Documentation
hssi_cmd()
hssi_cmd::hssi_cmd () inline
Definition at line 54 of file hssi_cmd.h.
Member Function Documentation
clock_freq_for()
double hssi_cmd::clock_freq_for (test_afu * afu) const inline
Definition at line 56 of file hssi_cmd.h.
References BITSVER_MAJOR_N6000, BITSVER_MAJOR_S10, opae::fpga::types::token::enumerate(), FPGA_BBS_VER_MAJOR, FPGA_DEVICE, opae::fpga::types::properties::get(), INVALID_CLOCK_FREQ, USER_CLKFREQ_N6000, and USER_CLKFREQ_S10.
Referenced by hssi_10g_cmd::run().
set_pkt_filt_dest()
int hssi_cmd::set_pkt_filt_dest (const std::string & dfl_dev, uint64_t bin_dest_addr) const inline
Definition at line 88 of file hssi_cmd.h.
References opae::afu_test::afu::error, int_to_hex(), opae_uio_close(), opae_uio_open(), opae_uio_region_get(), PKT_FILT_CSR_DEST_ADDR, and opae::afu_test::afu::success.
Referenced by hssi_pkt_filt_100g_cmd::run(), and hssi_pkt_filt_10g_cmd::run().
mac_bits_for()
uint64_t hssi_cmd::mac_bits_for (std::string addr) const inline
Definition at line 121 of file hssi_cmd.h.
References INVALID_MAC.
Referenced by hssi_100g_cmd::run(), hssi_10g_cmd::run(), hssi_pkt_filt_100g_cmd::run(), hssi_pkt_filt_10g_cmd::run(), and hssi_100g_cmd::select_port().
run_process()
void hssi_cmd::run_process (const std::string & proc) inline
Definition at line 134 of file hssi_cmd.h.
Referenced by enable_eth_loopback(), and show_eth_stats().
show_eth_stats()
void hssi_cmd::show_eth_stats (const std::string & eth) inline
Definition at line 146 of file hssi_cmd.h.
References run_process().
Referenced by hssi_100g_cmd::run(), and hssi_10g_cmd::run().
enable_eth_loopback()
void hssi_cmd::enable_eth_loopback (const std::string & eth, bool enable) inline
Definition at line 152 of file hssi_cmd.h.
References run_process(), and usleep().
Referenced by hssi_100g_cmd::run(), and hssi_10g_cmd::run().
int_to_hex()
template<typename X > std::string hssi_cmd::int_to_hex (X x) const inline
Definition at line 164 of file hssi_cmd.h.
Referenced by hssi_100g_cmd::print_registers(), hssi_10g_cmd::print_registers(), hssi_200g_400g_cmd::print_registers(), and set_pkt_filt_dest().