OPAE C API: opae::afu_test::afu Class Reference
opae::afu_test::afu Class Reference
#include </root/samples/cxl_host_exerciser/he_cache_test.h>
Public Types
enum exit_codes {
success = 0 , not_run , not_found , no_access ,
exception , error
}
typedef int(* command_fn) (afu *afu, CLI::App *app)
Public Member Functions
afu (const char *name, const char *afu_id=nullptr, const char *log_level=nullptr)
virtual ~afu ()
CLI::App & cli ()
int find_dev_feature ()
void unmap_mmio ()
bool map_mmio ()
int open_handle (const char *dev)
int main (int argc, char *argv[])
virtual int run (CLI::App *app, command::ptr_t test)
template<class T >
CLI::App * register_command ()
uint64_t read64 (uint32_t offset)
void write64 (uint32_t offset, uint64_t value)
uint32_t read32 (uint32_t offset)
void write32 (uint32_t offset, uint32_t value)
command::ptr_t current_command () const
bool allocate_dsm (size_t len=((4) *1024), uint32_t numa_node=0)
bool free_dsm ()
void reset_dsm ()
bool allocate_cache_read (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read ()
bool allocate_cache_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_write ()
bool allocate_cache_read_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read_write ()
uint8_t * get_dsm () const
uint8_t * get_read () const
uint8_t * get_write () const
uint8_t * get_read_write () const
Data Fields
std::shared_ptr< spdlog::logger > logger_
Protected Attributes
std::string name_
std::string afu_id_
CLI::App app_
std::string pci_addr_
std::string log_level_
uint32_t timeout_msec_
int fd_
uint8_t * mmio_base_
uint64_t mmio_len_
uint8_t * dsm_buffer_
uint64_t dsm_buf_len_
uint8_t * rd_buffer_
uint64_t rd_buf_len_
uint8_t * wr_buffer_
uint64_t wr_buf_len_
uint8_t * rd_wr_buffer_
uint64_t rd_wr_buf_len_
struct dfl_cxl_cache_region_info rinfo_
std::string dev_path_ [2]
command::ptr_t current_command_
std::map< CLI::App *, command::ptr_t > commands_
Detailed Description
Definition at line 269 of file he_cache_test.h.
Member Typedef Documentation
command_fn
typedef int(* opae::afu_test::afu::command_fn) (afu *afu, CLI::App *app)
Definition at line 271 of file he_cache_test.h.
Member Enumeration Documentation
exit_codes
enum opae::afu_test::afu::exit_codes
Enumerator
success
not_run
not_found
no_access
exception
error
Definition at line 272 of file he_cache_test.h.
Constructor & Destructor Documentation
afu()
opae::afu_test::afu::afu (const char * name, const char * afu_id = nullptr, const char * log_level = nullptr) inline
Definition at line 281 of file he_cache_test.h.
References opae::afu_test::spdlog_levels().
~afu()
virtual opae::afu_test::afu::~afu () inline virtual
Definition at line 296 of file he_cache_test.h.
Member Function Documentation
cli()
CLI::App& opae::afu_test::afu::cli () inline
Definition at line 304 of file he_cache_test.h.
find_dev_feature()
int opae::afu_test::afu::find_dev_feature () inline
Definition at line 306 of file he_cache_test.h.
References FEATURE_DEV, MAX_SIZE, and sysfs_read_u64().
unmap_mmio()
void opae::afu_test::afu::unmap_mmio () inline
Definition at line 376 of file he_cache_test.h.
map_mmio()
bool opae::afu_test::afu::map_mmio () inline
Definition at line 383 of file he_cache_test.h.
open_handle()
int opae::afu_test::afu::open_handle (const char * dev) inline
Definition at line 396 of file he_cache_test.h.
main()
int opae::afu_test::afu::main (int argc, char * argv[]) inline
Definition at line 434 of file he_cache_test.h.
References app.
Referenced by main().
run()
virtual int opae::afu_test::afu::run (CLI::App * app, command::ptr_t test) inline virtual
Reimplemented in mem_tg::mem_tg, host_exerciser::host_exerciser, dummy_afu::dummy_afu, cxl_mem_tg::cxl_mem_tg, and host_exerciser::host_exerciser.
Definition at line 477 of file he_cache_test.h.
References app.
Referenced by host_exerciser::host_exerciser::run(), cxl_mem_tg::cxl_mem_tg::run(), dummy_afu::dummy_afu::run(), and mem_tg::mem_tg::run().
register_command()
template<class T > CLI::App* opae::afu_test::afu::register_command () inline
Definition at line 500 of file he_cache_test.h.
Referenced by main().
read64()
uint64_t opae::afu_test::afu::read64 (uint32_t offset) inline
Definition at line 508 of file he_cache_test.h.
Referenced by mem_tg::tg_test::config_input_options(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test(), host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::host_exerciser_cmd::host_exerciser_errors(), host_exerciser::host_exerciser_cmd::host_exerciser_status(), host_exerciser::host_exerciser_cmd::host_exerciser_swtestmsg(), host_exerciser::he_cmd::print_csr(), hssi_100g_cmd::print_registers(), hssi_10g_cmd::print_registers(), hssi_200g_400g_cmd::print_registers(), host_exerciser::host_exerciser_cmd::run(), hssi_100g_cmd::run(), hssi_200g_400g_cmd::run(), mem_tg::tg_test::run(), mem_tg::tg_test::tg_perf(), and mem_tg::tg_test::tg_wait_test_completion().
write64()
void opae::afu_test::afu::write64 (uint32_t offset, uint64_t value) inline
Definition at line 513 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test(), host_exerciser::he_cmd::he_start_test(), host_exerciser::he_cache_cmd::run(), host_exerciser::he_cache_lpbk_cmd::run(), hssi_100g_cmd::run(), hssi_200g_400g_cmd::run(), host_exerciser::host_exerciser_cmd::run_single_test(), and hssi_100g_cmd::select_port().
read32()
uint32_t opae::afu_test::afu::read32 (uint32_t offset) inline
Definition at line 518 of file he_cache_test.h.
write32()
void opae::afu_test::afu::write32 (uint32_t offset, uint32_t value) inline
Definition at line 523 of file he_cache_test.h.
Referenced by mem_tg::tg_test::config_input_options(), host_exerciser::host_exerciser_cmd::he_forcetestcmpl(), mem_tg::tg_test::run_mem_test(), and host_exerciser::host_exerciser_cmd::run_single_test().
current_command()
command::ptr_t opae::afu_test::afu::current_command () const inline
Definition at line 528 of file he_cache_test.h.
Referenced by sig_handler().
allocate_dsm()
bool opae::afu_test::afu::allocate_dsm (size_t len = ((4)*1024), uint32_t numa_node = 0) inline
Definition at line 530 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
free_dsm()
bool opae::afu_test::afu::free_dsm () inline
Definition at line 572 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
reset_dsm()
void opae::afu_test::afu::reset_dsm () inline
Definition at line 600 of file he_cache_test.h.
allocate_cache_read()
bool opae::afu_test::afu::allocate_cache_read (size_t len = ((2)*1024 * 1024), uint32_t numa_node = 0) inline
Definition at line 604 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), and DFL_CXL_CACHE_RD_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test().
free_cache_read()
bool opae::afu_test::afu::free_cache_read () inline
Definition at line 646 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_RD_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test().
allocate_cache_write()
bool opae::afu_test::afu::allocate_cache_write (size_t len = ((2)*1024 * 1024), uint32_t numa_node = 0) inline
Definition at line 673 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
free_cache_write()
bool opae::afu_test::afu::free_cache_write () inline
Definition at line 714 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_miss_test().
allocate_cache_read_write()
bool opae::afu_test::afu::allocate_cache_read_write (size_t len = ((2)*1024 * 1024), uint32_t numa_node = 0) inline
Definition at line 741 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test().
free_cache_read_write()
bool opae::afu_test::afu::free_cache_read_write () inline
Definition at line 788 of file he_cache_test.h.
References buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test().
get_dsm()
uint8_t* opae::afu_test::afu::get_dsm () const inline
Definition at line 822 of file he_cache_test.h.
Referenced by host_exerciser::he_cmd::get_ticks(), host_exerciser::he_cmd::he_get_perf(), host_exerciser::he_cmd::he_perf_counters(), and host_exerciser::he_cmd::he_wait_test_completion().
get_read()
uint8_t* opae::afu_test::afu::get_read () const inline
Definition at line 824 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test().
get_write()
uint8_t* opae::afu_test::afu::get_write () const inline
Definition at line 826 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
get_read_write()
uint8_t* opae::afu_test::afu::get_read_write () const inline
Definition at line 828 of file he_cache_test.h.
Field Documentation
name_
std::string opae::afu_test::afu::name_ protected
Definition at line 831 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
afu_id_
std::string opae::afu_test::afu::afu_id_ protected
Definition at line 832 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
app_
CLI::App opae::afu_test::afu::app_ protected
Definition at line 833 of file he_cache_test.h.
pci_addr_
std::string opae::afu_test::afu::pci_addr_ protected
Definition at line 834 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
log_level_
std::string opae::afu_test::afu::log_level_ protected
Definition at line 835 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
timeout_msec_
uint32_t opae::afu_test::afu::timeout_msec_ protected
Definition at line 836 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
fd_
int opae::afu_test::afu::fd_ protected
Definition at line 838 of file he_cache_test.h.
mmio_base_
uint8_t* opae::afu_test::afu::mmio_base_ protected
Definition at line 839 of file he_cache_test.h.
mmio_len_
uint64_t opae::afu_test::afu::mmio_len_ protected
Definition at line 840 of file he_cache_test.h.
dsm_buffer_
uint8_t* opae::afu_test::afu::dsm_buffer_ protected
Definition at line 842 of file he_cache_test.h.
dsm_buf_len_
uint64_t opae::afu_test::afu::dsm_buf_len_ protected
Definition at line 843 of file he_cache_test.h.
rd_buffer_
uint8_t* opae::afu_test::afu::rd_buffer_ protected
Definition at line 845 of file he_cache_test.h.
rd_buf_len_
uint64_t opae::afu_test::afu::rd_buf_len_ protected
Definition at line 846 of file he_cache_test.h.
wr_buffer_
uint8_t* opae::afu_test::afu::wr_buffer_ protected
Definition at line 848 of file he_cache_test.h.
wr_buf_len_
uint64_t opae::afu_test::afu::wr_buf_len_ protected
Definition at line 849 of file he_cache_test.h.
rd_wr_buffer_
uint8_t* opae::afu_test::afu::rd_wr_buffer_ protected
Definition at line 851 of file he_cache_test.h.
rd_wr_buf_len_
uint64_t opae::afu_test::afu::rd_wr_buf_len_ protected
Definition at line 852 of file he_cache_test.h.
rinfo_
struct dfl_cxl_cache_region_info opae::afu_test::afu::rinfo_ protected
Definition at line 852 of file he_cache_test.h.
dev_path_
std::string opae::afu_test::afu::dev_path_[2] protected
Definition at line 856 of file he_cache_test.h.
current_command_
command::ptr_t opae::afu_test::afu::current_command_ protected
Definition at line 858 of file he_cache_test.h.
commands_
std::map<CLI::App *, command::ptr_t> opae::afu_test::afu::commands_ protected
Definition at line 859 of file he_cache_test.h.
logger_
std::shared_ptr<spdlog::logger> opae::afu_test::afu::logger_
Definition at line 862 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate(), host_exerciser::he_cache_cmd::he_continuousmode(), host_exerciser::host_exerciser_cmd::he_continuousmode(), host_exerciser::host_exerciser_cmd::he_perf_counters(), host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_miss_test(), host_exerciser::host_exerciser_cmd::host_exerciser_status(), host_exerciser::he_cmd::print_csr(), host_exerciser::host_exerciser_cmd::run(), mem_tg::tg_test::run_mem_test(), and host_exerciser::host_exerciser_cmd::run_single_test().