OPAE C API: host_exerciser::host_exerciser_cmd Class Reference
host_exerciser::host_exerciser_cmd Class Reference
#include </root/samples/host_exerciser/host_exerciser_cmd.h>
Public Member Functions
host_exerciser_cmd ()
virtual ~host_exerciser_cmd ()
void host_exerciser_status ()
void host_exerciser_errors ()
uint64_t host_exerciser_swtestmsg ()
uint64_t cacheline_aligned_addr (uint64_t num)
double he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks)
uint64_t dsm_num_ticks (const volatile he_dsm_status *dsm_status)
uint64_t dsm_num_reads (const volatile he_dsm_status *dsm_status)
uint64_t dsm_num_writes (const volatile he_dsm_status *dsm_status)
void he_perf_counters ()
bool he_interrupt (event::ptr_t ev)
bool he_wait_test_completion ()
void he_forcetestcmpl ()
void he_init_src_buffer (shared_buffer::ptr_t buffer)
void he_dump_buffer (shared_buffer::ptr_t buffer, const char *msg)
uint64_t he_compare_buffer ()
bool he_continuousmode ()
void set_cfg_reqlen (hostexe_req_len req_len)
void set_cfg_reqlen (uint32_t req_len)
hostexe_req_len get_cfg_reqlen ()
int parse_input_options ()
int run_single_test ()
int run_all_tests ()
virtual int run (test_afu *afu, CLI::App *app)
Public Member Functions inherited from opae::afu_test::command
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Protected Attributes
he_cfg he_lpbk_cfg_
he_ctl he_lpbk_ctl_
host_exerciser * host_exe_
shared_buffer::ptr_t source_
shared_buffer::ptr_t destination_
shared_buffer::ptr_t dsm_
he_interrupt0 he_interrupt_
token::ptr_t token_
hostexe_req_len he_lpbk_max_reqlen_
uint8_t he_lpbk_api_ver_
bool he_lpbk_atomics_supported_
bool is_ase_sim_
Additional Inherited Members
Public Types inherited from opae::afu_test::command
typedef std::shared_ptr< command > ptr_t
Detailed Description
Definition at line 51 of file host_exerciser_cmd.h.
Constructor & Destructor Documentation
host_exerciser_cmd()
host_exerciser::host_exerciser_cmd::host_exerciser_cmd () inline
Definition at line 54 of file host_exerciser_cmd.h.
References he_lpbk_api_ver_, he_lpbk_atomics_supported_, he_lpbk_cfg_, he_lpbk_ctl_, he_lpbk_max_reqlen_, host_exerciser::HOSTEXE_CLS_8, is_ase_sim_, host_exerciser::he_ctl::value, and host_exerciser::he_cfg::value.
~host_exerciser_cmd()
virtual host_exerciser::host_exerciser_cmd::~host_exerciser_cmd () inline virtual
Definition at line 63 of file host_exerciser_cmd.h.
Member Function Documentation
host_exerciser_status()
void host_exerciser::host_exerciser_cmd::host_exerciser_status () inline
Definition at line 65 of file host_exerciser_cmd.h.
References host_exerciser::HE_STATUS0, host_exerciser::HE_STATUS1, host_exe_, opae::afu_test::afu::logger_, opae::afu_test::afu::read64(), host_exerciser::he_status0::value, and host_exerciser::he_status1::value.
Referenced by he_perf_counters(), and he_wait_test_completion().
host_exerciser_errors()
void host_exerciser::host_exerciser_cmd::host_exerciser_errors () inline
Definition at line 91 of file host_exerciser_cmd.h.
References host_exerciser::HE_ERROR, host_exe_, opae::afu_test::afu::read64(), and host_exerciser::he_error::value.
Referenced by he_interrupt(), and he_wait_test_completion().
host_exerciser_swtestmsg()
uint64_t host_exerciser::host_exerciser_cmd::host_exerciser_swtestmsg () inline
Definition at line 104 of file host_exerciser_cmd.h.
References host_exerciser::HE_SWTEST_MSG, host_exe_, and opae::afu_test::afu::read64().
Referenced by he_compare_buffer().
cacheline_aligned_addr()
uint64_t host_exerciser::host_exerciser_cmd::cacheline_aligned_addr (uint64_t num) inline
Definition at line 119 of file host_exerciser_cmd.h.
References host_exerciser::LOG2_CL.
Referenced by run().
he_num_xfers_to_bw()
double host_exerciser::host_exerciser_cmd::he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks) inline
Definition at line 124 of file host_exerciser_cmd.h.
References host_exerciser::host_exerciser::he_clock_mhz_, and host_exe_.
Referenced by he_perf_counters(), and run_all_tests().
dsm_num_ticks()
uint64_t host_exerciser::host_exerciser_cmd::dsm_num_ticks (const volatile he_dsm_status * dsm_status) inline
Definition at line 129 of file host_exerciser_cmd.h.
References host_exerciser::he_dsm_status::num_ticks.
Referenced by he_perf_counters(), and run_all_tests().
dsm_num_reads()
uint64_t host_exerciser::host_exerciser_cmd::dsm_num_reads (const volatile he_dsm_status * dsm_status) inline
Definition at line 135 of file host_exerciser_cmd.h.
References host_exerciser::he_dsm_status::num_reads_h, and host_exerciser::he_dsm_status::num_reads_l.
Referenced by he_perf_counters(), and run_all_tests().
dsm_num_writes()
uint64_t host_exerciser::host_exerciser_cmd::dsm_num_writes (const volatile he_dsm_status * dsm_status) inline
Definition at line 141 of file host_exerciser_cmd.h.
References host_exerciser::he_dsm_status::num_writes_h, and host_exerciser::he_dsm_status::num_writes_l.
Referenced by he_perf_counters(), and run_all_tests().
he_perf_counters()
void host_exerciser::host_exerciser_cmd::he_perf_counters () inline
Definition at line 146 of file host_exerciser_cmd.h.
References host_exerciser::CL, dsm_, dsm_num_reads(), dsm_num_ticks(), dsm_num_writes(), host_exerciser::host_exerciser::he_continuousmode_, he_lpbk_cfg_, he_num_xfers_to_bw(), host_exe_, host_exerciser::HOST_EXEMODE_READ, host_exerciser::HOST_EXEMODE_WRITE, host_exerciser_status(), opae::afu_test::afu::logger_, and host_exerciser::LPBK1_BUFFER_SIZE.
Referenced by he_continuousmode(), and run_single_test().
he_interrupt()
bool host_exerciser::host_exerciser_cmd::he_interrupt (event::ptr_t ev) inline
Definition at line 189 of file host_exerciser_cmd.h.
References host_exerciser::host_exerciser::compare(), destination_, he_lpbk_cfg_, host_exe_, host_exerciser::HOST_EXEMODE_LPBK1, host_exerciser_errors(), host_exerciser::host_exerciser::interrupt_wait(), and source_.
Referenced by run_single_test().
he_wait_test_completion()
bool host_exerciser::host_exerciser_cmd::he_wait_test_completion () inline
Definition at line 204 of file host_exerciser_cmd.h.
References dsm_, host_exerciser::HELPBK_TEST_SLEEP_INVL, host_exerciser::HELPBK_TEST_TIMEOUT, host_exerciser_errors(), host_exerciser_status(), is_ase_sim_, and usleep().
Referenced by he_forcetestcmpl(), and run_single_test().
he_forcetestcmpl()
void host_exerciser::host_exerciser_cmd::he_forcetestcmpl () inline
Definition at line 227 of file host_exerciser_cmd.h.
References host_exerciser::HE_CTL, he_lpbk_ctl_, he_wait_test_completion(), host_exe_, usleep(), host_exerciser::he_ctl::value, and opae::afu_test::afu::write32().
Referenced by he_continuousmode().
he_init_src_buffer()
void host_exerciser::host_exerciser_cmd::he_init_src_buffer (shared_buffer::ptr_t buffer) inline
Definition at line 243 of file host_exerciser_cmd.h.
References host_exerciser::CL, host_exerciser::host_exerciser::fill(), he_lpbk_cfg_, host_exe_, host_exerciser::HOSTEXE_ATOMIC_CAS_4, host_exerciser::HOSTEXE_ATOMIC_CAS_8, and host_exerciser::HOSTEXE_ATOMIC_OFF.
Referenced by run(), and run_all_tests().
he_dump_buffer()
void host_exerciser::host_exerciser_cmd::he_dump_buffer (shared_buffer::ptr_t buffer, const char * msg) inline
Definition at line 273 of file host_exerciser_cmd.h.
References host_exerciser::CL.
Referenced by run_single_test().
he_compare_buffer()
uint64_t host_exerciser::host_exerciser_cmd::he_compare_buffer () inline
Definition at line 295 of file host_exerciser_cmd.h.
References host_exerciser::CL, destination_, he_lpbk_cfg_, host_exerciser::HOST_EXEMODE_LPBK1, host_exerciser_swtestmsg(), host_exerciser::HOSTEXE_ATOMIC_OFF, and source_.
Referenced by run_single_test().
he_continuousmode()
bool host_exerciser::host_exerciser_cmd::he_continuousmode () inline
Definition at line 376 of file host_exerciser_cmd.h.
References g_he_exit, host_exerciser::host_exerciser::he_continuousmode_, host_exerciser::host_exerciser::he_contmodetime_, he_forcetestcmpl(), he_perf_counters(), host_exe_, and opae::afu_test::afu::logger_.
Referenced by run_single_test().
set_cfg_reqlen() [1/2]
void host_exerciser::host_exerciser_cmd::set_cfg_reqlen (hostexe_req_len req_len) inline
Definition at line 396 of file host_exerciser_cmd.h.
References he_lpbk_cfg_.
Referenced by parse_input_options(), run_all_tests(), and set_cfg_reqlen().
set_cfg_reqlen() [2/2]
void host_exerciser::host_exerciser_cmd::set_cfg_reqlen (uint32_t req_len) inline
Definition at line 404 of file host_exerciser_cmd.h.
References set_cfg_reqlen().
get_cfg_reqlen()
hostexe_req_len host_exerciser::host_exerciser_cmd::get_cfg_reqlen () inline
Definition at line 409 of file host_exerciser_cmd.h.
References he_lpbk_cfg_.
Referenced by parse_input_options().
parse_input_options()
int host_exerciser::host_exerciser_cmd::parse_input_options () inline
Definition at line 415 of file host_exerciser_cmd.h.
References opae::fpga::types::properties::get(), get_cfg_reqlen(), host_exerciser::host_exerciser::he_continuousmode_, host_exerciser::host_exerciser::he_contmodetime_, host_exerciser::host_exerciser::he_delay_, host_exerciser::host_exerciser::he_interleave_, host_exerciser::host_exerciser::he_interrupt_, he_lpbk_api_ver_, he_lpbk_atomics_supported_, he_lpbk_cfg_, he_lpbk_max_reqlen_, host_exerciser::host_exerciser::he_modes_, host_exerciser::host_exerciser::he_req_atomic_func_, host_exerciser::host_exerciser::he_req_cls_len_, host_exerciser::host_exerciser::he_req_encoding_, host_exe_, host_exerciser::HOST_EXEMODE_LPBK1, host_exerciser::HOST_EXEMODE_TRPUT, host_exerciser::HOSTEXE_ATOMIC_OFF, host_exerciser::HOSTEXE_CLS_1, host_exerciser::HOSTEXE_ENCODING_DEFAULT, is_ase_sim_, host_exerciser::host_exerciser::option_passed(), set_cfg_reqlen(), and token_.
Referenced by run().
run_single_test()
int host_exerciser::host_exerciser_cmd::run_single_test () inline
Definition at line 503 of file host_exerciser_cmd.h.
References destination_, dsm_, host_exerciser::HE_CFG, he_compare_buffer(), he_continuousmode(), host_exerciser::host_exerciser::he_continuousmode_, host_exerciser::HE_CTL, he_dump_buffer(), he_interrupt(), host_exerciser::HE_INTERRUPT0, host_exerciser::host_exerciser::he_interrupt_, he_interrupt_, he_lpbk_cfg_, he_lpbk_ctl_, he_perf_counters(), he_wait_test_completion(), host_exe_, opae::afu_test::afu::logger_, host_exerciser::LPBK1_DSM_SIZE, host_exerciser::host_exerciser::register_interrupt(), source_, usleep(), host_exerciser::he_ctl::value, host_exerciser::he_cfg::value, host_exerciser::he_interrupt0::value, opae::afu_test::afu::write32(), and opae::afu_test::afu::write64().
Referenced by run(), and run_all_tests().
run_all_tests()
int host_exerciser::host_exerciser_cmd::run_all_tests () inline
Definition at line 600 of file host_exerciser_cmd.h.
References destination_, dsm_, dsm_num_reads(), dsm_num_ticks(), dsm_num_writes(), host_exerciser::host_exerciser::he_continuousmode_, host_exerciser::host_exerciser::he_contmodetime_, he_init_src_buffer(), he_lpbk_atomics_supported_, he_lpbk_cfg_, he_lpbk_max_reqlen_, he_num_xfers_to_bw(), host_exerciser::he_req_atomic_func, host_exerciser::he_req_cls_len, host_exe_, host_exerciser::HOST_EXEMODE_LPBK1, host_exerciser::HOST_EXEMODE_READ, host_exerciser::HOST_EXEMODE_TRPUT, host_exerciser::HOST_EXEMODE_WRITE, host_exerciser::HOSTEXE_ATOMIC_CAS_8, host_exerciser::HOSTEXE_ATOMIC_FADD_4, host_exerciser::HOSTEXE_ATOMIC_OFF, host_exerciser::HOSTEXE_CLS_1, host_exerciser::LPBK1_BUFFER_SIZE, run_single_test(), set_cfg_reqlen(), and source_.
Referenced by run().
run()
virtual int host_exerciser::host_exerciser_cmd::run (test_afu * afu, CLI::App * app) inline virtual
Implements opae::afu_test::command.
Definition at line 730 of file host_exerciser_cmd.h.
References app, cacheline_aligned_addr(), host_exerciser::CL, destination_, dsm_, host_exerciser::host_exerciser::he_clock_mhz_, host_exerciser::HE_CTL, host_exerciser::HE_DSM_BASEH, host_exerciser::HE_DSM_BASEL, host_exerciser::HE_DST_ADDR, host_exerciser::HE_INFO0, he_init_src_buffer(), he_lpbk_api_ver_, he_lpbk_atomics_supported_, he_lpbk_ctl_, he_lpbk_max_reqlen_, host_exerciser::HE_NUM_LINES, host_exerciser::HE_SRC_ADDR, host_exerciser::host_exerciser::he_test_all_, host_exe_, host_exerciser::HOSTEXE_CLS_16, host_exerciser::HOSTEXE_CLS_8, opae::afu_test::afu::logger_, host_exerciser::LPBK1_BUFFER_ALLOCATION_SIZE, host_exerciser::LPBK1_BUFFER_SIZE, host_exerciser::LPBK1_DSM_SIZE, parse_input_options(), opae::afu_test::afu::read64(), run_all_tests(), run_single_test(), source_, token_, usleep(), and host_exerciser::he_ctl::value.
Field Documentation
he_lpbk_cfg_
he_cfg host_exerciser::host_exerciser_cmd::he_lpbk_cfg_ protected
Definition at line 826 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), get_cfg_reqlen(), he_compare_buffer(), he_init_src_buffer(), he_interrupt(), he_perf_counters(), parse_input_options(), run_all_tests(), run_single_test(), and set_cfg_reqlen().
he_lpbk_ctl_
he_ctl host_exerciser::host_exerciser_cmd::he_lpbk_ctl_ protected
Definition at line 827 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), he_forcetestcmpl(), run(), and run_single_test().
host_exe_
host_exerciser* host_exerciser::host_exerciser_cmd::host_exe_ protected
Definition at line 828 of file host_exerciser_cmd.h.
Referenced by he_continuousmode(), he_forcetestcmpl(), he_init_src_buffer(), he_interrupt(), he_num_xfers_to_bw(), he_perf_counters(), host_exerciser_errors(), host_exerciser_status(), host_exerciser_swtestmsg(), parse_input_options(), run(), run_all_tests(), and run_single_test().
source_
shared_buffer::ptr_t host_exerciser::host_exerciser_cmd::source_ protected
Definition at line 829 of file host_exerciser_cmd.h.
Referenced by he_compare_buffer(), he_interrupt(), run(), run_all_tests(), and run_single_test().
destination_
shared_buffer::ptr_t host_exerciser::host_exerciser_cmd::destination_ protected
Definition at line 830 of file host_exerciser_cmd.h.
Referenced by he_compare_buffer(), he_interrupt(), run(), run_all_tests(), and run_single_test().
dsm_
shared_buffer::ptr_t host_exerciser::host_exerciser_cmd::dsm_ protected
Definition at line 831 of file host_exerciser_cmd.h.
Referenced by he_perf_counters(), he_wait_test_completion(), run(), run_all_tests(), and run_single_test().
he_interrupt_
he_interrupt0 host_exerciser::host_exerciser_cmd::he_interrupt_ protected
Definition at line 832 of file host_exerciser_cmd.h.
Referenced by run_single_test().
token_
token::ptr_t host_exerciser::host_exerciser_cmd::token_ protected
Definition at line 833 of file host_exerciser_cmd.h.
Referenced by parse_input_options(), and run().
he_lpbk_max_reqlen_
hostexe_req_len host_exerciser::host_exerciser_cmd::he_lpbk_max_reqlen_ protected
Definition at line 834 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), parse_input_options(), run(), and run_all_tests().
he_lpbk_api_ver_
uint8_t host_exerciser::host_exerciser_cmd::he_lpbk_api_ver_ protected
Definition at line 835 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), parse_input_options(), and run().
he_lpbk_atomics_supported_
bool host_exerciser::host_exerciser_cmd::he_lpbk_atomics_supported_ protected
Definition at line 836 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), parse_input_options(), run(), and run_all_tests().
is_ase_sim_
bool host_exerciser::host_exerciser_cmd::is_ase_sim_ protected
Definition at line 837 of file host_exerciser_cmd.h.
Referenced by host_exerciser_cmd(), he_wait_test_completion(), and parse_input_options().