OPAE C API: include/opae/event.h File Reference
event.h File Reference
Functions for registering events and managing the lifecycle for fpga_event_handles.
#include <opae/types.h>
Functions
fpga_result fpgaCreateEventHandle (fpga_event_handle *event_handle)
fpga_result fpgaDestroyEventHandle (fpga_event_handle *event_handle)
fpga_result fpgaGetOSObjectFromEventHandle (const fpga_event_handle eh, int *fd)
fpga_result fpgaRegisterEvent (fpga_handle handle, fpga_event_type event_type, fpga_event_handle event_handle, uint32_t flags)
fpga_result fpgaUnregisterEvent (fpga_handle handle, fpga_event_type event_type, fpga_event_handle event_handle)
Detailed Description
Functions for registering events and managing the lifecycle for fpga_event_handles.
OPAE provides an interface to asynchronous events that can be generated by different FPGA resources. The event API provides functions to register for these events; associated with every event a process has registered for is an fpga_event_handle, which encapsulates the OS-specific data structure for event objects. On Linux, an fpga_event_handle can be used as a file descriptor and passed to select(), poll(), epoll() and similar functions to wait for asynchronous events.
Definition in file event.h.
Function Documentation
fpgaCreateEventHandle()
fpga_result fpgaCreateEventHandle (fpga_event_handle * event_handle)
Initialize an event_handle
Platform independent way to initialize an event_handle used for notifications from the driver to application. For Linux, this function creates an eventfd and returns the eventfd file descriptor in *event_handle.
Parameters
[out] event_handle Pointer to event handle variable.
Returns
FPGA_OK on success. FPGA_INVALID_PARAM if event_handle is NULL. FPGA_NOT_SUPPORTED if platform does not support events.
Referenced by main().
fpgaDestroyEventHandle()
fpga_result fpgaDestroyEventHandle (fpga_event_handle * event_handle)
Destroy an event_handle
Destroy handle and free resources. On Linux this corresponds to closing the file descriptor pointed to by handle
Note
fpgaDestroyEventHandle() requires the address of an event_handle as created by fpgaCreateEventHandle(). Passing any other value results in undefined behavior.
Parameters
[in] event_handle Pointer to handle to be destroyed
Returns
FPGA_OK on success. FPGA_INVALID_PARAM if event_handle is NULL.
Referenced by main().
fpgaGetOSObjectFromEventHandle()
fpga_result fpgaGetOSObjectFromEventHandle (const fpga_event_handle eh, int * fd)
Get OS object from event handle
Check validity of event handle, and get the OS object used to subscribe and unsubscribe to events. On Linux, the object corresponds to a file descriptor.
Parameters
[in] eh Event handle to get the descriptor value from
[out] fd integer to store the descriptor value
Returns
FPGA_OK on success. FPGA_INVALID_PARAM if event_handle is invalid.
Referenced by main().
fpgaRegisterEvent()
fpga_result fpgaRegisterEvent (fpga_handle handle, fpga_event_type event_type, fpga_event_handle event_handle, uint32_t flags)
Register an FPGA event
This function tells the driver that the caller is interested in notification for the event specified by the type and flags pair.
The event_handle points to an OS specific mechanism for event notification. An event_handle is associated with only a single event.
In case of user interrupts, the flags parameter will be used to specify the vector ID. The value of the flags parameter indicates the vector ID, no bit encoding is used.
Parameters
[in] handle Handle to previously opened FPGA resource.
[in] event_type Type of event
[in] event_handle Handle to previously opened resource for event notification.
[in] flags Optional argument for specifying additional information about event. For example irq number for interrupt events.
Returns
FPGA_OK on success. FPGA_INVALID_PARAM if handle does not refer to a resource supporting the requested event, or if event_handle is not valid. FPGA_EXCEPTION if an internal exception occurred while accessing the handle or the event_handle. On Linux: FPGA_NO_DAEMON if the driver does not support the requested event and there is no FPGA Daemon (fpgad) running to proxy it.
Referenced by main().
fpgaUnregisterEvent()
fpga_result fpgaUnregisterEvent (fpga_handle handle, fpga_event_type event_type, fpga_event_handle event_handle)
Unregister an FPGA event
This function tells the driver that the caller is no longer interested in notification for the event associated with the event_handle
The event_handle points to an OS specific mechanism for event notification. An event_handle is associated with only a single event.
Parameters
[in] handle Handle to previously opened FPGA resource.
[in] event_type Type of event to unregister.
[in] event_handle Handle to previously registered resource for event notification.
Returns
FPGA_OK on success. FPGA_INVALID_PARAM if handle does not refer to a resource supporting the requested event, or if event_handle is not valid. FPGA_EXCEPTION if an internal error occurred accessing the handle or the event_handle.
Referenced by main().