OPAE C API: samples/cxl_host_exerciser/he_cache_test.h File Reference
he_cache_test.h File Reference
#include <future>
#include <glob.h>
#include <inttypes.h>
#include <numa.h>
#include <opae/cxx/core.h>
#include <regex.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <CLI/CLI.hpp>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
#include "fpga-dfl.h"
Data Structures
union opae::afu_test::pcie_address
class opae::afu_test::command
class opae::afu_test::afu
struct opae::afu_test::pcie_address.fields
Namespaces
opae
opae::afu_test
Macros
#define FEATURE_DEV
#define MAX_SIZE 256
#define MAX_HE_CACHE_DEVICE 2
#define PROTECTION (PROT_READ | PROT_WRITE)
#define MAP_HUGETLB 0x40000
#define MAP_HUGE_SHIFT 26
#define MAP_2M_HUGEPAGE (0x15 << MAP_HUGE_SHIFT) /* 2 ^ 0x15 = 2M */
#define MAP_1G_HUGEPAGE (0x1e << MAP_HUGE_SHIFT) /* 2 ^ 0x1e = 1G */
#define ADDR ((void *)(0x0UL))
#define FLAGS_4K (MAP_PRIVATE | MAP_ANONYMOUS)
#define FLAGS_2M (FLAGS_4K | MAP_2M_HUGEPAGE | MAP_HUGETLB)
#define FLAGS_1G (FLAGS_4K | MAP_1G_HUGEPAGE | MAP_HUGETLB)
#define KiB(x) ((x)*1024)
#define MiB(x) ((x)*1024 * 1024)
#define GiB(x) ((x)*1024 * 1024 * 1024)
#define DFL_CXL_CACHE_DSM_BASE 0x030
#define DFL_CXL_CACHE_WR_ADDR_TABLE_DATA 0x068
#define DFL_CXL_CACHE_RD_ADDR_TABLE_DATA 0x088
Enumerations
enum { MATCHES_SIZE = 6 }
Functions
bool buffer_allocate (void **addr, uint64_t len, uint32_t numa_node)
bool buffer_release (void *addr, uint64_t len)
bool sysfs_read_u64 (const char *path, uint64_t *value)
template<typename T >
bool opae::afu_test::parse_match_int (const char *s, regmatch_t m, T &v, int radix=10)
std::vector< std::string > opae::afu_test::spdlog_levels ()
Variables
const char * sbdf_pattern
Data Structure Documentation
opae::afu_test::pcie_address.fields
struct opae::afu_test::pcie_address.fields
Definition at line 187 of file he_cache_test.h.
Data Fields
uint32_t function: 3
uint32_t device: 5
uint32_t bus: 8
uint32_t domain: 16
Macro Definition Documentation
FEATURE_DEV
#define FEATURE_DEV
Value:
  "/sys/bus/pci/devices/%s/"                                                   \
  "fpga_region/region*/dfl-fme*/dfl_dev*/feature_id"
Definition at line 58 of file he_cache_test.h.
MAX_SIZE
#define MAX_SIZE 256
Definition at line 62 of file he_cache_test.h.
MAX_HE_CACHE_DEVICE
#define MAX_HE_CACHE_DEVICE 2
Definition at line 63 of file he_cache_test.h.
PROTECTION
#define PROTECTION (PROT_READ | PROT_WRITE)
Definition at line 65 of file he_cache_test.h.
MAP_HUGETLB
#define MAP_HUGETLB 0x40000
Definition at line 68 of file he_cache_test.h.
MAP_HUGE_SHIFT
#define MAP_HUGE_SHIFT 26
Definition at line 71 of file he_cache_test.h.
MAP_2M_HUGEPAGE
#define MAP_2M_HUGEPAGE (0x15 << MAP_HUGE_SHIFT) /* 2 ^ 0x15 = 2M */
Definition at line 74 of file he_cache_test.h.
MAP_1G_HUGEPAGE
#define MAP_1G_HUGEPAGE (0x1e << MAP_HUGE_SHIFT) /* 2 ^ 0x1e = 1G */
Definition at line 75 of file he_cache_test.h.
ADDR
#define ADDR ((void *)(0x0UL))
Definition at line 83 of file he_cache_test.h.
FLAGS_4K
#define FLAGS_4K (MAP_PRIVATE | MAP_ANONYMOUS)
Definition at line 84 of file he_cache_test.h.
FLAGS_2M
#define FLAGS_2M (FLAGS_4K | MAP_2M_HUGEPAGE | MAP_HUGETLB)
Definition at line 85 of file he_cache_test.h.
FLAGS_1G
#define FLAGS_1G (FLAGS_4K | MAP_1G_HUGEPAGE | MAP_HUGETLB)
Definition at line 86 of file he_cache_test.h.
KiB
#define KiB (x) ((x)*1024)
Definition at line 89 of file he_cache_test.h.
MiB
#define MiB (x) ((x)*1024 * 1024)
Definition at line 90 of file he_cache_test.h.
GiB
#define GiB (x) ((x)*1024 * 1024 * 1024)
Definition at line 91 of file he_cache_test.h.
DFL_CXL_CACHE_DSM_BASE
#define DFL_CXL_CACHE_DSM_BASE 0x030
Definition at line 93 of file he_cache_test.h.
DFL_CXL_CACHE_WR_ADDR_TABLE_DATA
#define DFL_CXL_CACHE_WR_ADDR_TABLE_DATA 0x068
Definition at line 94 of file he_cache_test.h.
DFL_CXL_CACHE_RD_ADDR_TABLE_DATA
#define DFL_CXL_CACHE_RD_ADDR_TABLE_DATA 0x088
Definition at line 95 of file he_cache_test.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MATCHES_SIZE
Definition at line 57 of file he_cache_test.h.
Function Documentation
buffer_allocate()
bool buffer_allocate (void ** addr, uint64_t len, uint32_t numa_node)
Definition at line 98 of file he_cache_test.h.
References ADDR, FLAGS_1G, FLAGS_2M, FLAGS_4K, KiB, MiB, and PROTECTION.
Referenced by opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_cache_read_write(), opae::afu_test::afu::allocate_cache_write(), and opae::afu_test::afu::allocate_dsm().
buffer_release()
bool buffer_release (void * addr, uint64_t len)
Definition at line 149 of file he_cache_test.h.
Referenced by opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_cache_read_write(), opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_cache_read_write(), opae::afu_test::afu::free_cache_write(), and opae::afu_test::afu::free_dsm().
sysfs_read_u64()
bool sysfs_read_u64 (const char * path, uint64_t * value)
Definition at line 158 of file he_cache_test.h.
Referenced by opae::afu_test::afu::find_dev_feature().
Variable Documentation
sbdf_pattern
const char* sbdf_pattern
Initial value:
=
    "(([0-9a-fA-F]{4}):)?([0-9a-fA-F]{2}):([0-9a-fA-F]{2})\\.([0-9])"
Definition at line 54 of file he_cache_test.h.
Referenced by opae::afu_test::pcie_address::parse().