OPAE C API: samples/hello_afu/sw/hello_afu.c File Reference
hello_afu.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <uuid/uuid.h>
#include <opae/enum.h>
#include <opae/access.h>
#include <opae/mmio.h>
#include <opae/properties.h>
#include <opae/utils.h>
#include "afu_json_info.h"
Data Structures
struct cache_line
Macros
#define UNUSED_PARAM(x) (void) x
#define HELLO_AFU_ID AFU_ACCEL_UUID
#define SCRATCH_REG 0X80
#define SCRATCH_VALUE 0x0123456789ABCDEF
#define SCRATCH_RESET 0
#define BYTE_OFFSET 8
#define AFU_DFH_REG 0x0
#define AFU_ID_LO 0x8
#define AFU_ID_HI 0x10
#define AFU_NEXT 0x18
#define AFU_RESERVED 0x20
#define ON_ERR_GOTO(res, label, desc)
#define ASSERT_GOTO(condition, label, desc)
Functions
int usleep (unsigned)
void print_err (const char *s, fpga_result res)
int main (int argc, char *argv[])
Variables
static int s_error_count = 0
Data Structure Documentation
cache_line
struct cache_line
Definition at line 85 of file hello_afu.c.
Data Fields
uint32_t uint[16]
Macro Definition Documentation
UNUSED_PARAM
#define UNUSED_PARAM (x) (void) x
Definition at line 40 of file hello_afu.c.
HELLO_AFU_ID
#define HELLO_AFU_ID AFU_ACCEL_UUID
Definition at line 44 of file hello_afu.c.
SCRATCH_REG
#define SCRATCH_REG 0X80
Definition at line 45 of file hello_afu.c.
SCRATCH_VALUE
#define SCRATCH_VALUE 0x0123456789ABCDEF
Definition at line 46 of file hello_afu.c.
SCRATCH_RESET
#define SCRATCH_RESET 0
Definition at line 47 of file hello_afu.c.
BYTE_OFFSET
#define BYTE_OFFSET 8
Definition at line 48 of file hello_afu.c.
AFU_DFH_REG
#define AFU_DFH_REG 0x0
Definition at line 50 of file hello_afu.c.
AFU_ID_LO
#define AFU_ID_LO 0x8
Definition at line 51 of file hello_afu.c.
AFU_ID_HI
#define AFU_ID_HI 0x10
Definition at line 52 of file hello_afu.c.
AFU_NEXT
#define AFU_NEXT 0x18
Definition at line 53 of file hello_afu.c.
AFU_RESERVED
#define AFU_RESERVED 0x20
Definition at line 54 of file hello_afu.c.
ON_ERR_GOTO
#define ON_ERR_GOTO (res, label, desc)
Value:
   do {                                       \
      if ((res) != FPGA_OK) {            \
         print_err((desc), (res));  \
         s_error_count += 1; \
         goto label;                \
      }                                  \
   } while (0)
Definition at line 62 of file hello_afu.c.
ASSERT_GOTO
#define ASSERT_GOTO (condition, label, desc)
Value:
   do {                                       \
      if ((condition) == 0) {            \
         fprintf(stderr, "Error %s\n", desc); \
         s_error_count += 1; \
         goto label;                \
      }                                  \
   } while (0)
Definition at line 75 of file hello_afu.c.
Function Documentation
usleep()
int usleep (unsigned)
Referenced by hssi_cmd::enable_eth_loopback(), fpga_start(), fpga_stop(), host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::host_exerciser_cmd::he_forcetestcmpl(), host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::host_exerciser_cmd::he_wait_test_completion(), main(), host_exerciser::host_exerciser_cmd::run(), and host_exerciser::host_exerciser_cmd::run_single_test().
print_err()
void print_err (const char * s, fpga_result res)
Definition at line 89 of file hello_afu.c.
References fpgaErrStr().
main()
int main (int argc, char * argv[])
Definition at line 94 of file hello_afu.c.
References AFU_DFH_REG, AFU_ID_HI, AFU_ID_LO, AFU_NEXT, AFU_RESERVED, ASSERT_GOTO, FPGA_ACCELERATOR, FPGA_INVALID_PARAM, FPGA_OK, fpgaClose(), fpgaDestroyProperties(), fpgaDestroyToken(), fpgaEnumerate(), fpgaGetProperties(), fpgaMapMMIO(), fpgaOpen(), fpgaPropertiesSetGUID(), fpgaPropertiesSetObjectType(), fpgaReadMMIO64(), fpgaReset(), fpgaUnmapMMIO(), fpgaWriteMMIO64(), HELLO_AFU_ID, ON_ERR_GOTO, s_error_count, SCRATCH_REG, SCRATCH_RESET, SCRATCH_VALUE, and UNUSED_PARAM.
Variable Documentation
s_error_count
int s_error_count = 0 static
Definition at line 56 of file hello_afu.c.
Referenced by main().