OPAE C API: samples/hello_events/hello_events.c File Reference
hello_events.c File Reference
A code sample of using OPAE event API.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <poll.h>
#include <errno.h>
#include <sys/stat.h>
#include <pthread.h>
#include <opae/fpga.h>
#include <argsfilter.h>
#include "mock/opae_std.h"
Data Structures
struct ras_inject_error
union ras_inject_error.__unnamed88__
struct ras_inject_error.__unnamed88__.__unnamed90__
Macros
#define FME_SYSFS_INJECT_ERROR "errors/inject_errors"
#define ON_ERR_GOTO(res, label, desc)
#define GETOPT_STRING "hv"
Functions
int usleep (unsigned)
void print_err (const char *s, fpga_result res)
fpga_result inject_ras_fatal_error (fpga_token fme_token, uint8_t err)
void * error_thread (void *arg)
void help (void)
fpga_result parse_args (int argc, char *argv[])
fpga_result find_fpga (fpga_properties device_filter, fpga_token *fpga, uint32_t *num_matches)
int main (int argc, char *argv[])
Detailed Description
A code sample of using OPAE event API.
This sample starts two processes. One process injects an artificial fatal error to sysfs; while the other tries to asynchronously capture and handle the event. This sample code exercises all major functions of the event API, including creating and destroying event handles, register and unregister events, polling on event file descriptor, and getting the OS object associated with an event. For a full discussion of OPAE event API, refer to event.h.
Definition in file hello_events.c.
Data Structure Documentation
ras_inject_error
struct ras_inject_error
Definition at line 76 of file hello_events.c.
Data Fields
union ras_inject_error __unnamed__
ras_inject_error.__unnamed88__
union ras_inject_error.__unnamed88__
Definition at line 77 of file hello_events.c.
Data Fields
uint64_t csr
__unnamed88__ __unnamed__
ras_inject_error.__unnamed88__.__unnamed90__
struct ras_inject_error.__unnamed88__.__unnamed90__
Definition at line 79 of file hello_events.c.
Data Fields
uint64_t catastrophicr_error: 1
uint64_t fatal_error: 1
uint64_t nonfatal_error: 1
uint64_t rsvd: 61
Macro Definition Documentation
FME_SYSFS_INJECT_ERROR
#define FME_SYSFS_INJECT_ERROR "errors/inject_errors"
Definition at line 60 of file hello_events.c.
ON_ERR_GOTO
#define ON_ERR_GOTO (res, label, desc)
Value:
   do {                                       \
      if ((res) != FPGA_OK) {            \
         print_err((desc), (res));  \
         goto label;                \
      }                                  \
   } while (0)
Definition at line 62 of file hello_events.c.
GETOPT_STRING
#define GETOPT_STRING "hv"
Definition at line 164 of file hello_events.c.
Function Documentation
usleep()
int usleep (unsigned)
Referenced by error_thread().
print_err()
void print_err (const char * s, fpga_result res)
Definition at line 70 of file hello_events.c.
References fpgaErrStr().
Referenced by error_thread(), and main().
inject_ras_fatal_error()
fpga_result inject_ras_fatal_error (fpga_token fme_token, uint8_t err)
Definition at line 92 of file hello_events.c.
References FME_SYSFS_INJECT_ERROR, FPGA_OK, FPGA_OPEN_SHARED, fpgaClose(), fpgaDestroyObject(), fpgaHandleGetObject(), fpgaObjectWrite64(), fpgaOpen(), ON_ERR_GOTO, and OPAE_ERR.
Referenced by error_thread().
error_thread()
void* error_thread (void * arg)
Definition at line 127 of file hello_events.c.
References FPGA_OK, inject_ras_fatal_error(), print_err(), and usleep().
Referenced by main().
help()
void help (void)
Definition at line 147 of file hello_events.c.
Referenced by parse_args().
parse_args()
fpga_result parse_args (int argc, char * argv[])
Definition at line 165 of file hello_events.c.
References FPGA_EXCEPTION, FPGA_OK, GETOPT_STRING, and help().
Referenced by main().
find_fpga()
fpga_result find_fpga (fpga_properties device_filter, fpga_token * fpga, uint32_t * num_matches)
Definition at line 204 of file hello_events.c.
References FPGA_DEVICE, FPGA_OK, fpgaCloneProperties(), fpgaDestroyProperties(), fpgaEnumerate(), fpgaPropertiesSetObjectType(), and ON_ERR_GOTO.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 228 of file hello_events.c.
References error_thread(), find_fpga(), FPGA_EVENT_ERROR, FPGA_EXCEPTION, FPGA_NOT_FOUND, FPGA_OK, FPGA_OPEN_SHARED, fpgaClose(), fpgaCreateEventHandle(), fpgaDestroyEventHandle(), fpgaDestroyProperties(), fpgaDestroyToken(), fpgaGetOSObjectFromEventHandle(), fpgaGetProperties(), fpgaOpen(), fpgaRegisterEvent(), fpgaUnregisterEvent(), ON_ERR_GOTO, parse_args(), and print_err().