OPAE C API: samples/n5010-ctl/n5010-ctl.c File Reference
n5010-ctl.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <error.h>
#include <time.h>
#include <signal.h>
#include <getopt.h>
#include <opae/fpga.h>
#include <uuid/uuid.h>
#include <endian.h>
#include "argsfilter.h"
Data Structures
struct n5010_test
struct n5010
Macros
#define DFH_EOL(h) ((h >> 40) & 1)
#define DFH_NEXT(h) ((h >> 16) & 0xffffff)
#define DFH_TYPE(h) ((h >> 60) & 0xf)
#define DFH_TYPE_AFU 1
#define MAX_PORT 3
#define INVALID_PORT (MAX_PORT + 1)
#define CVL0_QSFP01_SWITCH 0x28
#define CVL1_QSFP23_SWITCH 0x30
Functions
void signal_callback_handler (int signum)
static fpga_result fpga_setread_switch (struct n5010 *n5010)
static fpga_result fpga_read_switch (struct n5010 *n5010)
static fpga_result fpga_run (struct n5010 *n5010)
static fpga_result fpga_open (struct n5010 *n5010)
static void fpga_close (struct n5010 *n5010)
static fpga_result fpga_base (struct n5010 *n5010)
static void fpga_dump (struct n5010 *n5010, uint64_t offset, size_t count)
static fpga_result fpga_set_switch (struct n5010 *n5010)
static fpga_result fpga_read_switch_port (struct n5010 *n5010, uint32_t cvl)
static fpga_result fpga_run (__attribute__((unused)) struct n5010 *n5010)
static void print_usage (FILE *f)
static bool parse_port (struct n5010 *n5010, const char *port_str)
static bool parse_mode (struct n5010 *n5010, const char *mode)
static int parse_args (int argc, char **argv, struct n5010 *n5010)
int main (int argc, char **argv)
Variables
char const * default_guid = "c48d4e2a-9121-497d-adc7-3640729ec6f7"
static volatile bool stop = false
static const struct n5010_test n5010_test []
Data Structure Documentation
n5010
struct n5010
Definition at line 76 of file n5010-ctl.c.
Data Fields
fpga_properties filter
fpga_token token
fpga_handle handle
fpga_guid guid
uint64_t base
const struct n5010_test * test
uint64_t port
bool debug
uint open_mode
Macro Definition Documentation
DFH_EOL
#define DFH_EOL (h) ((h >> 40) & 1)
Definition at line 43 of file n5010-ctl.c.
DFH_NEXT
#define DFH_NEXT (h) ((h >> 16) & 0xffffff)
Definition at line 44 of file n5010-ctl.c.
DFH_TYPE
#define DFH_TYPE (h) ((h >> 60) & 0xf)
Definition at line 45 of file n5010-ctl.c.
DFH_TYPE_AFU
#define DFH_TYPE_AFU 1
Definition at line 46 of file n5010-ctl.c.
MAX_PORT
#define MAX_PORT 3
Definition at line 48 of file n5010-ctl.c.
INVALID_PORT
#define INVALID_PORT (MAX_PORT + 1)
Definition at line 49 of file n5010-ctl.c.
CVL0_QSFP01_SWITCH
#define CVL0_QSFP01_SWITCH 0x28
Definition at line 50 of file n5010-ctl.c.
CVL1_QSFP23_SWITCH
#define CVL1_QSFP23_SWITCH 0x30
Definition at line 51 of file n5010-ctl.c.
Function Documentation
signal_callback_handler()
void signal_callback_handler (int signum)
Definition at line 58 of file n5010-ctl.c.
References stop.
Referenced by main().
fpga_setread_switch()
static fpga_result fpga_setread_switch (struct n5010 * n5010) static
Definition at line 305 of file n5010-ctl.c.
References fpga_read_switch(), fpga_set_switch(), INVALID_PORT, and n5010::port.
fpga_read_switch()
static fpga_result fpga_read_switch (struct n5010 * n5010) static
Definition at line 298 of file n5010-ctl.c.
References fpga_read_switch_port().
Referenced by fpga_setread_switch().
fpga_run() [1/2]
static fpga_result fpga_run (struct n5010 * n5010) static
fpga_open()
static fpga_result fpga_open (struct n5010 * n5010) static
Definition at line 107 of file n5010-ctl.c.
References n5010::filter, FPGA_ACCELERATOR, FPGA_NOT_FOUND, FPGA_OK, FPGA_OPEN_SHARED, fpgaClose(), fpgaEnumerate(), fpgaErrStr(), fpgaMapMMIO(), fpgaOpen(), fpgaPropertiesSetGUID(), fpgaPropertiesSetObjectType(), n5010::guid, n5010::handle, and n5010::token.
Referenced by main().
fpga_close()
static void fpga_close (struct n5010 * n5010) static
Definition at line 156 of file n5010-ctl.c.
References FPGA_OK, fpgaClose(), fpgaDestroyToken(), fpgaErrStr(), fpgaUnmapMMIO(), n5010::handle, and n5010::token.
Referenced by main().
fpga_base()
static fpga_result fpga_base (struct n5010 * n5010) static
Definition at line 180 of file n5010-ctl.c.
References n5010::base, DFH_EOL, DFH_NEXT, DFH_TYPE, DFH_TYPE_AFU, FPGA_NOT_FOUND, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), n5010::guid, and n5010::handle.
Referenced by main().
fpga_dump()
static void fpga_dump (struct n5010 * n5010, uint64_t offset, size_t count) static
Definition at line 246 of file n5010-ctl.c.
References n5010::base, n5010::debug, fpgaReadMMIO64(), and n5010::handle.
Referenced by main().
fpga_set_switch()
static fpga_result fpga_set_switch (struct n5010 * n5010) static
Definition at line 263 of file n5010-ctl.c.
References n5010::base, CVL0_QSFP01_SWITCH, CVL1_QSFP23_SWITCH, FPGA_OK, fpgaErrStr(), fpgaWriteMMIO64(), n5010::handle, and n5010::port.
Referenced by fpga_setread_switch().
fpga_read_switch_port()
static fpga_result fpga_read_switch_port (struct n5010 * n5010, uint32_t cvl) static
Definition at line 285 of file n5010-ctl.c.
References n5010::base, CVL0_QSFP01_SWITCH, CVL1_QSFP23_SWITCH, fpgaReadMMIO64(), and n5010::handle.
Referenced by fpga_read_switch().
fpga_run() [2/2]
static fpga_result fpga_run (__attribute__((unused)) struct n5010 * n5010) static
Definition at line 319 of file n5010-ctl.c.
References stop.
print_usage()
static void print_usage (FILE * f) static
Definition at line 328 of file n5010-ctl.c.
References default_guid.
Referenced by parse_args().
parse_port()
static bool parse_port (struct n5010 * n5010, const char * port_str) static
Definition at line 344 of file n5010-ctl.c.
References MAX_PORT, and n5010::port.
Referenced by parse_args().
parse_mode()
static bool parse_mode (struct n5010 * n5010, const char * mode) static
Definition at line 362 of file n5010-ctl.c.
References n5010_test, n5010_test::name, and n5010::test.
Referenced by parse_args().
parse_args()
static int parse_args (int argc, char ** argv, struct n5010 * n5010) static
Definition at line 385 of file n5010-ctl.c.
References n5010::debug, default_guid, n5010::guid, INVALID_PORT, options, parse_mode(), parse_port(), n5010::port, and print_usage().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 440 of file n5010-ctl.c.
References n5010::filter, fpga_base(), fpga_close(), fpga_dump(), FPGA_EXCEPTION, FPGA_OK, fpga_open(), fpgaDestroyProperties(), fpgaErrStr(), fpgaGetProperties(), n5010_test::func, n5010_test, parse_args(), signal_callback_handler(), and n5010::test.
Variable Documentation
default_guid
char const* default_guid = "c48d4e2a-9121-497d-adc7-3640729ec6f7"
Definition at line 53 of file n5010-ctl.c.
Referenced by parse_args(), and print_usage().
stop
volatile bool stop = false static
Definition at line 57 of file n5010-ctl.c.
Referenced by fpga_run(), and signal_callback_handler().
n5010_test
const struct n5010_test n5010_test[] static
Initial value:
= {
   {
      .name = "setsw",
      .func = fpga_setread_switch,
   },
   {
      .name = "readsw",
      .func = fpga_read_switch,
   },
   {
      .name = "runsw",
      .func = fpga_run,
   },
}
Definition at line 89 of file n5010-ctl.c.
Referenced by main(), and parse_mode().