OPAE C API: samples/n5010-test/n5010-test.c File Reference
n5010-test.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <error.h>
#include <time.h>
#include <getopt.h>
#include <opae/fpga.h>
#include <uuid/uuid.h>
#include <endian.h>
#include <argsfilter.h>
Data Structures
struct n5010_test
struct n5010
Macros
#define DFH_EOL(h) ((h >> 40) & 1)
#define DFH_NEXT(h) ((h >> 16) & 0xffffff)
#define DFH_TYPE(h) ((h >> 60) & 0xf)
#define DFH_TYPE_AFU 1
#define DDR_TEST_MODE0_CTRL 0x3000
#define DDR_TEST_MODE0_STAT 0x3008
#define DDR_TEST_MODE1_CTRL 0x3000
#define DDR_TEST_MODE1_STAT 0x3008
#define DDR_TEST_MODE1_BANK_STAT(x) (0x3010 + 8 * x)
#define HBM_TEST_PASS 0x4000
#define HBM_TEST_FAIL 0x4008
#define HBM_TEST_TIMEOUT 0x4010
#define HBM_TEST_CTRL 0x4018
#define QDR_TEST_STAT 0x5000
#define QDR_FM 0xff
#define QDR_TEST_TIMEOUT(h) ((h >> 16) & QDR_FM)
#define QDR_TEST_FAIL(h) ((h >> 8) & QDR_FM)
#define QDR_TEST_PASS(h) ((h >> 0) & QDR_FM)
#define QDR_TEST_CTRL 0x5008
#define ESRAM_TEST_STAT 0x6000
#define ESRAM_FM 0xffff
#define ESRAM_TEST_TIMEOUT(h) ((h >> 32) & ESRAM_FM)
#define ESRAM_TEST_FAIL(h) ((h >> 16) & ESRAM_FM)
#define ESRAM_TEST_PASS(h) ((h >> 0) & ESRAM_FM)
#define ESRAM_TEST_CTRL 0x6008
#define MAX_POLLS 10
Functions
static fpga_result fpga_test_ddr_directed (struct n5010 *n5010)
static fpga_result fpga_test_ddr_prbs (struct n5010 *n5010)
static fpga_result fpga_test_hbm (struct n5010 *n5010)
static fpga_result fpga_test_esram (struct n5010 *n5010)
static fpga_result fpga_test_qdr (struct n5010 *n5010)
static fpga_result fpga_open (struct n5010 *n5010)
static void fpga_close (struct n5010 *n5010)
static fpga_result fpga_base (struct n5010 *n5010)
static void fpga_dump (struct n5010 *n5010, uint64_t offset, size_t count)
static fpga_result fpga_banks (struct n5010 *n5010, uint64_t offset, uint64_t *num_banks)
static fpga_result fpga_start (struct n5010 *n5010, uint64_t offset, uint64_t num_banks)
static fpga_result fpga_stop (struct n5010 *n5010, uint64_t offset)
static fpga_result fpga_wait (struct n5010 *n5010, uint64_t offset, uint64_t init, uint64_t result)
static void print_usage (FILE *f)
static bool parse_mode (struct n5010 *n5010, const char *mode)
static fpga_result parse_args (int argc, char **argv, struct n5010 *n5010)
int main (int argc, char **argv)
Variables
static const struct n5010_test n5010_test []
Data Structure Documentation
n5010
struct n5010
Definition at line 76 of file n5010-ctl.c.
Data Fields
fpga_properties filter
fpga_token token
fpga_handle handle
fpga_guid guid
uint64_t base
const struct n5010_test * test
uint64_t port
bool debug
uint open_mode
Macro Definition Documentation
DFH_EOL
#define DFH_EOL (h) ((h >> 40) & 1)
Definition at line 43 of file n5010-test.c.
DFH_NEXT
#define DFH_NEXT (h) ((h >> 16) & 0xffffff)
Definition at line 44 of file n5010-test.c.
DFH_TYPE
#define DFH_TYPE (h) ((h >> 60) & 0xf)
Definition at line 45 of file n5010-test.c.
DFH_TYPE_AFU
#define DFH_TYPE_AFU 1
Definition at line 46 of file n5010-test.c.
DDR_TEST_MODE0_CTRL
#define DDR_TEST_MODE0_CTRL 0x3000
Definition at line 48 of file n5010-test.c.
DDR_TEST_MODE0_STAT
#define DDR_TEST_MODE0_STAT 0x3008
Definition at line 49 of file n5010-test.c.
DDR_TEST_MODE1_CTRL
#define DDR_TEST_MODE1_CTRL 0x3000
Definition at line 51 of file n5010-test.c.
DDR_TEST_MODE1_STAT
#define DDR_TEST_MODE1_STAT 0x3008
Definition at line 52 of file n5010-test.c.
DDR_TEST_MODE1_BANK_STAT
#define DDR_TEST_MODE1_BANK_STAT (x) (0x3010 + 8 * x)
Definition at line 53 of file n5010-test.c.
HBM_TEST_PASS
#define HBM_TEST_PASS 0x4000
Definition at line 55 of file n5010-test.c.
HBM_TEST_FAIL
#define HBM_TEST_FAIL 0x4008
Definition at line 56 of file n5010-test.c.
HBM_TEST_TIMEOUT
#define HBM_TEST_TIMEOUT 0x4010
Definition at line 57 of file n5010-test.c.
HBM_TEST_CTRL
#define HBM_TEST_CTRL 0x4018
Definition at line 58 of file n5010-test.c.
QDR_TEST_STAT
#define QDR_TEST_STAT 0x5000
Definition at line 60 of file n5010-test.c.
QDR_FM
#define QDR_FM 0xff
Definition at line 61 of file n5010-test.c.
QDR_TEST_TIMEOUT
#define QDR_TEST_TIMEOUT (h) ((h >> 16) & QDR_FM)
Definition at line 62 of file n5010-test.c.
QDR_TEST_FAIL
#define QDR_TEST_FAIL (h) ((h >> 8) & QDR_FM)
Definition at line 63 of file n5010-test.c.
QDR_TEST_PASS
#define QDR_TEST_PASS (h) ((h >> 0) & QDR_FM)
Definition at line 64 of file n5010-test.c.
QDR_TEST_CTRL
#define QDR_TEST_CTRL 0x5008
Definition at line 66 of file n5010-test.c.
ESRAM_TEST_STAT
#define ESRAM_TEST_STAT 0x6000
Definition at line 68 of file n5010-test.c.
ESRAM_FM
#define ESRAM_FM 0xffff
Definition at line 69 of file n5010-test.c.
ESRAM_TEST_TIMEOUT
#define ESRAM_TEST_TIMEOUT (h) ((h >> 32) & ESRAM_FM)
Definition at line 70 of file n5010-test.c.
ESRAM_TEST_FAIL
#define ESRAM_TEST_FAIL (h) ((h >> 16) & ESRAM_FM)
Definition at line 71 of file n5010-test.c.
ESRAM_TEST_PASS
#define ESRAM_TEST_PASS (h) ((h >> 0) & ESRAM_FM)
Definition at line 72 of file n5010-test.c.
ESRAM_TEST_CTRL
#define ESRAM_TEST_CTRL 0x6008
Definition at line 74 of file n5010-test.c.
MAX_POLLS
#define MAX_POLLS 10
Definition at line 76 of file n5010-test.c.
Function Documentation
fpga_test_ddr_directed()
static fpga_result fpga_test_ddr_directed (struct n5010 * n5010) static
Definition at line 415 of file n5010-test.c.
References n5010::base, DDR_TEST_MODE0_CTRL, DDR_TEST_MODE0_STAT, fpga_banks(), fpga_dump(), FPGA_EXCEPTION, FPGA_OK, fpga_start(), fpga_stop(), fpga_wait(), fpgaErrStr(), fpgaReadMMIO64(), and n5010::handle.
fpga_test_ddr_prbs()
static fpga_result fpga_test_ddr_prbs (struct n5010 * n5010) static
Definition at line 365 of file n5010-test.c.
References n5010::base, DDR_TEST_MODE1_BANK_STAT, DDR_TEST_MODE1_CTRL, DDR_TEST_MODE1_STAT, fpga_banks(), fpga_dump(), FPGA_EXCEPTION, FPGA_OK, fpga_start(), fpga_stop(), fpga_wait(), fpgaErrStr(), fpgaReadMMIO64(), and n5010::handle.
fpga_test_hbm()
static fpga_result fpga_test_hbm (struct n5010 * n5010) static
Definition at line 626 of file n5010-test.c.
References n5010::base, n5010::debug, FPGA_EXCEPTION, FPGA_OK, fpga_start(), fpgaErrStr(), fpgaReadMMIO64(), n5010::handle, HBM_TEST_CTRL, HBM_TEST_FAIL, HBM_TEST_PASS, and HBM_TEST_TIMEOUT.
fpga_test_esram()
static fpga_result fpga_test_esram (struct n5010 * n5010) static
Definition at line 476 of file n5010-test.c.
References n5010::base, n5010::debug, ESRAM_FM, ESRAM_TEST_CTRL, ESRAM_TEST_FAIL, ESRAM_TEST_PASS, ESRAM_TEST_STAT, ESRAM_TEST_TIMEOUT, FPGA_EXCEPTION, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), fpgaWriteMMIO64(), n5010::handle, and MAX_POLLS.
fpga_test_qdr()
static fpga_result fpga_test_qdr (struct n5010 * n5010) static
Definition at line 551 of file n5010-test.c.
References n5010::base, n5010::debug, FPGA_EXCEPTION, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), fpgaWriteMMIO64(), n5010::handle, MAX_POLLS, QDR_FM, QDR_TEST_CTRL, QDR_TEST_FAIL, QDR_TEST_PASS, QDR_TEST_STAT, and QDR_TEST_TIMEOUT.
fpga_open()
static fpga_result fpga_open (struct n5010 * n5010) static
Definition at line 125 of file n5010-test.c.
References n5010::filter, FPGA_ACCELERATOR, FPGA_NOT_FOUND, FPGA_OK, fpgaEnumerate(), fpgaErrStr(), fpgaMapMMIO(), fpgaOpen(), fpgaPropertiesSetGUID(), fpgaPropertiesSetObjectType(), fpgaReset(), n5010::guid, n5010::handle, n5010::open_mode, and n5010::token.
Referenced by main().
fpga_close()
static void fpga_close (struct n5010 * n5010) static
Definition at line 175 of file n5010-test.c.
References n5010::filter, FPGA_OK, fpgaClose(), fpgaDestroyProperties(), fpgaDestroyToken(), fpgaErrStr(), fpgaUnmapMMIO(), n5010::handle, and n5010::token.
Referenced by main(), and parse_args().
fpga_base()
static fpga_result fpga_base (struct n5010 * n5010) static
Definition at line 202 of file n5010-test.c.
References n5010::base, DFH_EOL, DFH_NEXT, DFH_TYPE, DFH_TYPE_AFU, FPGA_NOT_FOUND, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), n5010::guid, and n5010::handle.
Referenced by main().
fpga_dump()
static void fpga_dump (struct n5010 * n5010, uint64_t offset, size_t count) static
Definition at line 258 of file n5010-test.c.
References n5010::base, n5010::debug, fpgaReadMMIO64(), and n5010::handle.
Referenced by fpga_start(), fpga_stop(), fpga_test_ddr_directed(), fpga_test_ddr_prbs(), and main().
fpga_banks()
static fpga_result fpga_banks (struct n5010 * n5010, uint64_t offset, uint64_t * num_banks) static
Definition at line 274 of file n5010-test.c.
References n5010::base, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), and n5010::handle.
Referenced by fpga_test_ddr_directed(), and fpga_test_ddr_prbs().
fpga_start()
static fpga_result fpga_start (struct n5010 * n5010, uint64_t offset, uint64_t num_banks) static
Definition at line 288 of file n5010-test.c.
References n5010::base, fpga_dump(), FPGA_OK, fpgaErrStr(), fpgaWriteMMIO64(), n5010::handle, and usleep().
Referenced by fpga_test_ddr_directed(), fpga_test_ddr_prbs(), and fpga_test_hbm().
fpga_stop()
static fpga_result fpga_stop (struct n5010 * n5010, uint64_t offset) static
Definition at line 312 of file n5010-test.c.
References n5010::base, fpga_dump(), FPGA_OK, fpgaErrStr(), fpgaWriteMMIO64(), n5010::handle, and usleep().
Referenced by fpga_test_ddr_directed(), and fpga_test_ddr_prbs().
fpga_wait()
static fpga_result fpga_wait (struct n5010 * n5010, uint64_t offset, uint64_t init, uint64_t result) static
Definition at line 334 of file n5010-test.c.
References n5010::base, n5010::debug, FPGA_EXCEPTION, FPGA_OK, fpgaErrStr(), fpgaReadMMIO64(), and n5010::handle.
Referenced by fpga_test_ddr_directed(), and fpga_test_ddr_prbs().
print_usage()
static void print_usage (FILE * f) static
Definition at line 692 of file n5010-test.c.
Referenced by parse_args().
parse_mode()
static bool parse_mode (struct n5010 * n5010, const char * mode) static
Definition at line 713 of file n5010-test.c.
References n5010_test, n5010_test::name, and n5010::test.
Referenced by parse_args().
parse_args()
static fpga_result parse_args (int argc, char ** argv, struct n5010 * n5010) static
Definition at line 736 of file n5010-test.c.
References n5010::debug, n5010::filter, fpga_close(), FPGA_EXCEPTION, FPGA_OK, FPGA_OPEN_SHARED, fpgaErrStr(), fpgaGetProperties(), n5010::guid, n5010::open_mode, options, parse_mode(), and print_usage().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 807 of file n5010-test.c.
References fpga_base(), fpga_close(), fpga_dump(), FPGA_OK, fpga_open(), n5010_test::func, parse_args(), and n5010::test.
Variable Documentation
n5010_test
const struct n5010_test n5010_test[] static
Initial value:
= {
   {
      .name = "hbm",
      .func = fpga_test_hbm,
   },
   {
      .name = "ddr-directed",
      .func = fpga_test_ddr_directed,
   },
   {
      .name = "ddr-prbs",
      .func = fpga_test_ddr_prbs,
   },
   {
      .name = "esram",
      .func = fpga_test_esram,
   },
   {
      .name = "qdr",
      .func = fpga_test_qdr,
   }
}
Definition at line 100 of file n5010-test.c.
Referenced by parse_mode().