OPAE C API: samples/object_api/object_api.c File Reference
object_api.c File Reference
A code sample illustrates the basic usage of the OPAE C Object API.
#include <opae/fpga.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <string.h>
#include <argsfilter.h>
#include "mock/opae_std.h"
Data Structures
struct named_object
struct metric_group
struct token_group
struct config
Macros
#define ON_ERR_GOTO(res, label, desc)
#define MAX_CLEANUP 100
#define ADD_TO_CLEANUP(func, p)
#define MAX_TOKENS 4
#define MAX_GROUP_OBJECTS 32
#define GETOPT_STRING "hv"
#define USEC_TO_SEC 1000000
Typedefs
typedef fpga_result(* destroy_f) (void *p)
Functions
void print_err (const char *s, fpga_result res)
metric_group * init_metric_group (fpga_token token, const char *name, metric_group *group)
fpga_result add_clock (token_group *t_group)
fpga_result add_counter (metric_group *group, const char *name)
void print_counters (fpga_object clock, metric_group *group)
void help (void)
fpga_result parse_args (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
struct {
destroy_f fn
void * param
} cleanup [100]
STATIC int cleanup_size
struct config options = { 1.0 }
Detailed Description
A code sample illustrates the basic usage of the OPAE C Object API.
Definition in file object_api.c.
Data Structure Documentation
named_object
struct named_object
Definition at line 77 of file object_api.c.
Data Fields
const char * name
fpga_object object
uint64_t value
uint64_t delta
metric_group
struct metric_group
Definition at line 84 of file object_api.c.
Data Fields
const char * name
fpga_token token
fpga_object object
uint8_t bus
uint8_t device
uint8_t function
named_object objects[32]
size_t count
token_group
struct token_group
Definition at line 95 of file object_api.c.
Data Fields
fpga_token token
metric_group * groups
size_t count
fpga_object clock
config
struct config
Definition at line 129 of file hello_fpga.c.
Data Fields
int open_flags
int run_n3000
float interval_sec
Macro Definition Documentation
ON_ERR_GOTO
#define ON_ERR_GOTO (res, label, desc)
Value:
   do {                                                                   \
      if ((res) != FPGA_OK) {                                        \
         print_err((desc), (res));                              \
         goto label;                                            \
      }                                                              \
   } while (0)
Definition at line 49 of file object_api.c.
MAX_CLEANUP
#define MAX_CLEANUP 100
Definition at line 59 of file object_api.c.
ADD_TO_CLEANUP
#define ADD_TO_CLEANUP (func, p)
Value:
do {                          \
   if (cleanup_size < MAX_CLEANUP) {                               \
      cleanup[cleanup_size].fn = (destroy_f)func;             \
      cleanup[cleanup_size++].param = p;                      \
   }                       \
} while (0)
Definition at line 67 of file object_api.c.
MAX_TOKENS
#define MAX_TOKENS 4
Definition at line 75 of file object_api.c.
MAX_GROUP_OBJECTS
#define MAX_GROUP_OBJECTS 32
Definition at line 76 of file object_api.c.
GETOPT_STRING
#define GETOPT_STRING "hv"
Definition at line 217 of file object_api.c.
USEC_TO_SEC
#define USEC_TO_SEC 1000000
Definition at line 258 of file object_api.c.
Typedef Documentation
destroy_f
typedef fpga_result(* destroy_f) (void *p)
Definition at line 58 of file object_api.c.
Function Documentation
print_err()
void print_err (const char * s, fpga_result res)
Definition at line 44 of file object_api.c.
References fpgaErrStr().
Referenced by init_metric_group(), main(), and print_counters().
init_metric_group()
metric_group* init_metric_group (fpga_token token, const char * name, metric_group * group)
Definition at line 106 of file object_api.c.
References metric_group::bus, metric_group::count, metric_group::device, FPGA_OBJECT_GLOB, FPGA_OK, fpgaDestroyProperties(), fpgaGetProperties(), fpgaPropertiesGetBus(), fpgaPropertiesGetDevice(), fpgaPropertiesGetFunction(), fpgaTokenGetObject(), metric_group::function, metric_group::name, metric_group::object, print_err(), and metric_group::token.
Referenced by main().
add_clock()
fpga_result add_clock (token_group * t_group)
Definition at line 141 of file object_api.c.
References ADD_TO_CLEANUP, token_group::clock, FPGA_OBJECT_GLOB, FPGA_OK, fpgaDestroyObject(), fpgaTokenGetObject(), and token_group::token.
Referenced by main().
add_counter()
fpga_result add_counter (metric_group * group, const char * name)
Definition at line 152 of file object_api.c.
References ADD_TO_CLEANUP, metric_group::count, FPGA_EXCEPTION, FPGA_OBJECT_GLOB, FPGA_OK, fpgaDestroyObject(), fpgaObjectGetObject(), named_object::name, named_object::object, metric_group::object, metric_group::objects, and named_object::value.
Referenced by main().
print_counters()
void print_counters (fpga_object clock, metric_group * group)
Definition at line 171 of file object_api.c.
References metric_group::bus, metric_group::count, named_object::delta, metric_group::device, FPGA_OBJECT_SYNC, FPGA_OK, fpgaObjectRead64(), metric_group::function, named_object::name, named_object::object, metric_group::objects, print_err(), and named_object::value.
Referenced by main().
help()
void help (void)
Definition at line 203 of file object_api.c.
Referenced by parse_args().
parse_args()
fpga_result parse_args (int argc, char * argv[])
Definition at line 218 of file object_api.c.
References FPGA_EXCEPTION, FPGA_OK, GETOPT_STRING, and help().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 260 of file object_api.c.
References add_clock(), add_counter(), ADD_TO_CLEANUP, cleanup, cleanup_size, token_group::count, FPGA_DEVICE, FPGA_OK, fpgaDestroyObject(), fpgaDestroyProperties(), fpgaDestroyToken(), fpgaEnumerate(), fpgaGetProperties(), fpgaPropertiesSetObjectType(), token_group::groups, init_metric_group(), config::interval_sec, MAX_TOKENS, metric_group::object, ON_ERR_GOTO, options, parse_args(), print_counters(), print_err(), token_group::token, USEC_TO_SEC, and usleep().
Variable Documentation
struct { ... } cleanup[ 100 ]
Referenced by main().
cleanup_size
STATIC int cleanup_size
Definition at line 65 of file object_api.c.
Referenced by main().
options
struct config options = { 1.0 }
Referenced by main(), and parse_args().