OPAE C API: opae::fpga::types::guid_t Struct Reference
opae::fpga::types::guid_t Struct Reference
#include <opae/cxx/core/pvalue.h>
Public Member Functions
guid_t (fpga_properties *p)
void update ()
operator uint8_t * ()
const uint8_t * c_type () const
guid_t & operator= (fpga_guid g)
bool operator== (const fpga_guid &g)
void parse (const char *str)
bool is_set () const
void invalidate ()
Private Attributes
fpga_properties * props_
bool is_set_
std::array< uint8_t, 16 > data_
Friends
std::ostream & operator<< (std::ostream &ostr, const guid_t &g)
Detailed Description
Representation of the guid member of a properties object.
Definition at line 44 of file pvalue.h.
Constructor & Destructor Documentation
guid_t()
opae::fpga::types::guid_t::guid_t (fpga_properties * p) inline
Construct the guid_t given its containing fpga_properties.
Definition at line 47 of file pvalue.h.
Member Function Documentation
update()
void opae::fpga::types::guid_t::update () inline
Update the local cached copy of the guid.
Definition at line 51 of file pvalue.h.
References ASSERT_FPGA_OK, data_, fpgaPropertiesGetGUID(), is_set_, and props_.
Referenced by operator uint8_t *().
operator uint8_t *()
opae::fpga::types::guid_t::operator uint8_t * () inline
Return a raw pointer to the guid.
Return values
nullptr if the guid could not be queried.
Definition at line 61 of file pvalue.h.
References data_, and update().
c_type()
const uint8_t* opae::fpga::types::guid_t::c_type () const inline
Return a raw pointer to the guid.
Definition at line 68 of file pvalue.h.
References data_.
operator=()
guid_t& opae::fpga::types::guid_t::operator= (fpga_guid g) inline
Assign from fpga_guid Sets the guid field of the associated properties object using the OPAE properties API.
Parameters
[in] g The given fpga_guid.
Returns
a reference to this guid_t.
Definition at line 76 of file pvalue.h.
References ASSERT_FPGA_OK, data_, fpgaPropertiesSetGUID(), is_set_, and props_.
operator==()
bool opae::fpga::types::guid_t::operator== (const fpga_guid & g) inline
Compare contents with an fpga_guid.
Return values
The result of memcmp of the two objects.
Definition at line 89 of file pvalue.h.
References data_, and is_set().
parse()
void opae::fpga::types::guid_t::parse (const char * str) inline
Convert a string representation of a guid to binary.
Parameters
[in] str The guid string.
Definition at line 96 of file pvalue.h.
References ASSERT_FPGA_OK, data_, fpgaPropertiesSetGUID(), is_set_, OPAECXX_HERE, and props_.
is_set()
bool opae::fpga::types::guid_t::is_set () const inline
Tracks whether the cached local copy of the guid is valid.
Definition at line 125 of file pvalue.h.
References is_set_.
Referenced by operator==().
invalidate()
void opae::fpga::types::guid_t::invalidate () inline
Invalidate the cached local copy of the guid.
Definition at line 129 of file pvalue.h.
References is_set_.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & ostr, const guid_t & g) friend
Send the string representation of the guid_t to the given stream.
Definition at line 107 of file pvalue.h.
Field Documentation
props_
fpga_properties* opae::fpga::types::guid_t::props_ private
Definition at line 132 of file pvalue.h.
Referenced by operator=(), parse(), and update().
is_set_
bool opae::fpga::types::guid_t::is_set_ private
Definition at line 133 of file pvalue.h.
Referenced by invalidate(), is_set(), operator=(), parse(), and update().
data_
std::array<uint8_t, 16> opae::fpga::types::guid_t::data_ private
Definition at line 134 of file pvalue.h.
Referenced by c_type(), operator uint8_t *(), operator=(), operator==(), parse(), and update().