OPAE C API: include/opae/uio.h File Reference
uio.h File Reference
APIs to manage a PCIe device via UIO.
#include <stdio.h>
#include <stdint.h>
Data Structures
struct opae_uio_device_region
struct opae_uio
Macros
#define OPAE_UIO_PATH_MAX 256
Functions
int opae_uio_open (struct opae_uio *u, const char *dfl_device)
int opae_uio_region_get (struct opae_uio *u, uint32_t index, uint8_t **ptr, size_t *size)
void opae_uio_close (struct opae_uio *u)
Detailed Description
APIs to manage a PCIe device via UIO.
Presents a simple interface for interacting with a DFL device that is bound to its UIO driver. See https://kernel.org/doc/html/v4.14/driver-api/uio-howto.html for a description of UIO.
Provides APIs for opening/closing the device and for querying info about the MMIO regions of the device.
Definition in file uio.h.
Data Structure Documentation
opae_uio_device_region
struct opae_uio_device_region
MMIO region info
Describes a range of mappable MMIO.
Definition at line 53 of file uio.h.
Data Fields
uint32_t region_index
uint8_t * region_ptr
size_t region_page_offset
size_t region_size
struct opae_uio_device_region * next
opae_uio
struct opae_uio
OPAE UIO device abstraction
This structure is used to interact with the OPAE UIO API. Each UIO device has a file descriptor that is used to mmap its regions into user address space. Each device also has one or more MMIO regions.
Definition at line 68 of file uio.h.
Data Fields
char device_path[256]
int device_fd
struct opae_uio_device_region * regions
Macro Definition Documentation
OPAE_UIO_PATH_MAX
#define OPAE_UIO_PATH_MAX 256
Definition at line 46 of file uio.h.
Function Documentation
opae_uio_open()
int opae_uio_open (struct opae_uio * u, const char * dfl_device)
Open and populate a UIO device
Opens the Device Feature List device corresponding to the device name given in dfl_device, eg "dfl_dev.10". The device must be bound to the dfl-uio-pdev driver prior to opening it. The data structures corresponding to the MMIO regions are initialized.
Parameters
[out] u Storage for the device. May be stack-resident.
[in] dfl_device The name of the desired DFL device.
Returns
Non-zero on error. Zero on success.
Example
$ sudo opaeuio -i -u lab -g lab dfl_dev.10
Example
struct opae_uio u;
if (opae_uio_open(&u, "dfl_dev.10")) {
  // handle error
}
Referenced by hssi_cmd::set_pkt_filt_dest().
opae_uio_region_get()
int opae_uio_region_get (struct opae_uio * u, uint32_t index, uint8_t ** ptr, size_t * size)
Query device MMIO region
Retrieves info describing the MMIO region with the given region index. The device structure u must have been previously opened by a call to opae_uio_open.
Parameters
[in] u The open OPAE UIO device.
[in] index The zero-based index of the desired MMIO region.
[out] ptr Optional pointer to receive the virtual address for the region. Pass NULL to ignore.
[out] size Optional pointer to receive the size of the MMIO region. Pass NULL to ignore.
Returns
Non-zero on error (including index out-of-range). Zero on success.
Example
struct opae_uio u;
uint8_t *virt = NULL;
size_t size = 0;
if (opae_uio_open(&u, "dfl_dev.10")) {
  // handle error
} else {
  opae_uio_region_get(&u, 0, &virt, &size);
}
Referenced by hssi_cmd::set_pkt_filt_dest().
opae_uio_close()
void opae_uio_close (struct opae_uio * u)
Release and close a UIO device
The given device pointer must have been previously initialized by opae_uio_open. Releases all data structures.
Parameters
[in] u Storage for the device info. May be stack-resident.
Example
struct opae_uio u;
if (opae_uio_open(&u, "dfl_dev.10")) {
  // handle error
} else {
  // interact with the device
  ...
  // free the device
  opae_uio_close(&u);
}
Example
$ sudo opaeuio -r dfl_dev.10
Referenced by hssi_cmd::set_pkt_filt_dest().