OPAE C API: include/opae/utils.h File Reference
utils.h File Reference
Utility functions and macros for the FPGA API.
#include <opae/types.h>
#include <stdio.h>
Functions
const char * fpgaErrStr (fpga_result e)
Detailed Description
Utility functions and macros for the FPGA API.
Definition in file utils.h.
Function Documentation
fpgaErrStr()
const char* fpgaErrStr (fpga_result e)
Return human-readable error message
Returns a pointer to a human-readable error message corresponding to the provided fpga_error error code.
Parameters
[in] e Error code (as returned by another FPGA API function
Returns
Pointer to a descriptive error message string
Referenced by fpga_banks(), fpga_base(), fpga_close(), fpga_open(), fpga_set_switch(), fpga_start(), fpga_stop(), fpga_test_ddr_directed(), fpga_test_ddr_prbs(), fpga_test_esram(), fpga_test_hbm(), fpga_test_qdr(), fpga_wait(), main(), parse_args(), and print_err().