include ../../base/sw/base_include_aal.mk

# Primary test name
TEST = test_cci_mpf_null

# Build directory
OBJDIR = obj/aal

# Files and folders
SRCS = $(TEST).cpp $(BASE_FILE_SRC)
OBJS = $(addprefix $(OBJDIR)/,$(patsubst %.cpp,%.o,$(SRCS)))

# Targets
all: $(TEST)_aal

$(TEST)_aal: $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(FPGA_LIBS)

$(OBJDIR)/%.o: %.cpp | objdir
	$(CXX) $(CPPFLAGS) $(CFLAGS) -DUSE_LEGACY_AAL -c $< -o $@

clean:
	rm -rf $(TEST)_aal $(OBJDIR)

objdir:
	@mkdir -p $(OBJDIR)

.PHONY: all clean
