//
// Generated by afu_json_mgr from hello_afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "hello_afu"
`define AFU_ACCEL_UUID 128'h1cddcf01_c266_44de_af63_9d09858310e5
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
