##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################
SET DUT_VLOG_SRC_LIST=C:\ase_Windows\ase/vlog_files.list 

# TODO: remove hardcoded path
SET DUT_INCDIR=C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\include_files+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\include_files\common+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\lpbk1_RdRspRAM2PORT+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\req_C1TxRAM2PORT+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\lpbk1_RdRspRAM2PORT\ram_2port_160+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\lpbk1_RdRspRAM2PORT\synth+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\lpbk1_RdRspRAM2PORT\ram_2port_160\synth+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\req_C1TxRAM2PORT\ram_2port_160+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\req_C1TxRAM2PORT\synth+C:\ase_Windows\ase\sample_config\intg_xeon_nlb\rtl\QSYS_IPs\RAM\req_C1TxRAM2PORT\ram_2port_160\synth+C:\ase_Windows\platforms\platform_if\rtl+C:\ase_Windows\platforms\platform_if\rtl\device_if+

SET SIMULATOR=QUESTA

SET ASE_PLATFORM=FPGA_PLATFORM_INTG_XEON

SET MENT_VLOG_OPT=+define+VENDOR_ALTERA +define+TOOL_QUARTUS +define+NUM_AFUS=1 +define+NLB400_MODE_0 +define+CCIP_IF_V0_1 +define+MPF_PLATFORM_BDX  +define+CCI_SIMULATION=1
