//
// Generated by afu_json_mgr from /home/abelardojara/workspace_remote/intel-fpga-bbb/samples/tutorial/02_hello_world_mpf/hw/rtl/cci_mpf_hello.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "cci_mpf_hello"
`define AFU_ACCEL_UUID 128'h1cddcf01_c266_44de_af63_9d09858310e5
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
