##############################################################
#                                                            #
# Xeon(R) + FPGA AFU Simulation Environment                  #
# File generated by ase/scripts/generate_ase_environment.py  #
#                                                            #
##############################################################

DUT_VLOG_SRC_LIST = $(PATH_TO_VLOG_LIST)/vlog_files.list

DUT_INCDIR = $(PATH_TO_NLB_RTL)/+$(PATH_TO_NLB_RTL)/QSYS_IPs+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/synth+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/ram_2port_160+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/lpbk1_RdRspRAM2PORT/ram_2port_160/synth+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/req_C1TxRAM2PORT+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/req_C1TxRAM2PORT/synth+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/req_C1TxRAM2PORT/ram_2port_160+$(PATH_TO_NLB_RTL)/QSYS_IPs/RAM/req_C1TxRAM2PORT/ram_2port_160/synth+$(PATH_TO_NLB_RTL)/include_files+$(PATH_TO_NLB_RTL)/include_files/common+

SIMULATOR = VCS

ASE_PLATFORM = FPGA_PLATFORM_INTG_XEON

SNPS_VLOGAN_OPT = +define+VENDOR_ALTERA +define+TOOL_QUARTUS +define+NUM_AFUS=1 +define+NLB400_MODE_3

MENT_VLOG_OPT = +define+VENDOR_ALTERA +define+TOOL_QUARTUS +define+NUM_AFUS=1 +define+NLB400_MODE_3
