#!/bin/bash

for f in $(find ./bin -type f -iname "test_*" -not -name "test_pyopae") ; do
  printf "checking $f\n"
  log="${f}.log"

  LD_LIBRARY_PATH=$PWD/../lib \
  OPAE_EXPLICIT_INITIALIZE=1 \
  valgrind \
  -v \
  --log-file=${log} \
  --tool=memcheck \
  --leak-check=full \
  --undef-value-errors=yes \
  --track-origins=yes \
  --show-leak-kinds=all \
  --leak-check-heuristics=all \
  --malloc-fill=0xa1 \
  --free-fill=0xfe \
  ${f}

done
