//
// Generated by afu_json_mgr from /home/abelardojara/cmake_builds/opae-sdk/samples/hello_mpf_afu/hw/hello_mpf_afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "hello_mpf_afu"
#define AFU_ACCEL_UUID "1CDDCF01-C266-44DE-AF63-9D09858310E5"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
