#!/bin/bash
shopt -o -s nounset

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
RPMBUILD_DIR="${SCRIPT_DIR}/rpmbuild"

rm -rf "${RPMBUILD_DIR}"
rm -f "${SCRIPT_DIR}"/opae-*.src.rpm
rm -f "${SCRIPT_DIR}"/opae-*.x86_64.rpm
