//
// Generated by afu_json_mgr from /home/abelardojara/cmake_builds/opae-sdk/samples/hello_intr_afu/hw/hello_intr_afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "hello_intr_afu"
#define AFU_ACCEL_UUID "850ADCC2-6CEB-4B22-9722-D43375B61C66"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu_avalon_mm_legacy_wires"

#endif // __AFU_JSON_INFO__
