#ifndef STI_NOSYS_PROT_PLATFORM_H_INCLUDED
#define STI_NOSYS_PROT_PLATFORM_H_INCLUDED

// Platform defines
#define STI_PLATFORM_NIOS_INICHE 1
#define STI_PLATFORM_WINDOWS 2
#define STI_PLATFORM_LINUX 3

#define STI_NOSYS_PROT_PLATFORM STI_PLATFORM_LINUX

#define ENABLE_MGMT 0

#endif //STI_NOSYS_PROT_PLATFORM_H_INCLUDED
