include ../../base/sw/base_include_aal.mk

# Build directory
OBJDIR = obj/aal

# Files and folders
SRCS = test_mem_perf_common.cpp $(BASE_FILE_SRC)
OBJS = $(addprefix $(OBJDIR)/,$(patsubst %.cpp,%.o,$(SRCS)))

CFLAGS += -DVCMAP_ENABLE_DEFAULT=false

all: test_mem_perf_aal test_mem_latency_aal \
	compute_latency_qos_params_aal \
	compute_vc_map_params_aal

test_mem_perf_aal: $(OBJDIR)/test_mem_perf.o $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(FPGA_LIBS)

test_mem_latency_aal: $(OBJDIR)/test_mem_latency.o $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(FPGA_LIBS)

compute_latency_qos_params_aal: $(OBJDIR)/compute_latency_qos_params.o $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(FPGA_LIBS)

compute_vc_map_params_aal: $(OBJDIR)/compute_vc_map_params.o $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS) $(FPGA_LIBS)

$(OBJDIR)/%.o: %.cpp | objdir
	$(CXX) $(CPPFLAGS) $(CFLAGS) $(OPTS) -DUSE_LEGACY_AAL -c $< -o $@

clean:
	rm -rf *_aal $(OBJDIR)

objdir:
	@mkdir -p $(OBJDIR)

.PHONY: all clean

