name: Build DEBs

on:
  push:
    branches:
      - master
      - 'release/*'
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - 'release/*'
    tags:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  DEB:
    strategy:
      matrix:
        distro: [ubuntu22]
    runs-on: ubuntu-latest
    name: Build ${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . -f docker/${{ matrix.distro }}/Dockerfile -t opae-${{ matrix.distro }}
      - name: Build DEBs
        run: |
          docker run --rm -v ${{ github.workspace }}:/opae-${{ matrix.distro }}/opae-sdk opae-${{ matrix.distro }} /opae-${{ matrix.distro }}/opae-sdk
      - name: Install and Test DEBs
        if: ${{ github.event_name != 'pull_request'}}
        run: |
          docker run --rm -v ${{ github.workspace }}:/opae-${{ matrix.distro }}/opae-sdk --workdir /opae-${{ matrix.distro }}/opae-sdk --entrypoint /bin/bash opae-${{ matrix.distro }} -c "/scripts/test-debs.sh"
      - name: Upload Artifact
        if: ${{ github.event_name != 'pull_request'}}
        uses: actions/upload-artifact@v3
        with:
          name: OPAE-${{ matrix.distro }}
          path:
            ${{ github.workspace }}/packaging/opae/deb/*.deb

