name: C/C++ CI

on:
  push:
    paths-ignore:
      - '.github/workflows/trigger-update.yml'
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - '.github/workflows/trigger-update.yml'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update -y
    - name: Get Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: uuid-dev libjson-c-dev libhwloc-dev lcov linux-headers-generic
    - name: configure
      run: mkdir ${{ github.workspace }}/.build && cd ${{ github.workspace }}/.build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPAE_ENABLE_MOCK=ON -DOPAE_BUILD_TESTS=ON -DOPAE_PYTHON_VERSION=3
    - name: make
      run: cd ${{ github.workspace }}/.build && make -j
    - name: set hugepages
      run: sudo sysctl -w vm.nr_hugepages=8
    - name: test
      run: cd ${{ github.workspace }}/.build && ctest --timeout 180
      env:
        OPAE_EXPLICIT_INITIALIZE: 1
        LD_LIBRARY_PATH: ${{ github.workspace }}/.build/lib
