name: C/C++ CI Build and Test (dummy)

# https://github.com/ossf/scorecard/blob/9ff40de429d0c7710076070387c8755494a9f187/docs/checks.md#token-permissions
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release, RelWithDebInfo]
    steps:
    - run: exit 0
  test:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
