name: python static analysis (dummy)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - run: exit 0
