name: python static analysis (dummy)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - run: exit 0
