name: python static analysis (dummy)

# https://github.com/ossf/scorecard/blob/9ff40de429d0c7710076070387c8755494a9f187/docs/checks.md#token-permissions
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - run: exit 0
