name: python static analysis (dummy)

on:
  workflow_dispatch:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - run: exit 0
