on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
name: Create Release
jobs:
  build:
    - name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: |
              Open Programmable Acceleration Engine (OPAE) ${{ github.ref }} Release Notes
              ----------------------------------------------------------------------------------------------------------------------
              OPAE ${{ github.ref }} release provides SDK, tools, and Linux kernel driver.  The main feature of this release is to support Intel速 FPGA Programmable Acceleration Card N3000 series.

              System Compatibility
              ----------------------------------
              - Hardware: Tightly coupled FPGA products and programmable FPGA acceleration cards for Intel(R) Xeon(R) processors:
                o Intel速 FPGA Programmable Acceleration Card N3000-2 Production Release
                o Intel速 FPGA Programmable Acceleration Card N3000-V Production Release
                o Intel速 FPGA Programmable Acceleration Card N3000-3 Production Release
              - Operating System: Tested on Fedora 31 with Linux Kernel 5.8 version.

                Major Changes from X.Y.Z to ${{ github.ref }}
              -------------------------------------------------------
              - Changes go here...

                Source Code
              ----------------------------------
              - FPGA DFL Linux driver source code:  tag  ${{ github.ref }}
                o https://github.com/OPAE/linux-dfl/tree/fpga-upstream-dev-5.8.0

              - SDK and tools source code:  tag ${{ github.ref }}-1
                o https://github.com/OPAE/opae-sdk/tree/release/${{ github.ref }}
                o https://github.com/OPAE/opae-libs/tree/release/${{ github.ref }}
                o https://github.com/OPAE/opae-legacy/tree/release/${{ github.ref }}
                o https://github.com/OPAE/opae-test/tree/release/${{ github.ref }}

                Notes/Known Issues
              ----------------------------------
              - FPGA DFL kernel driver upstreaming to Linux kernel is ongoing.
              - OPAE ${{ github.ref }} is not be compatible with Intel production FPGA driver.
            draft: true
            prerelease: false
        - name: Create tarball
          run: |
            git clone https://github.com/pybind11/pybind11.git external/pybind11 -b v.2.6.0
            ./scripts/create-tarball.sh ${{ github.ref }}
        - name: Upload Release Asset
          id: upload-release-asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./opae-${{ github.ref }}.tar.gz
            asset_name: opae-${{ github.ref }}.tar.gz
            asset_content_type: application/gzip



